### ISSUE TITLE
Custom headers end up in URL parameters instead of HTTP headers section

### ISSUE THREAD

**Issue by lpandzic** [Atmosphere/atmosphere#1095]
When setting custom headers in request like this:

var headers = {};
            headers["Authorization"] = "Basic " +  "${basicAuth}";

var request = {
        url: notifiactionsUrl,
        contentType: "application/json",
        logLevel: 'debug',
        headers: authHeaders,
        transport: 'websocket'
};

they end up in http url parameters section. Fallback system sets them properly in http headers.
So for example this works with no error:
var headers = {};
            headers["Authorization"] = "Basic " +  "${basicAuth}";

var request = {
        url: notifiactionsUrl,
        contentType: "application/json",
        logLevel: 'debug',
        headers: authHeaders,
};

but then I have no control over transport protocol used.

**Comment by vineet-verma** [comment]
attachHeadersAsQueryString:false drops the custom header from query param string but neither custom header come in request header section in network call nor received at server end in request. I can not get the custom header anyway at server end. I also used (dropHeaders:false) but did not work.
 url: "http://channelurl,
					transport: 'sse',
						enableXDR:true,
						attachHeadersAsQueryString:false,
						headers:{
							'Authorization':'bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImFkc19jZXJ0MiJ9.eyJzY29wZSI6W10sImNsaWVudF9pZCI6Im1hcmtpdF9zZXJ2aWNlIiwianRpIjoieEl3ZmxsUWdIcGxqUmw3NmdyRHpqYXZuSXJxdThLTm4iLCJlbWFpbF9hZGRyZXNzIjoiUGF1bC5tYXJ0aW5AaWNiY3N0YW5kYXJkLmNvbSIsIm1lbWJlcl9zdGF0dXMiOiJQYXVsIiwibmFtZSI6IlBhdWwiLCJsYXN0X25hbWUiOiJQYXVsIiwibWlkZGxlX25hbWUiOiJQYXVsIiwiZmlyc3RfbmFtZSI6InBhdWwubWFydGluIiwidXNlcmlkIjoicGF1bC5tYXJ0aW4iLCJleHAiOjE0OTc0NDA5NDR9.PZrltrtycM-U2Fw9JPAVGpsDXE8hyLP2N2lWqqE44YxJhvHE0SjJJfsal6QPAkdHoz2_zJCyMnTrz_pu4ko-7_739zrEzGeDr9m-iMNz52nMQNK3VVC2nMGDOyC-VtEFGT1V3zlue6OWXdQqf-gidlalSVpWvkOPAft9fpukm0aqZijeP1JGcxSvcNBu1Jnm6wA7SWEJnWvo3K7J77HZ57wZmic6eLeP6XlPUpS9qhRRf2WbSZ4XdGLSujadXrAPVLGDZvrEYHuv6Ko7WrrLArE8X1oRnjRCRf4fd4OcUzEW42BgxD8xws2zLq9RP-jK69P6jB80N3w13bhjWj4Kzw'
						}
