### ISSUE TITLE
Firefox closes websocket/streaming/long-polling request when window.location is changed

### ISSUE THREAD

**Issue by Legioth** [Atmosphere/atmosphere#1128]
When a value is written to window.location, it usually means that the current page will be unloaded. The new location might however be e.g. a download or a mailto URI that opens in an external program and in such cases the document will not be unloaded. The problem is that in firefox does still close all pending requests and all open websocket connections. It seems that in this situation Atmosphere attempts to reopen the connection, but for some reason two connection attempts are made with the javascript listening to data from the first opened connection whereas the server sends data to the second connection. The end result of this is that no messages are received from the server.

Tested using the chat sample from the head of the atmosphere-1.0.x branch by adding a button that runs `window.location = 'mailto:foo@bar@.com';`.

**Comment by drogatkin** [comment]
window.open helps here.

**Comment by jfarcand** [comment]
@drogatkin Contribution welcomed...
