### ISSUE TITLE
detect if a disconnect is due to a timeout ex: when setting maxInactiveActivity

### ISSUE THREAD

**Issue by omar-aguilar** [Atmosphere/atmosphere#1137]
At the moment is not possible to detect whether a onConnect, onDisconnect event on the server was due to a timeout event like when setting maxInactiveActivity or due a client event like closing the browser

This could be helpful if for example you send a broadcast in those events to say that the client is online or offline, but if the timeout occurs internally there is a disconnect and connect events and if the client is still there you end up sending connect and disconnect messages each time the timeout fires

This originally was because when you unplug the network cable or if you are in a wifi and then turn off the wifi the websocket on the server never realizes about this, it thinks that the client is still connected, so a way to solve this on the server side is adding this maxInactiveActivity but this fires an onDisconnect and onConnect events each time it fires

**Comment by jfarcand** [comment]
Next official version https://github.com/Atmosphere/Atmosph4rX
