### ISSUE TITLE
Need configuration option for disabling analytics.

### ISSUE THREAD

**Issue by klieber** [Atmosphere/atmosphere#1212]
Currently, whenever an Atmosphere application is started a thread is started that hits http://async-io.org/version.html to validate whether or not the latest version of Atmosphere is in use and then appears start up some analytics tracking.

Here is the code in question: [AtmosphereFramework.java](/atmosphere/atmosphere/blob/master/modules/cpr/src/main/java/org/atmosphere/cpr/AtmosphereFramework.java#L633)

I don't mind this while I'm in development but I fail to see the value it brings me in a production environment so I need to be able to disable it before moving to production.  A simple init parameter would probably suffice.

Also, it seems like the default for this should be to have it turned off.

I'd probably have some time to make these changes and send over a pull request once I have feedback from you on how exactly you'd like to handle it.

Thanks!

**Comment by basisbit** [comment]
how does this comply with GDPR and similar other legal stuff which requires one to ask / inform the user first? @jfarcand 
Sadly, http://async-io.org/ also does not contain any details about what data is tracked / stored and son on.

**Comment by jfarcand** [comment]
@basisbit https://github.com/Atmosphere/atmosphere/blob/atmosphere-2.5.x/modules/cpr/src/main/java/org/atmosphere/cpr/ApplicationConfig.java#L831
