### ISSUE TITLE
[Atmosphere/TomEE] WARNING: Unable to detect annotations. Application may fail to deploy.

### ISSUE THREAD

**Issue by smithh032772** [Atmosphere/atmosphere#1349]
see mail list topic[1]

[1] https://groups.google.com/forum/?fromgroups#!topic/atmosphere-framework/PcYoqKZ3_Aw

**Comment by salviof** [comment]
Maybe Atmosphere  should use The Reflection API tools from apache:
The easy mode:
  List<Class> lista = new ArrayList<>();
   Reflections reflections = new Reflections("pakage");
    Set<Class<?>> annotated = reflections.getTypesAnnotatedWith(anotation.class);

       <dependency>
            <groupId>org.reflections</groupId>
            <artifactId>reflections</artifactId>
            <version>0.9.10</version>
        </dependency>
Or  maybe  alow custom AnnotationProcessor...

**Comment by jfarcand** [comment]
@salviof Atmosphere supports that. Check the documentation (via web.xml)
