### ISSUE TITLE
License: Apache/CDDL/GPL2 with exception

### ISSUE THREAD

**Issue by DamianFekete** [Atmosphere/atmosphere#1415]
There are about 50 files that have a somewhat confusing license header. For example: https://github.com/Atmosphere/atmosphere/blob/master/modules/cpr/src/main/java/org/atmosphere/cpr/Broadcaster.java where it is stated that:

```
Licensed under the Apache License, Version 2.0 (the "License")
...
The contents of this file are subject to the terms of either the GNU General 
Public License Version 2 only ("GPL") or the Common Development and 
Distribution License("CDDL") (collectively, the "License")
```

Which is `the "License"`? Is there any code left in the sources from Sun Microsystems, Inc that is not under the Apache license?

**Comment by rahulmohang** [comment]
Hi @jfarcand, 

Many files in the latest version too carry both the license statements. Can you please let me know if you have reached a conclusion?
