### ISSUE TITLE
long-polling protocol (at least) doesn't encode messages as UTF-8 like websocket

### ISSUE THREAD

**Issue by tehnicaorg** [Atmosphere/atmosphere#1424]
Using the long-polling protocol messages that must be encoded as UTF-8 won't be received by the client by default. One must call the [setCharacterEncoding](http://docs.oracle.com/javaee/6/api/javax/servlet/ServletResponse.html#setCharacterEncoding(java.lang.String%29) explicitly.

I think the protocols(long-polling and websocket) should behave the same.

Please see https://github.com/Atmosphere/atmosphere-samples/issues/8 discussion.

**Comment by jfarcand** [comment]
OK closing this issue as WON'T fix as it will have too much side effect. @flowersinthesand will take care of that in Atmosphere 3.

**Comment by flowersinthesand** [comment]
@tehnicaorg I agree with your point. Atmosphere 3 aka [Vibe](http://vibe-project.github.io/) protocol's all transports use UTF-8 as charset.
