### ISSUE TITLE
NullReferenceException thrown when calling BroadcasterFactory.lookup

### ISSUE THREAD

**Issue by jbrx107** [Atmosphere/atmosphere#1468]
When I call this code:

``` java
 BroadcasterFactory factory = BroadcasterFactory.getDefault();
                Broadcaster broadcaster = factory.lookup("hello");
```

It looks like there is a missing null check somewhere in the code.

I get this exception (Tomcat 7.0.47 with Chrome latest browser/Safari latest browser):

Error: {"readyState":4,"responseText":"<html><head><title>Apache Tomcat/7.0.47 - Error report</title><style></style> </head><body><h1>HTTP Status 500 - java.lang.NullPointerException</h1><HR size=\"1\" noshade=\"noshade\"><p><b>type</b> Exception report</p><p><b>message</b> <u>java.lang.NullPointerException</u></p><p><b>description</b> <u>The server encountered an internal error that prevented it from fulfilling this request.</u></p><p><b>exception</b> <pre>javax.servlet.ServletException: java.lang.NullPointerException\n\torg.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:333)\n\torg.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:372)\n\torg.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:335)\n\torg.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:218)\n\torg.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)\n</pre></p><p><b>root cause</b> <pre>java.lang.NullPointerException\n\tWebServicesPublic.Todos.Create(Todos.java:105)\n\tsun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tsun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\n\tsun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tjava.lang.reflect.Method.invoke(Method.java:606)\n\torg.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)\n\torg.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:125)\n\torg.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:195)\n\torg.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:91)\n\torg.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:346)\n\torg.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:341)\n\torg.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:101)\n\torg.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:224)\n\torg.glassfish.jersey.internal.Errors$1.call(Errors.java:271)\n\torg.glassfish.jersey.internal.Errors$1.call(Errors.java:267)\n\torg.glassfish.jersey.internal.Errors.process(Errors.java:315)\n\torg.glassfish.jersey.internal.Errors.process(Errors.java:297)\n\torg.glassfish.jersey.internal.Errors.process(Errors.java:267)\n\torg.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)\n\torg.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:198)\n\torg.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:946)\n\torg.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:323)\n\torg.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:372)\n\torg.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:335)\n\torg.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:218)\n\torg.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)\n</pre></p><p><b>note</b> <u>The full stack trace of the root cause is available in the Apache Tomcat/7.0.47 logs.</u></p><HR size=\"1\" noshade=\"noshade\"><h3>Apache Tomcat/7.0.47</h3></body></html>","status":500,"statusText":"Internal Server Error"}

**Comment by tedpoovey** [comment]
Well that is TOTALLY unhelpful.  Just like the documentation.  And the arcane setup.  And all the samples don't do named broadcasters.  So yeah.  Pretty much not great here.  Horrible user experience.
