### ISSUE TITLE
[AtmosphereResourceLifeCycleInterceptor] Prevent application error by suspending first

### ISSUE THREAD

**Issue by jfarcand** [Atmosphere/atmosphere#1524]
Right now `AtmosphereResource#suspend` is invoked after the `AtmosphereHandler` gets invoked. If an application/user write some bytes with the `AtmosphereHandler`, the bytes will be written before interceptor like `JavaScriptProtocol` get a chance to execute the Atmosphere's Handshake if `enableProtocol:true`

**Comment by silvpol** [comment]
Workaround sounds better. When using AtmosphereHandler and AtmosphereResourceLifeCycleInterceptor it's useful to be able to modify response headers before suspending. In our case we disable compression dynamically based on transport used.

**Comment by jfarcand** [comment]
Won't change that with `2.x`. Will re-evaluate in 3.x
