### ISSUE TITLE
[jsr356] Wrong pathInfo computed.

### ISSUE THREAD

**Issue by jfarcand** [Atmosphere/atmosphere#1527]
[See](https://groups.google.com/forum/#!topic/atmosphere-framework/ntIHOohlYIc)

**Comment by noherbert** [comment]
I'm affected by this error with atmosphere version 2.3.3

I have a @ManagedService(path="/") which works fine, but the moment i change the path to anything different from "/" i get these error.

My stacktrace is avaiable at http://pastebin.com/ey4mdT3G

**Comment by noherbert** [comment]
I am using wildfly 8.1 and NetBeans 8.0

I tried setting the context-path in the jboss-web.xml to "/" like suggested in https://github.com/Atmosphere/atmosphere/wiki/AtmosphereHandler-not-being-found,-when-using-NetBeans-IDE
but it didn't help with the problem

**Comment by jfarcand** [comment]
@noherbert Running inside Netbean is not supported. Running outside should work.

**Comment by noherbert** [comment]
Hi jfarcand! Thank you for your response!
What exactly do you mean by running outside NetBeans? Because if i am building manually by maven commandline and deploy over WildFly's webinterface the error persists
