### ISSUE TITLE
Possible ClassCastException when resolving AtmosphereResource

### ISSUE THREAD

**Issue by gdrouet** [Atmosphere/atmosphere#1561]
As far as I understand the code, [this](https://github.com/Atmosphere/atmosphere/blob/master/modules/cpr/src/main/java/org/atmosphere/cpr/AsynchronousProcessor.java#L229) can produce a ClassCastException if the user set an ObjectFactory which does not return an AtmosphereResourceImpl

**Comment by jfarcand** [comment]
Won't fix this issue as it is too risky for a 2.x changes. In 3.0 those issues are fixed.
