### ISSUE TITLE
[OSGi] MeteorServlet.init() - two calls to delegate servlet init() method 

### ISSUE THREAD

**Issue by dstoch** [Atmosphere/atmosphere#1571]
Delegated servlet is initialized twice (in 2.1.3):
1. inside framework.addAtmosphereHandler() line 373
2. inside framework.initAtmosphereHandler() line 1339
This 1 fragment was added in 2.0.8, in previous versions it works ok (servlet.init() was called only once).

I am using OSGi HttpService (from PaxWeb) to register servlet. The call stack is that HttpService registers already created servlet instance and perform initialization by calling servlet.init() method. I am using MeteorServlet to wrap my own servlet (delegated one). And inside MeteorServlet.init(ServletConfig) ReflectorServletProcessor instance is created and on line 96 added as an AtmosphereHandler and initialized:
framework.addAtmosphereHandler(delegateMapping, r).initAtmosphereHandler(sc);

**Comment by jfarcand** [comment]
@dstoch Can you share a test case or try with 2.2.4? Thanks!

**Comment by dstoch** [comment]
I'll try to restest it with 2.2.4.

**Comment by jfarcand** [comment]
@dstoch Thanks for the help. I've pushed a fix in 2.3.0-SNAPSHOT based on your help. Let me know if that help.
