### ISSUE TITLE
MeteorServlet using Java config

### ISSUE THREAD

**Issue by vert3x** [Atmosphere/atmosphere#1587]
Hi, I'm new to Atmosphere framework, I'm working on a project with zero xml, everything is configured using Spring annotations.
I tried to register MeteorServlet like this 
<code>
       @Bean
	public ServletRegistrationBean servletRegistrationBean(){
	    return new ServletRegistrationBean(new MeteorServlet());
         }
</code>

but I always get <code>java.lang.IllegalStateException: MeteorServlet not defined in web.xml</code>

Thank you.

**Comment by seamusmac** [comment]
Not sure this is really an issue.
I am using pure java config with Spring and Atmosphere now, and I am having no issues. 

Instead of the WebAppInitializer extending AbstractAnnotationConfigDispatcherServletInitializer 
remove the servletRegistrationBean from WebAppConfig also.

try making it implement WebApplicationInitializer, and add the servlet initialization there. eg. 

```java
 public class Initializer implements WebApplicationInitializer {  
      
    @Override  
    public void onStartup(ServletContext servletContext) throws ServletException {  
          
        AnnotationConfigWebApplicationContext ctx = new AnnotationConfigWebApplicationContext();  
        ctx.register(WebAppConfig.class);  
          
        ctx.setServletContext(servletContext);    
          
        Dynamic servlet = servletContext.addServlet("dispatcher", new DispatcherServlet(ctx));  
        servlet.addMapping("/");  
        servlet.setLoadOnStartup(1);  

        ServletRegistration.Dynamic atmosphereServlet = container.addServlet("MeteorServlet", MeteorServlet.class.getName());
		atmosphereServlet.setLoadOnStartup(1);
		atmosphereServlet.addMapping("/meteor/*");
		atmosphereServlet.setAsyncSupported(true);
 
          
        }  
  
     }  
```

**Comment by jfarcand** [comment]
@seamusmac Thanks fior checking. Closing as `fixed`, @vert3x re-open if you still can't makle it work.

**Comment by Omi004** [comment]
I am getting the same error while integrating atmosphere example form https://github.com/GregaVrbancic/spring-atmosphere-chat-example (which  is xml based) in my existing application which is java base configured.

`public class AppInitializer extends AbstractAnnotationConfigDispatcherServletInitializer {

	@Override
	protected Class<?>[] getRootConfigClasses() {
		return new Class[] { AppConfig.class };
	}
 
	@Override
	protected Class<?>[] getServletConfigClasses() {
		return null;
	}
 
	@Override
	protected String[] getServletMappings() {
		return new String[] { "/" };
	}

	@Override
    protected void registerDispatcherServlet(ServletContext servletContext) {
        super.registerDispatcherServlet(servletContext);

        ServletRegistration.Dynamic atmosphereServlet = servletContext.addServlet("MeteorServlet", MeteorServlet.class.getName());
        atmosphereServlet.setLoadOnStartup(1);
        atmosphereServlet.addMapping("/");
        atmosphereServlet.setAsyncSupported(true);
        servletContext.addServlet("MeteorServlet", MeteorServlet.class);
    }
	
	 @Override
		protected void customizeRegistration(ServletRegistration.Dynamic registration) {
	    	registration.setMultipartConfig(getMultipartConfigElement());
		}

	    private MultipartConfigElement getMultipartConfigElement(){
			MultipartConfigElement multipartConfigElement = new MultipartConfigElement(LOCATION, MAX_FILE_SIZE, MAX_REQUEST_SIZE, FILE_SIZE_THRESHOLD);
			return multipartConfigElement;
		}
	    
	    /*Set these variables for your project needs*/ 
	    
		private static final String LOCATION = "D:/mytemp/";

		private static final long MAX_FILE_SIZE = 1024 * 1024 * 25;//25MB
		
		private static final long MAX_REQUEST_SIZE = 1024 * 1024 * 30;//30MB

	    private static final int FILE_SIZE_THRESHOLD = 0;
}`

This is my class and I have tried to add meteorservlet in it.But still getting the same error.
You can also refer the stackoverflow question: http://stackoverflow.com/questions/40292382/how-to-integrate-atmosphere-configuration-in-springs-java-based-configuration-u

Thanks,
Omi
