### ISSUE TITLE
PrimePush (Primefaces 5) with TomEE 1.6 Error: can't find annotations

### ISSUE THREAD

**Issue by karlkilden** [Atmosphere/atmosphere#1624]
Added PrimeFaces push notify example according to Primefaces docs. Tested with various versions of Atmosphere but I always get:

2014:06:09 10:15:27 ERROR  org.primefaces.push.PushServlet: No Annotated class using @PushEndpoint found. Push will not work.

Full startup log below with debug enabled. I tested my slf4j config by using warn first, as it turns out no debug statements where reached as far as I can see. I also verified this by verious breakpoints at statements with debug logging in AtmosphereFramework.java

https://gist.github.com/karlkilden/a8ddfac2609f4d470761
##### This is easy to reproduce with my test project:

https://github.com/karlkilden/ref The readme explains how to run it.
I added PrimePush for the function "Group Setup". In the gui you click Admin -> Group Management -> Setup Group and create a group (just random name will suffice).

the source code is groupSetup.xhtml (the socket is in template.xhtml) The bean is GroupSetupBean.java

The EndPoint is: NotifyResource.java

**Comment by jeanse7en** [comment]
Hello,
How can you solve it?

**Comment by salviof** [comment]
+
