### ISSUE TITLE
AtmosphereResourceSessionListener

### ISSUE THREAD

**Issue by fcorneli** [Atmosphere/atmosphere#1630]
A nice feature would be an AtmosphereResourceSessionListener interface. This would ease the cleanup of AtmosphereResources that are kept in a Map for optimal search performance (for fast selective broadcasting). Interface would be similar to:
http://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpSessionListener.html

**Comment by jfarcand** [comment]
#1824 is doing something quite similar to what you asked, so closing as fixed. Try it and let me know.
