### ISSUE TITLE
UUIDBroadcastCache buffer messages on timeout/severed connections

### ISSUE THREAD

**Issue by digitaldan** [Atmosphere/atmosphere#1674]
This is related to #1655 

Following the same flow as in #1655, if a broadcast message is sent after a client has abruptly disconnected (ctrl-c or timeout for example) but before that client has reconnected, then the message is silently lost.  The expected behavior would be that the broadcast cache would retain the message if the client is not connected.   As a note, messages sent after the client has reconnected are delivered fine (per #1655), only messages sent while the client is disconnected are lost.

**Comment by jfarcand** [comment]
Closing as fixed.
