### ISSUE TITLE
Documentation: Failed to get Atmosphere 2.3 to run on WebSphere 7 (Java EE 5/Servlet 2.5)

### ISSUE THREAD

**Issue by Jeff-Walker** [Atmosphere/atmosphere#1751]
The documentation says: 
"The Atmosphere Framework Stack works on all Servlet based servers including Tomcat, JBoss Jetty, Resin, GlassFish, Undertow, WebSphere, WebLogic etc." And in the list of servers you have WebSphere 7.

But, I was unable to make the chat sample (or any test app) run on WebSphere 7 and Java EE 5. When I used WebSphere 8.5 and Java EE 6, everything worked well. The hang-up is Servlet 3.0 I think. I spent a lot of time failing to make it work. I even tried using an atmosphere.xml file, which will forego the annotation scanning, but that didn't work either; I got the same messages. There is no documentation on using the atmosphere.xml, but I realize that most people aren't stuck in 2008 with their application servers.

Great framework and thanks.

**Comment by jfarcand** [comment]
Ok closing this issue, once you have a solution just update the thread. Thanks

**Comment by Jeff-Walker** [comment]
Thanks for your help on this. I've moved to WebSphere 8.5 for this project
and that supports Servlet 3.0 and has no problem with Atmosphere. I'm sorry
I don't have time to struggle through with WebSphere 7, but it sounds like
that isn't a problem you've run into much anyway. I'm looking forward to
using Atmosphere in my project. Thanks.

**Comment by Jeff-Walker** [comment]
So, an update with my experience with WebSphere 8.5 (liberty profile). Like I said, the Servlet 3.0 support enabled async servlets, which made Atmosphere work in the first place. I did have trouble again with the `wsjar://` URL business. 
Basically, if the Atmosphere libraries are loaded from a different classloader (parent classloader in this case) than the current classloader (one that the servlet itself runs in), WebSphere hands out `wsjar://` URLs, which aren't compatible with `jar://` URLs, which the Atmosphere AnnotationDetector needs. There is a settting in WebSphere 8.5 that forces the classloader to hand out jar: URLs instead of `wsjar://` URLs.
I think this should probably go in as a footnote or something in the docs that talk about WebSphere.

**Comment by jfarcand** [comment]
@Jeff-Walker Thanks Jeff, really appreciated. Can you just create a page on the FAQ with your information https://github.com/Atmosphere/atmosphere/wiki/Frequently-Asked-Questions ? Thanks a lot!

**Comment by Jeff-Walker** [comment]
Yep, will do.
I found that there's a problem with hierarchical class loaders when the Atmosphere classes are loaded from a classloader that is above where the code it is scanning. The way it works (at least in WebSphere, but I think it is Java EE standard) is that your code in your web project (WAR) loads classes from its library directory, then the EAR libraries, then finally the app server. If the Atmosphere jars are in the EAR and my code is in the WAR, my code has to go a level above to the EAR to get Atmosphere. Atmosphere then scans its classpath for annotated classes. It will never find my class because the classloader won't search downward, it only knows about itself and its parent. I've had this problem with logging frameworks being loaded and then can't find the log.properties files in the classpath. My solution will be to always put Atmosphere at the same level as my handler code, so my handlers will always have to be in the WAR. I don't have a suggestion on how to make that work better. That will work for me, and probably most everyone else, which is why I didn't find all of this on the Internet.

So, this "issue" actually covers three separate problems. Once again, thanks for your help.

**Comment by Jeff-Walker** [comment]
I added https://github.com/Atmosphere/atmosphere/wiki/No-AtmosphereHandler-found-when-using-hierarchical-classloaders.  I'll also add a WebSphere page to the "Known WebServer Issues" list.

I would also suggest we remove WebSphere 7 from the supported servers list. Maybe someone else could get it working, but I would have saved myself a lot of time if I knew what was in store. I'll do it with your permission.

**Comment by heatherD79** [comment]
Has anyone successfully run Atmosphere on Websphere 7? We're running in to the same problems as above and are hoping that maybe someone has already worked through the issues. 

Upgrading to Websphere 8.5 is a more difficult hurdle for us than we were prepared to handle.

Any assistance or direction would be greatly appreciated.

**Comment by Jeff-Walker** [comment]
I gave up trying to run it on WebSphere 7. It doesn't support async
servlets, if I remember correctly, which was the unfixable problem. It
worked fine in WebSphere 8.5.

**Comment by jfarcand** [comment]
@heatherD79 If you really needs it, either you contribute supports or you buy some professional services with Async-Io.org.
