### ISSUE TITLE
HeartbeatInterceptor executed before IdleResourceInterceptor

### ISSUE THREAD

**Issue by freongrr** [Atmosphere/atmosphere#1760]
I'm using client heartbeats, but `IdleResourceInterceptor` keeps cancelling my resources.

It turns out that `IdleResourceInterceptor#inspect()` is never called (and the "MAX_INACTIVE" property is never updated), because `HeartbeatInterceptor` is invoked first, and it cancels the request from the client.

How about bumping up `IdleResourceInterceptor` in the list of default interceptors in `AtmosphereFramework`?

```java
For reference, this is my handler definition:

    @ManagedService(
      path = "/push",
      interceptors = {
        AtmosphereResourceLifecycleInterceptor.class,
        TrackMessageSizeInterceptor.class,
        SuspendTrackerInterceptor.class,
        GwtRpcInterceptor.class,
        AtmosphereMessageInterceptor.class,
      },
      atmosphereConfig = {
        "org.atmosphere.interceptor.HeartbeatInterceptor.clientHeartbeatFrequencyInSeconds=60",
        "org.atmosphere.cpr.CometSupport.maxInactiveActivity=180000"
      }
    )
    public class TestPushManager {
      ...
    }
```
And this is the order of interceptors when I hit `AsynchronousProcessor#action()`:

* UUID Tracking Interceptor
* Track Message Size Interceptor using |
* CORS Interceptor Support
* Default Response's Headers Interceptor
* Browser Padding Interceptor Support
* Android Interceptor Support
* **Heartbeat Interceptor Support**
* SSE Interceptor Support
* JSONP Interceptor Support
* Atmosphere JavaScript Protocol
* org.atmosphere.interceptor.WebSocketMessageSuspendInterceptor
* Browser disconnection detection
* **org.atmosphere.interceptor.IdleResourceInterceptor**

**Comment by jfarcand** [comment]
@freongrr Any update?

**Comment by freongrr** [comment]
So, I could not test because the load balancer my company uses drops some websocket messages...

**Comment by jfarcand** [comment]
@freongrr Any feedback? I'm tempted to switch the order, but I first want feedback from you.

**Comment by freongrr** [comment]
As I said above, I had to stop using websockets. The change worked during my limited testing, but I could not see how it worked in a real deployment.

**Comment by jfarcand** [comment]
With #1877 , IdleResourceInterceptor will always be executed first. Closing as fixed, but in case you have time, please test :-)
