### ISSUE TITLE
Completely remove BroadcasterFactory.getDefault

### ISSUE THREAD

**Issue by jfarcand** [Atmosphere/atmosphere#1762]
Deprecated in 2.2, removed in 2.3

**Comment by krissco** [comment]
With this functionality removed, and the examples not updated (https://github.com/Atmosphere/atmosphere/wiki/Getting-Started-with-Meteor,-WebSocket-and-Long-Polling), I'm not sure how to refactor my code to use newer versions of the Atmosphere Framework. Do you have any updated examples on how to get the default BroadcasterFactory?

Thank you.

**Comment by jfarcand** [comment]
See: https://github.com/Atmosphere/atmosphere/wiki/Injecting-Atmosphere-components-and-factories-using-the-javax.inject.Inject . Please file a new issue for the sample.
