### ISSUE TITLE
v2.2.4: Can't open websocket in Android browser to Jetty 9.2.5.v20141112

### ISSUE THREAD

**Issue by dreamershl** [Atmosphere/atmosphere#1814]
When try to open the connection through websocket, the server side receive the following string. The method is 'OPTIONS' instead of 'GET'.

(OPTIONS /comet/stock?X-Atmosphere-tracking-id=0&X-Atmosphere-Framework=2.2.6-javascript&X-Atmosphere-Transport=long-polling&X-Atmosphere-TrackMessageSize=true&Content-Type=application%2Fjson&X-atmo-protocol=true&_=1418261777398)@2106345160 org.eclipse.jetty.server.Request@7d8c46c8

And the AsynchronousProcessor fail because the req.isAsyncSupported() is false!!!

```
   if (isServlet30 && (!req.isAsyncSupported() && !Utils.closeMessage(req))) {
```

This error happened only after I upgrade to the latest version of Jetty & Atmosphere.

**Comment by dreamershl** [comment]
Hi,
   Now I am pretty sure it is a android (4.1 ~ 4.3) issue. The later android version won't have this issue. According to the wiki, http://en.wikipedia.org/wiki/Android_version_history, the 4.1~4.3 is about 80% usage. Thanks

**Comment by dreamershl** [comment]
Would like to raise an attention on this function of the AtmosphereServlet::doOptions 

Is it correct to treat the HTTP OPTIONS request as "POST"? normally it should just return the header like "Allow: GET, xxxx"

**Comment by dreamershl** [comment]
Finally find out the root cause of the issue. Android 4.1~4.3 doesn't support websocket. they only support CROS. When try to set up the "long-polling" transport, android browser will issue 2 request, options + post. The library doesn't handle the options correctly, it should return the allowed method list. 

another potential issue is the browser seems have some issue to support the CROS request. But with the Cordova webview, the CROS will be success with the "webview.setAllowUniversalAccessFromFileURLs(true)"

To fix the library OPTIONS handling issue just simply come out another child class of "AtmosphereGuiceServlet" and overwrite  the doOptions() as the following 

    public void doOptions(HttpServletRequest req, HttpServletResponse res) throws IOException, ServletException
    {
        res.setHeader("Allow", "GET,HEAD,POST");
    }

And use this new class in the web.xml. Then you should be able to get the connection up in android

**Comment by jfarcand** [comment]
@dreamershl Not sure I understan your issue here. You don't have to extend `doOptions` with that header is Jetty is properly configured.

**Comment by dreamershl** [comment]
Jetty default implementation will take effect only when servlet class doesn't provide its own "options" handler "doOptions". But AtmosphereServlet has its own implementation of "doOptions". That is why the above is needed. Thanks.

**Comment by jfarcand** [comment]
@dreamershl We do have several deployment with CORS enabled and this has never been needed. Are you able to reproduce the issue with a normal browser.

**Comment by dreamershl** [comment]
Just for your info, I have put all the detail here http://stackoverflow.com/questions/27745839/fail-to-set-up-the-connection-with-atmosphere-2-2-4-in-android4-1-4-3-web. 

Yes, you are right. **The current options handing won't cause any issue**. Because HTTP doesn't really define how to process the options method, *browser seems will just ignore the response without 'allow' header*.

Now it is clear,  **the key reason for issue is the 'req.isAsyncSupported()"** . The request will become the sync, if one of the filter isn't async enabled. 

The following is the testing on the options handling. The current library handling won't return the 'allow' header.

#### My modified Options handling process

The request from the browser 
![image](https://cloud.githubusercontent.com/assets/1271739/5639130/26905efe-964c-11e4-9905-02f4acae7f94.png)

The break on the option handler
![image](https://cloud.githubusercontent.com/assets/1271739/5639103/c672edc0-964b-11e4-9792-288b93d7d1dd.png)

The stack for the options method
![image](https://cloud.githubusercontent.com/assets/1271739/5639099/a2ac13f8-964b-11e4-83b8-ec85d711c1b5.png)

#### Library Options handling 

The request from the browser
![image](https://cloud.githubusercontent.com/assets/1271739/5639229/6f1d4fc8-964d-11e4-9d57-8bcc8a407d14.png)
![image](https://cloud.githubusercontent.com/assets/1271739/5639234/7ab4139e-964d-11e4-8dfd-3c1c08c6fe9b.png)

The break on the handler
![image](https://cloud.githubusercontent.com/assets/1271739/5639159/87d5313a-964c-11e4-82c8-860951aeeac3.png)

The stack for the options method
![image](https://cloud.githubusercontent.com/assets/1271739/5639162/969168d8-964c-11e4-90ab-0d38558f9e66.png)

**Comment by jfarcand** [comment]
OK so you must make sure, by the Servlet Spec, than all Filters/Servlet mapping the path are async-enabled.
