### ISSUE TITLE
DefaultBroadcaster's messages queue is not processed

### ISSUE THREAD

**Issue by dmitry-treskunov** [Atmosphere/atmosphere#1822]
I have several DefaultBroadcasters. They share executors. 

One of them doesn't dispatch messages - method ```dispatchMessages(Deliver e) ``` is called and put deliver to the queue, but this queue is never flushed. 

Seems that ```getBroadcastHandler()``` task was finished. but ```dispatchThread``` value is 1. As I understand from the source code, it's possible only if queue polling was interrupted, but I don't understand why it can be interrupted. 

Do you have any ideas?

**Comment by jfarcand** [comment]
@dmitry-treskunov Any update on that one? Can you turn the log to trace and gist it? Maybe I can spot something?

**Comment by dmitry-treskunov** [comment]
Actually, it was reproduced a couple of times but I was not able to understand why.  As a result we started using SimpleBroadcaster, seems that it's suitable for us.

Probably, you can close this issue until anybody else will not faced it.

**Comment by jfarcand** [comment]
@dmitry-treskunov Ok Thanks. I would really like to see the log if you find an old one.
