### ISSUE TITLE
node-webkit chrome based browser throws exceptions (internal DoS)

### ISSUE THREAD

**Issue by bertung** [Atmosphere/atmosphere#1825]
node-webkit creates serious problems when using atmosphere.

https://github.com/rogerwang/node-webkit

**Comment by jfarcand** [comment]
@bertung Which line exactly? The code always first looks at `config.isSupportSession()` before calling `getSession`

**Comment by bertung** [comment]
Thanks for the info. Shouldnt getRequest method return null if the resource is dead?

**Comment by bertung** [comment]
Yes checking isCancelled has fixed it.

**Comment by bertung** [comment]
I have created a new issue

https://github.com/Atmosphere/atmosphere/issues/1834
