### ISSUE TITLE
[Tomcat 7.x only] Reloading the servlet context (tomcat 7) does not close all active web sockets

### ISSUE THREAD

**Issue by bertung** [Atmosphere/atmosphere#1827]
Reloading the servlet context does not close all open web sockets on tomcat. This leaves the client side in limbo because onclose is never called. This may also be the case for all other servlet containers.

**Comment by jfarcand** [comment]
@bertung Test case required. Just tested with the browser and [wAsync](https://github.com/Atmosphere/wasync) and it works fine. Which client are you using?

**Comment by jfarcand** [comment]
Also which Tomcat version? Please test with latest 7.0.x or 8.0.x

**Comment by bertung** [comment]
tomcat 7.0.53, Firefox 34. For the test, any servlet context with an active web socket connection will do.

**Comment by bertung** [comment]
@jfarcand it looks like this still regresses with the RC4. Reloading the context does not close the client side sockets. Browsers still think that the sockets are connected to the server.

**Comment by bertung** [comment]
@jfarcand I have also tested this with tomcat 7.0.59, I am not sure if this is related to tomcat 7.0.59, but atmosphere may close connections by itself in a servlet context listener if possible.

**Comment by jfarcand** [comment]
@bertung How do you reproduce?

**Comment by bertung** [comment]
I used the tomcat manager. http://your domain:your port/manager/. There also may be a bug in tomcat manager, not taking care of the open web sockets during reload.
