### ISSUE TITLE
[Firefox] [NettoSphere] ManagedService Disconnect never called

### ISSUE THREAD

**Issue by artvel** [Atmosphere/atmosphere#1830]
Hi
I've used your Snake example to test the Browser Connection Issues.

console output on firefox:
16:18:35.437 [New I/O worker #4] DEBUG o.a.w.DefaultWebSocketProcessor - Delaying closing operation for firefox and resource b38658cb-02fb-4f5e-9b83-d4268cbbd1b1

It looks like an issue with the condition on https://github.com/Atmosphere/atmosphere/blob/master/modules/cpr/src/main/java/org/atmosphere/websocket/DefaultWebSocketProcessor.java line 621

testet with:
atmosphere: 2.2.0 + 2.2.4 same behavior on both
nettosphere: 2.2.0 + 2.2.1 same behavior on both

browser
firefox: 30.0 and 34.0 doesn't work!
chrome: 29 works
opera: 12.16 works

thx for help

**Comment by jfarcand** [comment]
Moved to the proper project. This works fine with J2EE server.
