### ISSUE TITLE
[Tomcat7only] Badly implemented WebSocket client makes Tomcat/Atmosphere to create sessions in an endless loop

### ISSUE THREAD

**Issue by bertung** [Atmosphere/atmosphere#1834]
The following call tree is called constantly until the tomcat(7.x) is terminated.

![endlessloop](https://cloud.githubusercontent.com/assets/9346984/5658892/e81aee20-9711-11e4-855d-fafb5318ae31.gif)

**Comment by bertung** [comment]
The issue is serious. Atmosphere should not create sessions by itself implicitly if session support is activated.

**Comment by jfarcand** [comment]
@bertung Atmosphere must read the original request's session in order to clone its content because the session is getting destroyed after the `handshake` request is executed. Henre there is no way for an application after that stage to have an 'HttpSession'

**Comment by jfarcand** [comment]
Also is the stack above called in a loop, blocking, for all requests (which is expected)? In any case, sound like an issue with Tomcat.

**Comment by bertung** [comment]
In this problem case, atmosphere clearly does not clone the original request instead creating a new HttpSession. Why it is creating a new HttpSession (not a clone) if the resource is canceled. I do not think this is the intended behavior. I can see thousands of http requests from the tomcat manager created for that context.

Yes this happens with all requests. It may be a tomcat issue but we do not have luxury to tell people not to use tomcat 7.x, do we? it will clearly create a DoS internally crashing the server as a result.

**Comment by bertung** [comment]
Simple test case would be to download the problem client namely (node-webkit) and test it with any web socket with sessions enabled.

**Comment by jfarcand** [comment]
@bertung Well, just don't enable session then?

**Comment by jfarcand** [comment]
I don't understand the
```
Why it is creating a new HttpSession (not a clone) if the resource is canceled? I do not think this is the intended behavior.
```
What do you means? I still think Atmosphere has nothing to do with your issue. So just don't enable session and let your app creates it.

**Comment by bertung** [comment]
We need the session information when handling web socket requests as well. This is not really my issue if you test it yourself with node-webkit. Anyways, I believe I will just leave it here.

**Comment by jfarcand** [comment]
@bertung Share you client test then

**Comment by jfarcand** [comment]
@bertung One workaround for you is to use jdk7, and turn [jsr356 on](https://github.com/Atmosphere/atmosphere/wiki/Forcing-JSR-356-for-WebSocket-Application). Another websocket runtime will be used.

**Comment by bertung** [comment]
That didn't make any difference. I do not have a simple test case for you and my hands are full. I will try to put a small test case if I can later. Would it be too hard to put another configuration for just cloning an existing session, but not creating one from scratch?

**Comment by jfarcand** [comment]
Ok added the properly. I seriously doubt it will works as like I said once the handshake is done, Tomcat destroy the session, so event if you try to create it later in your app it won't be the proper one, e.g it will be a fake one. Anyway, try it.

**Comment by bertung** [comment]
thank you very much, It looks like it is what we needed. I will test it over the weekend.

**Comment by jfarcand** [comment]
@bertung You own me a couple of beers :-)

**Comment by bertung** [comment]
Haha :), I will buy you a huge keg of beer :).
