### ISSUE TITLE
[SpringBoot] Try to workaround broken SpringBoot and bad JHipster integration

### ISSUE THREAD

**Issue by jfarcand** [Atmosphere/atmosphere#1836]
SpringBoot is severely broken with 'ServletContextInitiazer' and suprisingly, those guy just don't care to be spec compliant. We need to workaround so Julien Dubois stop saying Atmosphere is broken. Atmosphere won't have any dependency on `Spring` or worse, `Spring websocket`. (over my dead body) 

https://github.com/spring-projects/spring-boot/issues/321
https://github.com/jhipster/generator-jhipster/issues/844#event-212686037

**Comment by jfarcand** [comment]
`javax.websocket.server.ServerContainer` is always null with SpringBoot

**Comment by philwebb** [comment]
As discussed in https://github.com/spring-projects/spring-boot/issues/321 Spring Boot intentionally doesn't load `javax.servlet.ServletContainerInitializer`. I wish that we could support them without causing other issues but unfortunately it was really problematic.

I've added a sample application which includes configuration to trigger the `AtmosphereInitializer`. See https://github.com/spring-projects/spring-boot/blob/master/spring-boot-samples/spring-boot-sample-atmosphere/src/main/java/sample/SampleAtmosphereApplication.java.

That should help users get something working but it's not a great out-of-box experience. One option might be for us to include auto-configuration support for atmosphere but the interplay between `DispatcherServlet` and `AtmosphereServlet` makes this a bit tricky.

I don't think Atmosphere should have any dependency on Spring but perhaps something more could be added to the `atmosphere-spring` extension? I struggled to find the recommended way to configure atmosphere and Spring to play well together.

**Comment by jfarcand** [comment]
@philwebb Thanks for all the help, I've migrated the sample to the atmosphere-samples project. True some of the code can probably be migrated to [atmosphere-spring](http://goo.gl/lTMi1l), [pending community pull request](http://goo.gl/ZKIier)
