### ISSUE TITLE
AtmosphereResourceImpl doesn't override hashcode() which will fail the hash collection 

### ISSUE THREAD

**Issue by dreamershl** [Atmosphere/atmosphere#1841]
Based on JDK comments, this class should override the hashcode() function too. Currently it fails my project hash set when I store this object directly.

**Note that it is generally necessary to override the hashCode method whenever this method is overridden, so as to maintain the general contract for the hashCode method, which states that equal objects must have equal hash codes.**

**Comment by flowersinthesand** [comment]
Fixed by https://github.com/Atmosphere/atmosphere/pull/1743 and https://github.com/Atmosphere/atmosphere/pull/1744

**Comment by dreamershl** [comment]
:+1: 

I should search closed issues first
