### ISSUE TITLE
Multiple handler's interceptors will be combined and intercepts all the services' message

### ISSUE THREAD

**Issue by dreamershl** [Atmosphere/atmosphere#1845]
Personally feel it is not right. But it is intended, just ignore my report.

If configure 2 service with different set of non system default interceptors, for example, the following 2 service's request will be all passed to the "SuspendTrackerInterceptor" although one of them doesn't configure it. 

     @ManagedService(path = "svc1")
     class defaultManagedServiceInterceptorSvc {}

      @ManagedService(path = "svc2", interceptors = {AtmosphereResourceLifecycleInterceptor.class, TrackMessageSizeInterceptor.class})
       class SvcWithoutSuspendTrackerInterceptor {}

The reason is because when request is processed by function "AsynchronousProcessor::action()" The following statement is called 
         
      Action a = invokeInterceptors(config.framework().interceptors(), resource, tracing);

When init the framework, all the handler's interceptors will be eventually added into the framework interceptors list by the function  "AtmosphereFramework::initHandlerInterceptors()".

**Comment by jfarcand** [comment]
Clearly a bug, thanks for reporting it.

**Comment by jfarcand** [comment]
@dreamershl If you can put a sample (or modify an existing one) in Github, that would help a lot.

**Comment by dreamershl** [comment]
my pleasure, give me some time to come out the change. Thanks

**Comment by dreamershl** [comment]
Seems it is more complex than i had thought. I list down 2 possible approach for the modification. Kindly tell me which one you prefer or none of them before I actually modify the codes.

Personally I prefer to the first one, (InvokerOrder will be simplified). The CPU cost on the additional comparison should be quite neglectable.  Another is the approach one better to rely on the Apache common collection library for the FilterIterator<> implementation

About the "SKIP_ATMOSPHEREHANDLER", I only find it is used by the "CorsInterceptor". Maybe it can be considered to removed. You may want to just follow the servlet's filter concept. if any of the interceptor return 'stop', the following will be just ignored. 

**Current Process**
1. check the interceptors execution priority and store them into the system default interceptors list if their priority is not AFTER_DEFAULT
2. Execute the interceptors from 2 queues, system default & handler's own queues

**Proposed Alternatives**
***Approach 1***
use the iterator to iterate the system default & handler's interceptors as a whole. use the Functors to filter different priorities. this approach simplify the priority define, only 2 groups, after or before. the caller function is the one to decide the sequence within the group, (queue sequence, first configure first call)*** 
1. don't add the the handler's queue into the system default queue
2. Rely on the iterator to manipulate the interceptor execution sequence
     (to make the idea clear, rely on the Apache's common library class Filter
     
        //high priority
        Iterator<AtmosphereInterceptor> handlersInterceptorIterator = new IteratorChain<AtmosphereResource>(handlerWrapper.interceptors().iterator(),config.framework().interceptors().iterator());

        FilterIterator<AtmosphereInterceptor> iterator = new FilterIterator<>(handlersInterceptorIterator,c->{
            boolean accept = false;

            if(c instanceof InvokationOrder)
            {
                accept = ((InvokationOrder) c).priority() != InvokationOrder.PRIORITY.AFTER_DEFAULT;
            }
            return accept;
        });
        invokeInterceptors(iterator,r,tracing);

        //low priority
        iterator = new FilterIterator<>(handlersInterceptorIterator,c->{
            boolean accept = true;

            if(c instanceof InvokationOrder)
            {
                accept = ((InvokationOrder) c).priority() == InvokationOrder.PRIORITY.AFTER_DEFAULT;
            }
            return accept;
        });
        invokeInterceptors(iterator,r,tracing);

***Approach 2***
Still follow the current idea, the caller even can decide the individual interceptors sequence through the InvokationOrder constant.

1. instead of merging the handler's interceptors into the system default interceptors queue, merging them into the handler's interceptor list
2. extend the Comparable<InvokationOrder>, Comparator<InvokationOrder> interface, so the list can be easily sorted through the Collections.sort(List<InvokationOrder>).

**Comment by jfarcand** [comment]
@dreamershl Great work. I think I prefer approach 2 because I'm not sure I want to have a dependency on Apache Common. So either we fork the class (could be quite complex), or we go with appoach 2. What do you think?

**Comment by elakito** [comment]
While looking for any issues marked tagged with 2.2.5, I came across this issue.

I just have a comment.

If we want to have a controlled ordering of interceptors, which is flexible enough to allow independently developed interceptors implementing various features to be added in the interceptor chain, one approach would be to have some form of beforeX and afterX logic attached to each interceptor so that each interceptor knows where to be placed relative to the other interceptors. This is how various CXF's interceptors are inserted into their corresponding interceptor chain to build a complex sequence of operations.
https://github.com/apache/cxf/blob/master/core/src/main/java/org/apache/cxf/phase/AbstractPhaseInterceptor.java#L123-L161
This is certainly not for 2.2.5 but we can think about it for the future, no?
regards, aki

**Comment by jfarcand** [comment]
@elakito That could be a clean implementation. I agree we should explore it for `2.3.0`. For 2.2.5 we need to be really carefull...I'm not event sure we should fix it for a dot release, but I will investigate soon.

**Comment by dreamershl** [comment]
Hi, I have come out the change in AsynchronousProcessor &  AtmosphereFramework. Please have a look to see whether need future adjust the change.  

My changes are here

https://github.com/dreamershl/atmosphere/commit/4fe1684e3f82b043596afc2f76e04b0eee39e886

**Comment by jfarcand** [comment]
@dreamershl Apology for the delay. Can you do a pull request? I will test your patch but that looks promising. GREAT WORK!

**Comment by dreamershl** [comment]
It is done. please check

**Comment by jfarcand** [comment]
@dreamershl There a lot of unit test failure and the ordering seems to be reverse (e.g. the CORSInterceptor ends up at the very end instead of the very beginning). Are the unit tests passing for you?

**Comment by dreamershl** [comment]
Sry. Haven't really tested them. Now I am out of office. Will get back to
 u once I completely pass all the unit tests.  Thx

On Wednesday, February 25, 2015, Jeanfrancois Arcand <
notifications@github.com> wrote:

> @dreamershl <https://github.com/dreamershl> There a lot of unit test
> failure and the ordering seems to be reverse (e.g. the CORSInterceptor ends
> up at the very end instead of the very beginning). Are the unit tests
> passing for you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Atmosphere/atmosphere/issues/1845#issuecomment-75886241>
> .
>


-- 
Sent from Gmail Mobile

**Comment by jfarcand** [comment]
Regression #1890
