### ISSUE TITLE
AtmosphereRequest is not configured properly when using Weblogic 12c with websockets

### ISSUE THREAD

**Issue by tjkaal** [Atmosphere/atmosphere#1854]
When using WebLogic 12.1.3 with websockets it seems that sessions attributes and GET parameters are not set properly in `WeblogicWebSocketHandler.onOpen(WebSocketConnection)`.

Cause for this seems to be that while `GlassFishWebSocketHandler.onConnect(WebSocket)` makes a call to `AtmosphereFramework.configureRequestResponse(AtmosphereRequest, AtmosphereResponse)`, with `WeblogicWebSocketHandler` nothing similar is done.

**Comment by tjkaal** [comment]
Could actually be related to [this issue](https://github.com/Atmosphere/atmosphere/issues/1834), will investigate further.

**Comment by jfarcand** [comment]
@tjkaal It may be a bug in WebLogic actually because 
```java
AtmosphereRequest ar = AtmosphereRequest.cloneRequest(request.get(), true, false, true, config.getInitParameter(PROPERTY_SESSION_CREATE, true));
```
is using the `WSHandshakeRequest` which may not have the information (that's the only possible scenario). If you debug the `cloneRequest`, are you seeing the parameters? Thanks for the help.

**Comment by tjkaal** [comment]
So far I've found out that while query string is set to the request, it is never processed. This can at least be fixed by making an ugly call:

	ar.queryString(ar.getQueryString());

Still, the session seems to be lost. Is there a problem if `copySession` is set to `true` when calling `AtmosphereRequest.cloneRequest()`? If that is done the server seems to be able to access the session data properly.

**Comment by jfarcand** [comment]
@tjkaal Please port to `Vaadin` issue 1856 to enable JSR356 support in WebLogic 12c as this is a much better implementation than their broken native one.

**Comment by tjkaal** [comment]
Thanks, will take a look.
