### ISSUE TITLE
ManagedServiceProcessor always load three default interceptors 

### ISSUE THREAD

**Issue by allenxiang** [Atmosphere/atmosphere#1857]
ManagedServiceProcessor always load three default interceptors.

Line 85:            AnnotationUtil.defaultInterceptors(framework, l);
Line 86:            AnnotationUtil.interceptors(framework, a.interceptors(), l);

I have tried use ApplicationConfig.DISABLE_ATMOSPHEREINTERCEPTORS to disable TrackMessageSizeInterceptor but had no effect.

**Comment by jfarcand** [comment]
@allenxiang Don't use the `ManagedServiceProcessor` in that case as it won't work as expected.

**Comment by allenxiang** [comment]
But I still want to use @ManagedService, how do I override ManagedServiceProcessor?

**Comment by allenxiang** [comment]
@jfarcand  Please allow me to explain the issue. We are using ManagedService for binary messages. Since TrackMessageSizeInterceptor is always activated but not applicable to binary message, it will throw a warning every time a heartbeat or a user message is sent. In production these warning messages will soon fill up the log file. Please reconsider this issue if it make sense. Thanks.

**Comment by jfarcand** [comment]
@aleksandarn fair enough. Contribution welcomed :-) Should be simple to read that value when the annotation is scanned and don't add those. Pull request?

**Comment by allenxiang** [comment]
@jfarcand pull request created. Thanks.

**Comment by allenxiang** [comment]
This issue has been fixed by commit 1ffc3a5 and 1c2315e. We can close this issue now.
