### ISSUE TITLE
Is synchronous XHR really needed by Atmosphere?

### ISSUE THREAD

**Issue by ookke** [Atmosphere/atmosphere#1863]
Synchronous XHR is in the process of being deprecated (https://xhr.spec.whatwg.org/#sync-warning), and for good reasons.

When testing a solution for https://github.com/Atmosphere/atmosphere/issues/1860 I encountered an issue where Atmosphere tries to reconnect a Websocket just as the network goes down and the synchronous XHR request gets stuck pending blocking the UI thread for 15 minutes before it times out. This is a problem because our offline-aware app has a connection indicator that doesn't get rendered because the UI thread is blocked waiting for the XHR to complete.

I tried using connectTimeout earlier, but that seemed to also affect valid "waiting" long polling connections which doesn't seem logical.

**Comment by jfarcand** [comment]
This is required because if not some browser won't send the request and the disconnect won't be detected.

**Comment by ookke** [comment]
Ok, fair enough. So my only choice is using connectTimeout then I guess?

**Comment by jfarcand** [comment]
You can make it 'async` as well and see how the application behave. I'm not sure the timeout will works...contribution welcomed :-) 

<spam>BTW if you are planning to go in production, take a look at http://async-io.org/AtmospherePro.html</spam>. Specially Atmosphere Postman that helps with Firefox/websocket leaks when the user reload the page.

**Comment by ookke** [comment]
You were right about the connectTimeout not always working, made a PR for that.
