### ISSUE TITLE
[ManagedAtmosphereHandler] Second consequent message not delivered 

### ISSUE THREAD

**Issue by meszarv** [Atmosphere/atmosphere#1887]
Hi,
I have a managed service with one @Message annotated method:
```    
@Message
public Serializable onMessage(AtmosphereResource r, Object message) {
```
Just switched to 2.3.0.RC4 version and found that I only receive every second message sent from javascript client.
This problem is comming from [ManagedAtmosphereHandler.message():369](https://github.com/Atmosphere/atmosphere/blob/master/modules/cpr/src/main/java/org/atmosphere/config/managed/ManagedAtmosphereHandler.java#L369) which sets this "invokedMethod" attribute and then every second message is got swallowed by this branch of the method  [ManagedAtmosphereHandler.message():339] (https://github.com/Atmosphere/atmosphere/blob/master/modules/cpr/src/main/java/org/atmosphere/config/managed/ManagedAtmosphereHandler.java#L339). The attribute is [removed](https://github.com/Atmosphere/atmosphere/blob/master/modules/cpr/src/main/java/org/atmosphere/config/managed/ManagedAtmosphereHandler.java#L334) and the next message is processed correctly again...

According to history new logic in this file was to fix #1620 : calling broadcast inside @Message method. 

Thanks

**Comment by jfarcand** [comment]
@meszarv Which transport are you using?

**Comment by jfarcand** [comment]
@meszarv Please try [2.3.0-SNAPSHOT](https://github.com/Atmosphere/atmosphere/wiki/Downloading-Atmosphere's-SNAPSHOT) and confirm the fix works for you.

**Comment by meszarv** [comment]
Thanks Jeanfrancois! 
fix works.

**Comment by meszarv** [comment]
Don't know if this is related (it seems related to #1620) but now all messages are swallowed by atmosphere if I broadcast something in the @Ready annotated method. 
If I remove the broadcast everything works fine. 
here is sample project (jetty:run):
https://drive.google.com/file/d/0B8N1HB3oyzQ_Y1pWMzVBYXpoZ2c/view?usp=sharing

**Comment by jfarcand** [comment]
@meszarv What it working before? If yes, file another issue :-) Thanks for the help!

**Comment by reda-alaoui** [comment]
Hi Jean-François,

I have the following method in my managed service:

```
        @Message
	public void message(AtmosphereResource resource, InputStream is) {
             ...
        }
```
I am using 2.3.4-SNAPSHOT

Randomly, after refreshing the browser page, this method receives no message at all. I have to reload  the browser page, sometime several times, to make things work again.
After debugging, issue arise when the first received message is trapped by ManagedAtmosphereHandler#346. Of course there is no encoder so the message is just lost.

Are you sure that your correction is supposed to work even with a method expecting an InputStream?

**Comment by reda-alaoui** [comment]
Hi Jean-François,

There are still non-received messages with JSR356.

**Comment by jfarcand** [comment]
@reda-alaoui I need a unit test in order to help :-)
