### ISSUE TITLE
[ManagedAtmosphereHandler] Messages not delivered after broadcast from @Ready method

### ISSUE THREAD

**Issue by meszarv** [Atmosphere/atmosphere#1890]
Issue after fix of #1887. All messages are swallowed by atmosphere if I broadcast something in the @Ready annotated method. 
If I remove the broadcast everything works fine. 
here is sample project (jetty:run):
https://drive.google.com/file/d/0B8N1HB3oyzQ_Y1pWMzVBYXpoZ2c/view?usp=sharing

**Comment by jfarcand** [comment]
Actually #1845 just exposed more the issue, which is the fact the test is duplicating `AtmosphereInterceptor` which are already added by the framework
```java
@ManagedService(path = "/async/test", interceptors = { AtmosphereResourceLifecycleInterceptor.class, ManagedServiceInterceptor.class, TrackMessageSizeInterceptor.class, HeartbeatInterceptor.class, SuspendTrackerInterceptor.class })

```

**Comment by jfarcand** [comment]
This is a regression from #1709
