### ISSUE TITLE
NullPointerException in MeteorServlet

### ISSUE THREAD

**Issue by andrew-ix** [Atmosphere/atmosphere#1893]
I got
`java.lang.NullPointerException
	at org.atmosphere.cpr.MeteorServlet.init(MeteorServlet.java:87)`

`if (!framework().isInit) {
            super.init(sc);

            if (delegate == null) {
                loadDelegateViaConfig(sc);
            } else {
                ReflectorServletProcessor r = new ReflectorServletProcessor(delegate);
                for (Filter f : filters) {
                    r.addFilter(f);
                }
                framework().getBroadcasterFactory().remove(delegateMapping);
                framework().addAtmosphereHandler(delegateMapping, r).initAtmosphereHandler(sc);
            }
        }

In first line method framework() called, but framework is not initialized, so it returns `null`, initialization is done inside `super.init(sc);`

**Comment by jfarcand** [comment]
@andrew-ix Which version are you using? Are you able to reproduc with one of the sample (https://github.com/Atmosphere/atmosphere-samples/tree/master/samples/meteor-chat)

**Comment by jfarcand** [comment]
Please re-open once you have a valid test case. All samples works fine.
