### ISSUE TITLE
getInitParameter also from ServetContext?

### ISSUE THREAD

**Issue by bertung** [Atmosphere/atmosphere#1897]
It looks like getInitParameter uses ServletConfig as oppose to ServletContext. ServletConfig as you know is servlet specific. There must be a way to set configuration parameters application context wide.

**Comment by jfarcand** [comment]
@bertung I'm not sure I agree here. AtmosphereServlet is per Config. If you need ServletContext, then just do `getAtmosphereConfig().getServletContext()`

**Comment by bertung** [comment]
As an addition to per servlet config, there may be an option to set it to web application context. If the config option is not in the servlet configuration, servlet context may also be check if it is defined for all servlets or not.

**Comment by jfarcand** [comment]
@bertung Agree.  Pull request welcomed.

**Comment by bertung** [comment]
https://github.com/Atmosphere/atmosphere/pull/1898
