### ISSUE TITLE
Long-Polling interrupted on initial connect

### ISSUE THREAD

**Issue by seamusmac** [Atmosphere/atmosphere#1906]
Copied from https://groups.google.com/forum/#!topic/atmosphere-framework/R--IyIDnyG4

Testing the 2.3.0-SNAPSHOT, and I am seeing one issue so far.
take the atmosphere-chat example. make the following 2 modifications:
1. change transport to 'long-polling'
2. uncomment the logger in logback.xml <logger name="org.atmosphere" level="TRACE"/>

when trying to connect the first time, I am seeing the following in the logs:

12:16:20.116 TRACE [http-bio-9090-exec-1] o.a.c.AsynchronousProcessor [AsynchronousProcessor.java:340] Interceptor Atmosphere JavaScript Protocol interrupted the dispatch for 4ab46ea9-93ee-4c5e-a946-0300d9e81a3a with Action{timeout=-1, type=CANCELLED}
12:16:20.117 TRACE [http-bio-9090-exec-1] o.a.c.AsyncSupportListenerAdapter [AsyncSupportListenerAdapter.java:47] Closing resource AtmosphereResource{
	 uuid=4ab46ea9-93ee-4c5e-a946-0300d9e81a3a,
	 transport=LONG_POLLING,
	 isInScope=true,
	 isResumed=false,
	 isCancelled=false,
	 isSuspended=false,
	 broadcasters=/chat,
	 isClosedByClient=false,
	 isClosedByApplication=false,
	 action=Action{timeout=-1, type=CREATED}} for request AtmosphereRequest{ method=GET contextPath=/atmosphere-chat servletPath=/chat pathInfo=null requestURI=/atmosphere-chat/chat requestURL=http://localhost:9090/atmosphere-chat/chat AtmosphereResource UUID=4ab46ea9-93ee-4c5e-a946-0300d9e81a3a destroyable=true}

**Comment by jfarcand** [comment]
@seamusmac This error may be caused when you load `atmosphere.js`, shutdown the server and then reload the page. In that case the close message will be send and may cause this log. Is that what you are doing or you are loading a resf page? Thanks!!!

**Comment by seamusmac** [comment]
@jfarcand 
I just ran a quick test. I opened my eclipse, started the Tomcat server. 
Then I opened a new firefox instance, put in the atmosphere-chat url:
The full log is at: 
https://gist.githubusercontent.com/seamusmac/289f6890393fb97cdb8f/raw/8f3a9fc5f1dbb89c28ce9e48399c4b7acdcbc21d/gistfile1.txt

I am not sure, but I don't think one of the first things I should see is:
"Interceptor Atmosphere JavaScript Protocol interrupted the dispatch.......
Closing resource AtmosphereResource....."

**Comment by jfarcand** [comment]
@seamusmac Just waked up. In AsynchronousProcessor
```java
            if (a.type() != Action.TYPE.CONTINUE) {
                logger.trace("Interceptor {} interrupted the dispatch for {} with " + a, arc, r.uuid());
                return a;
            }
```
The message is expected, it just means an interceptor stopped the processing.

**Comment by seamusmac** [comment]
@jfarcand That sounds good. I just discovered a bug in the way I was registering one of my broadcasters, and I thought it was related. So I was wrong.
 Everything looking good now. 
Looking forward to the next Release Candidate. :+1:

**Comment by jfarcand** [comment]
Thanks a lot @seamusmac for your help. This is extremely appreciated!
