### ISSUE TITLE
Trailing slashes in JSR 356 path not handled correctly for Jetty 9.2

### ISSUE THREAD

**Issue by Artur-** [Atmosphere/atmosphere#1910]
If the path used for JSR 356 websocket requests end in a slash, the websocket upgrade request will fail and return 200

Reproducible in the chat sample by changing the url to
var request = { url: document.location.toString() + 'chat/',

and forcing the use of JSR 356 through
<init-param>
    <param-name>org.atmosphere.cpr.asyncSupport</param-name>
    <param-value>org.atmosphere.container.JSR356AsyncSupport</param-value>
</init-param>

**Comment by Artur-** [comment]
Some more info at http://dev.vaadin.com/ticket/14381

**Comment by jfarcand** [comment]
@Artur- Getting the same behavior with Tomcat 8.0.21. Which Tomcat version have you tested?

**Comment by Artur-** [comment]
Indeed it happens also on Tomcat, I must have not forced JSR 356 on Tomcat 8 when testing earlier. Does the spec say anything about trailing slashes?

**Comment by jfarcand** [comment]
Tomcat 8 only supports jsr 356. I don't recall about the spec...will need to look at it.

**Comment by jdahlstrom** [comment]
JSR 356 section 3.1.1 seems to indicate that if there's an endpoint path like /{path} then only eg. /PUSH will match it, not /PUSH/.

**Comment by jfarcand** [comment]
Closing as not an issue.
