### ISSUE TITLE
Support for JDK 8 only

### ISSUE THREAD

**Issue by jfarcand** [Atmosphere/atmosphere#1912]

**Comment by jfarcand** [comment]
https://github.com/Atmosphere/atmosphere/blob/e6303826ce704887b8a8ebf99747e2d2e7623932/pom.xml

**Comment by gdrouet** [comment]
Does this mean that we can introduce some code refactoring or should we wait as it may complexify some backport to 2.x?

**Comment by jfarcand** [comment]
Yes you can introcude code refactoring :-) We are free to do whatever we want on `master` from now on!
