### ISSUE TITLE
Remove Servlet API dependency

### ISSUE THREAD

**Issue by jfarcand** [Atmosphere/atmosphere#1918]
Atmosphere 3.0 must not have any hard dependency on Servlet. Write a Reflection or JDK 8 Proxy Layer instead.

**Comment by gdrouet** [comment]
What is your motivation? Why having a dependency on servlet is an issue?

**Comment by jfarcand** [comment]
For Netty, Play and Vert.x is bad to depend on the servlet API to be on the classpath to work.

**Comment by jfarcand** [comment]
Next official version https://github.com/Atmosphere/Atmosph4rX
