### ISSUE TITLE
Drop support for atmosphere-jersey API (Jersey 1.x)

### ISSUE THREAD

**Issue by jfarcand** [Atmosphere/atmosphere#1924]

**Comment by allenxiang** [comment]
atmosphere-guice still depends on jersey 1.x, is there any plan to update that module as well?

**Comment by manikantag** [comment]
Is there any solid reason to stop supporting Jersey 1.x? As most of the projects still using Jersey 1.x due to Jersey backward compatibility & performance issues.

**Comment by jfarcand** [comment]
@manikantag Good point. The only reason is maintability right now.

**Comment by allenxiang** [comment]
@jfarcand @manikantag I guess most of the projects still use java <=7 while atmosphere 3.x is going to drop support for java <=7.

**Comment by jfarcand** [comment]
@allenxiang Nothing is fully decided to be honest...3.0.0-SNAPSHOT right now still uses 1.7 and we may decide, as a community, to keep 1.7 :-)

**Comment by DigitalSmile** [comment]
Why to stop supporting Jersey 1? There are benefits of using 1.x version rather than 2.x, like guice integration and performance. It would be a pitty, If the support will be dropped...

**Comment by jfarcand** [comment]
@DigitalSmile There is no plan right now for Atmosphere 3, hence Jersey support is here to stay :-)

**Comment by manikantag** [comment]
Glad to hear about Jersey 1.x support... at least for now...

**Comment by jfarcand** [comment]
Next official version https://github.com/Atmosphere/Atmosph4rX
