### ISSUE TITLE
Drop support for AtmosphereHandler/AtmosphereResourceEvent 

### ISSUE THREAD

**Issue by jfarcand** [Atmosphere/atmosphere#1926]

**Comment by silvpol** [comment]
We're using AtmosphereHandler/AtmosphereResourceEvent as this allows for clean integration with Dropwizard. What is the rationale for removing it and what would be a replacement?

**Comment by jfarcand** [comment]
@silvpol We haven't yet discussed the replacement, but it would be some kind of annotated POJO. Note that the solution will go along that line.

**Comment by jfarcand** [comment]
Next official version https://github.com/Atmosphere/Atmosph4rX
