### ISSUE TITLE
Not able to receive messages on client side when the war is bundeled inside ear

### ISSUE THREAD

**Issue by Sheshagiri** [Atmosphere/atmosphere#1928]
Hi 

I built a small application based on chat application using atmosphere and jquery. Everything work fine i deploy that project as a war in my jboss-6.1.0.Final. But when i bundle the same war in my ear and try to deply that ear, i dont get and messages from the server on client. I can confirm that i'm getting messages on when i deploy as a WAR.

Please let me know if anybody has seen this kind of behaviour earlier. It will be very useful. Thank You in advance.

Cheers

**Comment by gdrouet** [comment]
Please can you share the sample you deployed as an EAR so we can reproduce the issue?

**Comment by jfarcand** [comment]
Please use the mailing list for question. That's clearly not a bug with Atmosphere

https://groups.google.com/group/atmosphere-framework?pli=1

**Comment by gdrouet** [comment]
@jfarcand I'm probably wrong but I'm always afraid that annotation detector don't manage a dirty behavior in jboss ;-)

**Comment by jfarcand** [comment]
@gdrouet You are right, but first let's have the discussion on the mailing list with proper logs etc. :-)

**Comment by Sheshagiri** [comment]
After some head banging with the jboss logs i found that bundling jetty-util-6.1.4 in the ear was breaking the flow. Haven't got a chance to dig deep into the issue. For now i'm able to bundle my war inside the ear. We can take it in  mailing list if you guys would like to know more details of this.

**Comment by jfarcand** [comment]
@Sheshagiri The Atmosphere's log is probably showing that Atmosphere detected Jetty instead of JBoss because of that jar file. You can paste the log here. Any reason to bundle Jetty inside the war?

**Comment by Sheshagiri** [comment]
@jfarcand jetty jar came in as a dependency when we added DWR. I'll pass on logs.
