### ISSUE TITLE
ConcurrrentHashMap Leaking.

### ISSUE THREAD

**Issue by farchanjo** [Atmosphere/atmosphere#1929]
Hi everyone,
I'm using atmosphere with spring boot, then my app is leaking my memory. 

Take a look my heap dump:
![screenshot 2015-03-30 11 32 00](https://cloud.githubusercontent.com/assets/4031556/6898417/85f92c4e-d6d0-11e4-8338-9be80ff65691.png)

I have too many ConcurrentHashMap instances. Can give a tip why is it happens? Looking inside the object, I have too many key as SpringAnnotationContext and WeakReference, but the GC isn't release the memory. I have another thread which count my AtmosphereResource and then my resources just increase, increase.. I have tried EMPTY_DESTROY but is not working.

**Comment by jfarcand** [comment]
Please use the https://groups.google.com/group/atmosphere-framework?pli=1 for question.
