### ISSUE TITLE
Possible Thread Race with AsyncToken in DefaultBroadcaster

### ISSUE THREAD

**Issue by jfarcand** [Atmosphere/atmosphere#1932]
In DefaultBroadcaster, setAttribute is called with the same key:
```java
request.setAttribute(ASYNC_TOKEN, token);
```
This can cause side effect if more than one Broadcaster is used with the same `AtmosphereResource`

**Comment by slovdahl** [comment]
This issue is marked as fixed in 2.2.7, but I can't find any commit that fixes it in the atmosphere-2.2.x branch.

**Comment by jfarcand** [comment]
@slovdahl  If you have the cycle, just cherry-pick it. Thanks!

**Comment by slovdahl** [comment]
Sure, will do.

**Comment by slovdahl** [comment]
Should we let the ```public void cacheLostMessage(AtmosphereResource r)``` method be available in 2.2.x? It's a bit dangerous to remove a public method.

**Comment by jfarcand** [comment]
+1

**Comment by slovdahl** [comment]
Hmm, can't find that wiki page or mail where you said which :symbol: to use for commits :camel:

**Comment by jfarcand** [comment]
https://github.com/Atmosphere/atmosphere/wiki/For-Committers
