### ISSUE TITLE
Glassfish 4 websocket support is broken if using multiple endpoints

### ISSUE THREAD

**Issue by Artur-** [Atmosphere/atmosphere#1933]
If you have multiple endpoints inside the same web app (war), the requests might go to the wrong endpoint - depending on in which order they were initialized.

The problem seems to be in Grizzly2WebSocketApplication.isApplicationRequest, which only compares the context path.

"Jeanfrancois wrote: Most probably I need to port this https://github.com/Atmosphere/atmosphere/blob/master/modules/cpr/src/main/java/org/atmosphere/container/GlassFishWebSocketHandler.java#L58

This does not seem to be a problem with JSR-356

**Comment by Artur-** [comment]
This is still broken when you have two servlets, e.g.

/first/*
and
/second/*

because `IOUtils.guestServletPath(config)` in GlassFishServ30WebSocketSupport constructor

    WebSocketEngine.getEngine().register(config.getServletContext().getContextPath(), IOUtils.guestServletPath(config), application);

will convert the servlet paths to the form `/first` instead of `/first/*` and thus if you use `/first/push` as the websocket path, the request will never be upgraded as it does not match `/first`

**Comment by jfarcand** [comment]
OK let me investigate again.
