### ISSUE TITLE
OnDisconnectInterceptor transport check failure when using JS client.

### ISSUE THREAD

**Issue by petejohanson** [Atmosphere/atmosphere#1934]
Currently, when enableProtocol is set, when the atmosphere-javascript client unsubscribes, it issues a request that contains a *header* of X-Atmosphere-Transport=polling and a *query* parameter of X-Atmosphere-Transport=close. However, the OnDisconnectInterceptor `inspect` uses Utils.closeMessage with [this check](https://github.com/Atmosphere/atmosphere/blob/master/modules/cpr/src/main/java/org/atmosphere/util/Utils.java#L180):

    String s = request.getHeader(HeaderConfig.X_ATMOSPHERE_TRANSPORT);
    return s != null && s.equalsIgnoreCase(HeaderConfig.DISCONNECT_TRANSPORT_MESSAGE);

Which obviously is using the *header* to decide if this is a disconnect request.

Who is right? I'm happy to submit a pull request for either atmosphere-javascript or atmosphere core depending on the answer. It *seems* that the atmosphere-javascript code should send "close" for both the header and query parameter, but I wanted some feedback before submitting a PR.

Thanks.

**Comment by jfarcand** [comment]
@petejohanson Look inside the `AtmosphereFramework`, the query string, which is sent by default, is translated into headers. Thanks.
