### ISSUE TITLE
Multiple threads call AtmosphereResource.write(), websocket stops working

### ISSUE THREAD

**Issue by agherardi** [Atmosphere/atmosphere#1937]
Hi,
I'm using Atmosphere 2.2.0. In my application, multiple threads can concurrently call AtmosphereResource.write() on the same AtmosphereResoiurce object. I noticed that under load, after a while the websocket stops working - no data is being received by the websocket client.

I'm not sure whether this is an issue or whether AtmosphereResource.write() is not multi-thread safe by design. And if it's not multi-thread safe by design, is the recommended workaround to serialize calls to AtmosphereResource.write() in the application?

Thank you in advance,
Alessandro

**Comment by jfarcand** [comment]
You must synchronize the write operation like `Broadcaster` are normally doing. So just do:
```java
synchronized(atmosphereResource){
  atmosphereResource.write(...);   
}
```

**Comment by agherardi** [comment]
What about the HeartbeatInterceptor? Does it synchronize writes?

**Comment by jfarcand** [comment]
@agherardi Yes https://github.com/Atmosphere/atmosphere/blob/master/modules/cpr/src/main/java/org/atmosphere/interceptor/HeartbeatInterceptor.java#L355-L373

**Comment by agherardi** [comment]
Ouch - we're running version 2.2.0-RC1, which doesn't have the synchronize.

Do you recommend upgrading to 2.2.7 or to 2.3.X?

**Comment by jfarcand** [comment]
2.3.x but it will needs some rework...2.2.7 should be easier as well.
