### ISSUE TITLE
Make JSR-356 the preferred websocket implementation

### ISSUE THREAD

**Issue by Artur-** [Atmosphere/atmosphere#1940]
Native websocket implementations are still preferred over JSR 356 in DefaultAsyncSupportResolver (even though useNativeIfPossible is false) but many of the native websocket implementations have issues. WebLogic native implementation is deprecated and requires a hard coded "/ws/*" path, Glassfish 4 native websockets do not currently work with multiple servlets because of mapping problems (https://github.com/Atmosphere/atmosphere/issues/1933).

Is JSR 356 implementation in servers mature enough so the standard could be preferred whenever available?

**Comment by jfarcand** [comment]
I'm still uncomfortable to turn it on, specially for Tomcat 7 and Jetty in general. Will do in 2.3.1 or 2.4.0. Thanks!
