### ISSUE TITLE
Log the exception if DefaultAsyncSupport.newCometSupport fails

### ISSUE THREAD

**Issue by Artur-** [Atmosphere/atmosphere#1942]
[ERROR   ] Failed to create comet support class: class org.atmosphere.container.JSR356AsyncSupport, error: null
    [ERROR   ] Switching to BlockingIO

is not very helpful

**Comment by jfarcand** [comment]
I agree, but the code is just:
```java
        } catch (final Exception e) {
            logger.error("Failed to create comet support class: {}, error: {}", targetClass, e);
            logger.error("Switching to BlockingIO");

            return new BlockingIOCometSupport(config);
        }
```
I doubt e can be null, so something with the logger you are using is returning `null`, no?
