### ISSUE TITLE
AtmosphereResource.write incorrectly works in IE7 and IE8

### ISSUE THREAD

**Issue by 40rn05lyv** [Atmosphere/atmosphere#1950]
I downloaded atmosphere-samples-project-2.2.6, imported "atmosphere-chat" sample and changed only 1 place in code: replaced

```
@org.atmosphere.config.service.Message(encoders = {JacksonEncoder.class}, decoders = {JacksonDecoder.class})
public Message onMessage(Message message) throws IOException {
    logger.info("{} just send {}", message.getAuthor(), message.getMessage());
    return message;
}
```

with 

```
@org.atmosphere.config.service.Message(decoders = {JacksonDecoder.class})
public void onMessage2(AtmosphereResource r, Message message) throws IOException {
    logger.info("{} just send {}", message.getAuthor(), message.getMessage());
    r.write(new JacksonEncoder().encode(message));
}
```

In IE8 onMessage is not invoked in javascript, so input field is disabled.
In IE7 browser fallbacks to "jsonp" (instead of "streaming") and send (or receive) infinite number of the same messages from server.

Server log after sending 1 message from IE7:

```
 18:07:24.840 INFO [qtp289301850-98] o.a.s.c.Chat [Chat.java:93] d just send d
 18:07:24.904 INFO [qtp289301850-91] o.a.s.c.Chat [Chat.java:93] d just send d
 18:07:24.966 INFO [qtp289301850-82] o.a.s.c.Chat [Chat.java:93] d just send d
 18:07:25.029 INFO [qtp289301850-98] o.a.s.c.Chat [Chat.java:93] d just send d
 18:07:25.092 INFO [qtp289301850-91] o.a.s.c.Chat [Chat.java:93] d just send d
 18:07:25.153 INFO [qtp289301850-82] o.a.s.c.Chat [Chat.java:93] d just send d
 18:07:25.215 INFO [qtp289301850-98] o.a.s.c.Chat [Chat.java:93] d just send d
 18:07:25.278 INFO [qtp289301850-91] o.a.s.c.Chat [Chat.java:93] d just send d
 18:07:25.343 INFO [qtp289301850-82] o.a.s.c.Chat [Chat.java:93] d just send d
 18:07:25.405 INFO [qtp289301850-98] o.a.s.c.Chat [Chat.java:93] d just send d
 18:07:25.465 INFO [qtp289301850-91] o.a.s.c.Chat [Chat.java:93] d just send d
```

Works OK in all other browsers (FF, Chrome, IE10).
Works OK without modifying code.

I uploaded chat sample with my changes to this git repo:  https://github.com/40rn05lyv/atmosphere-chat-bug1

**Comment by 40rn05lyv** [comment]
Also, @DeliverTo(DeliverTo.DELIVER_TO.RESOURCE) does not work at all (tried with clean "atmosphere-chat" application, just added this annotation before onMessage method).

I debugged code to the IOUtils#deliver method and there nothing is executed, since "Object o" input is never String or byte[].

**Comment by jfarcand** [comment]
@40rn05lyv File another issue with a test case. Also please push your code on Github for the current issue. Thanks

**Comment by 40rn05lyv** [comment]
Created another issue. For current issue I already uploaded code: https://github.com/40rn05lyv/atmosphere-chat-bug1

**Comment by jfarcand** [comment]
Won't fix
