### ISSUE TITLE
Can not create a Broadcaster, because an implementation is required.

### ISSUE THREAD

**Issue by DonaldoDuckDe** [Atmosphere/atmosphere#1960]
I use in Version 2.2.6 the following code:
broadcasterFactory.lookup("tickets", true).broadcast("new Ticket xy is available");
to create an broadcaster.

With the new Version 2.3.0
I get an error, that an implementation is required. 

Is this method depracted? How shoud use this method now?

Greetings,
Christian

**Comment by jfarcand** [comment]
Please use the mailing list for question. Also please paste the error :-)
