### ISSUE TITLE
Concurrency issue in WebSocket's write operation

### ISSUE THREAD

**Issue by elakito** [Atmosphere/atmosphere#1961]
If more than one threads are writing responses, the response messages may get concatenated or corrupted. Concretely, WebSocket's transform method uses a shared buffer and this may lead to this data corruption issue when responses are concurrently sent back.

Originally, discussed in the swaggersocket's issue list:
https://github.com/swagger-api/swagger-socket/issues/43

**Comment by elakito** [comment]
@jfarcand 

Basically, there are three approaches
1. synchronize the buffer in WebSocket's transform or write ops
2. allocate a buffer every time the transform method is called and release it after the call
3. allocate a buffer at the first transform call in its thread-local and keep it while the same thread is invoking multiple write operations while processing a single service invocation and release it when this thread invokes the close method.

I tend to think we can first go for option 2, which is simple and guaranteed to not cause any memory leak. Option 3 may have some advantage over option 2 in those cases where a single service call generating a large number of multiple writes.

**Comment by jfarcand** [comment]
@elakito Ok go for 2. I think this could be improved lated by having a pool of buffer instead of creating one.

**Comment by elakito** [comment]
thanks.
done

**Comment by jfarcand** [comment]
@elakito Great work!
