### ISSUE TITLE
Return wrong  PathInfo/ServletPath from AtmosphereRequest while using Tomcat 8(JSR356AsyncSupport)

### ISSUE THREAD

**Issue by ansoncat** [Atmosphere/atmosphere#1966]
When upgrading our Spring MVC (3.0.7) based application from Tomcat 7.0.35/Atmosphere 2.0 to Tomcat 8.0.21/Atmosphere 2.3.0, an "No mapping found for HTTP request" error occurred. We found that the AtmosphereRequest instance returns wrong PathInfo/ServletPath in Tomcat 8(JSR356AsyncSupport).
For example: ws://localhost/webapp/rest/host (ContextPath: /webapp)
In Tomcat 7, we got:
getPathInfo()): null
getServletPath(): /rest/host
But in Tomcat 8:
getPathInfo()): /host
getServletPath(): /

I have work around this problem currently by setting correct value of servletPath in onOpen method of an WebSocketProtocol implementaion.

**Comment by jfarcand** [comment]
OK I'm closing this issue as invalid unless you demonstrate the issue using once of the Atmosphere sample. `2.0` may have suffered some issues that got fixed in `2.3`. Ttry `2.2.6` to be sure.
