### ISSUE TITLE
HeartbeatInterceptor make redirecting failed

### ISSUE THREAD

**Issue by ansoncat** [Atmosphere/atmosphere#1967]
When upgrading our Spring MVC (3.0.7) based application from Atmosphere 2.0 to 2.3.0, the page redirection is broken. Actually, a 302 redirecting without location header is issued. We found the workaround occasionally. By disabling the HeartbeatInterceptor, redirecting works as normal. We got same results on Tomcat 7/Tomcat 8/Jetty 8.

It may be related to #1407 ?

**Comment by jfarcand** [comment]
@ansoncat You will need to share some test case that demonstrate your issue...I've tested with Spring 4 and everything works as expected, so I will need some help...I fail to understand why the interceptor would cause such issue. So please package a test :-)
