### ISSUE TITLE
May sending incorrect Websocket message while no AsyncIOInterceptor is registered

### ISSUE THREAD

**Issue by ansoncat** [Atmosphere/atmosphere#1968]
As reported  in #1967, we have to disable HeartbeatInterceptor (actually all defaults is disabled) when upgrading our Spring MVC (3.0.7) based application from Atmosphere 2.0 to 2.3.0. Because of disabling all interceptors, our websocket application is failed to send correct content to client. We found that content of the first message is correct but the second message is wrong. 
For example:
1. server sent: "hello",  client got: "hello"
2. server sent: 1, but client got 0 !!

After digging code and experimenting different configurations, a simple workaround is found. Applying a dummy AsyncIOInterceptor works, and all messages are sent correctly.

PS: WEBSOCKET_BINARY_WRIT is set to true

**Comment by jfarcand** [comment]
That's the normal behavior, e.g if you disable all the interceptors and if your application requires some, then it will be broken. Please share some test case as well, with the workaround. Thanks

**Comment by jfarcand** [comment]
Closing, please re-open with a valid test case based on one of the Atmosphere's sample.
