### ISSUE TITLE
Provide error page support

### ISSUE THREAD

**Issue by cwellekoetter** [Atmosphere/atmosphere#1973]
I am using atmosphere-runtime:2.1.4 along with a current Apache-Tomcat:7.0.59+ and Wicket integration (Apache-Wicket:6.18.0, org.apache.wicket.experimental.wicket6:wicket-atmosphere:0.19). All pages and resources (including the error pages) are served by Wicket, which is integrated in the AtmosphereServlet.

After updating the wicket-atmosphere artifact to a newer version (0.20-0.22), which use a newer atmosphere-runtime ( 2.1.4+) we get empty error pages with HTTP-Status-Code 501. Also we get the following log message: "Invalid request state. AsyncContext#startAsync not supported. Make sure async-supported is set to true in web.xml". 
After some investigation I found out which code change is responsible for this behavior, I found the following commit (line 125ff): 
https://github.com/Atmosphere/atmosphere/commit/83ec6b87235a91179cf572f9a4ffca41833c1254 

Following web.xml configuration:

<web-app>

...
    
    
    

    <error-page>
        <error-code>403</error-code>
        <location>/forbidden.html</location> 
    </error-page>

    <error-page>
        <error-code>404</error-code>
        <location>/notFound.html</location> 
    </error-page>

   
    
    

    

    <servlet>
        <servlet-name>atmosphere</servlet-name>
        <servlet-class>org.atmosphere.cpr.AtmosphereServlet</servlet-class>
        <init-param>
            <param-name>org.atmosphere.cpr.sessionSupport</param-name>
            <param-value>true</param-value>
        </init-param>
        <init-param>
            <param-name>org.atmosphere.cpr.removeSessionTimeout</param-name>
            <param-value>false</param-value>
        </init-param>
        <init-param>
            <param-name>org.atmosphere.websocket.WebSocketProtocol</param-name>
            <param-value>org.atmosphere.websocket.protocol.EchoProtocol</param-value>
        </init-param>
        <init-param>
            <param-name>org.atmosphere.cpr.AtmosphereInterceptor</param-name>
            <param-value>org.atmosphere.client.TrackMessageSizeInterceptor</param-value>
        </init-param>
        <init-param>
            <param-name>org.atmosphere.client.TrackMessageSizeInterceptor.delimiter</param-name>
            <param-value><![CDATA[<|msg|>]]></param-value>
        </init-param>
        <init-param>
            <param-name>org.atmosphere.cpr.broadcasterCacheClass</param-name>
            <param-value>org.atmosphere.cache.UUIDBroadcasterCache</param-value>
        </init-param>
        <load-on-startup>0</load-on-startup>
        <async-supported>true</async-supported>
    </servlet>

    <servlet-mapping>
        <servlet-name>atmosphere</servlet-name>
        <url-pattern>/*</url-pattern>
    </servlet-mapping>

</web-app>

Following atmosphere.xml configuration:

```xml
<atmosphere-handlers>
    <atmosphere-handler context-root="/*" class-name="org.atmosphere.handler.ReflectorServletProcessor">
        <property name="filterClassName" value="org.apache.wicket.protocol.http.WicketFilter" />
        <applicationConfig>
            <param-name>applicationFactoryClassName</param-name>
            <param-value>org.apache.wicket.spring.SpringWebApplicationFactory</param-value>
        </applicationConfig>
        <applicationConfig>
            <param-name>applicationBean</param-name>
            <param-value>wicketApplication</param-value>
        </applicationConfig>
        <applicationConfig>
            <param-name>configuration</param-name>
            <param-value>development</param-value>
        </applicationConfig>
        <applicationConfig>
            <param-name>filterMappingUrlPattern</param-name>
            <param-value>/*</param-value>
        </applicationConfig>
    </atmosphere-handler>
</atmosphere-handlers>
```

PS: Error pages, that are directly forwarded in Wicket (like InternalServerError) work smoothly. Error Pages that are defined in the web.xml, do not work with with the AtmosphereServlet

**Comment by jfarcand** [comment]
I don't think it's a bug in Atmosphere. This message is from the Servlet Spec:
```java
"Invalid request state. AsyncContext#startAsync not supported. Make sure async-supported is set to true in web.xml". 
```
Also please try at least with `2.1.10` and let's follow up on the mailing list https://groups.google.com/group/atmosphere-framework?pli=1

**Comment by cwellekoetter** [comment]
The log message is produced in the AsynchronousProcessor of the atmosphere framework:

```java
if (isServlet30 && !req.isAsyncSupported()) {
    logger.error("Invalid request state. AsyncContext#startAsync not supported. Make sure async-supported is set to true in web.xml");
    res.setStatus(501);
    res.addHeader(X_ATMOSPHERE_ERROR, "AsyncContext not enabled");
    res.flushBuffer();
    return new Action();
}
```
This conditional block was added from version 2.1.4 to 2.1.5. (See your commit https://github.com/Atmosphere/atmosphere/commit/83ec6b87235a91179cf572f9a4ffca41833c1254)


If it is not a bug of atmosphere, can you please give me an advice/workaround for generating error pages that should be rendered by Wicket (defined in the atmosphere.xml)?

**Comment by cwellekoetter** [comment]
With version 2.1.10 I get the same error, if i would like to access http://localhost:8080/abcdefgh (which does not):

…
ERROR 16:10:44 org.atmosphere.cpr.AsynchronousProcessor: Invalid request state. AsyncContext#startAsync not supported. Make sure async-supported is set to true in web.xml
…

**Comment by jfarcand** [comment]
Yes, this is a bug in your application. Like I said, this is a Servlet Spec mandatory deployment descriptor. If Atmosphere gets called without it, then it fail as expected. Take a look at the definition of 'HttpServletRequest#isAsyncSupported()' for more information. But for sure nothing can be done here.

**Comment by cwellekoetter** [comment]
`async-supported` is defined for every filter and servlet in my web.xml. The only problem are the error pages, that also should be generated by wicket:
 
<error-page>
    <error-code>403</error-code>
    <location>/forbidden.html</location> 
</error-page>

<error-page>
    <error-code>404</error-code>
    <location>/notFound.html</location> 
</error-page>

I think it is a general problem: If error pages should be generated by a framework like Wicket, Vaadin, GWT, or etc. that is used with the AtmosphereServlet, then you will not get it but only a blank page with the error code 501.

As a workaround i will have to generate the error pages with simple jsp files.

**Comment by jfarcand** [comment]
@cwellekoetter I still fail to understand why the error page ends up within Atmosphere? But I'm open to suggestion about helping the issue. Can you share a test case? Also if you remove the code that generate the 501, does it work?

**Comment by cwellekoetter** [comment]
With `atmosphere-runtime:2.1.4` the error pages are generated and returned. With any `atmosphere-runtime > 2.1.4` I get a blank error page with state code 501.

As you can see in the web.xml snippet, that i posted for this task, every request loops through the AtmosphereServlet. I have only one atmosphere handler configured, that dispatches  all requests to the Wicket Filter, as you can see in the atmosphere.xml snippet above.

If I request a resource, that does not exist / that Wicket cannot handle, then the default error configuration of tomcat will act:

```xml
<error-page>
    <error-code>404</error-code>
    <location>/notFound.html</location> <!-- notFound.html is a mount to the Wicket page: PageNotFoundPage.java -->
</error-page>
```
The location "/notFound.html" is not a resource in the webroot, but should be handled by Wicket. 
But anyway the check of `request.isAsyncSupported` returns false.

**Comment by jfarcand** [comment]
OK Fair enough. OK I need information from you. Can you share a small test case?

**Comment by jfarcand** [comment]
Rollback #1637 to allow framework that runs on top of Atmosphere via the 'ReflectorServletProcessor' to handler error pages.
