### ISSUE TITLE
ManagedAtmosphereHandler should not try to re-enconde if no BroadcasterFilter are defined

### ISSUE THREAD

**Issue by krskrs** [Atmosphere/atmosphere#1975]
https://github.com/Atmosphere/atmosphere/blob/master/modules/cpr/src/main/java/org/atmosphere/config/managed/ManagedAtmosphereHandler.java#L211-L221

Hi, I was looking at the code in the link above, and I don't understand the comment and the code below the comment. 

The comment says:

 // No method matched. Give a last chance by trying to decode the proxiedInstance.

Where did a method not match? And where are we trying to decode something again?

Moreover it's not clear to me why, in the code just below the comment, all messages methods are iterated again and their encoders are applied on the newMsg again. Shouldn't the newMsg have already been ecoded in the:

private MethodInfo.EncoderObject message(AtmosphereResource resource, Object o)

method?

**Comment by jfarcand** [comment]
Use the ml for question ; https://groups.google.com/group/atmosphere-framework?pli=1

**Comment by jfarcand** [comment]
After the discussion [here](https://groups.google.com/forum/#!topic/atmosphere-framework/D7j5VdZLwtE), I found an issue/optimization that needs to be added to prevent re-encoding. If there are no `BroadcasterFilter` defined, then we must most re-encode.

**Comment by krskrs** [comment]
Hi, thanks for your attention. I saw your change, but now, if a message has already been processed (wrapped inside Managed class) but at the same time there are no BroadcasterFilter defined, 
this condition is false:

`if (r.getBroadcaster().getBroadcasterConfig().hasFilters() && Managed.class.isAssignableFrom(msg.getClass())) {`

and the else block is always executed. But inside of it, the message is processed again by a call to:

`final MethodInfo.EncoderObject e = message(r, msg);`

Perhaps this might lead to redundant processing / encoding / decoding again and maybe the message method is not even able to handle a msg wrapped in the Managed class.

At a first thought, I would suggest something like:

```java
if (Managed.class.isAssignableFrom(msg.getClass())) {
    Object newMsg = Managed.class.cast(msg).o;
    event.setMessage(newMsg);
    // encoding might be needed again since BroadcasterFilter might have modified message body
    // This makes application development more simpler.
    // Chaining of encoder is not supported.
    // TODO: This could be problematic with String + method
    if (r.getBroadcaster().getBroadcasterConfig().hasFilters()) {
        for (MethodInfo m : onRuntimeMethod) {
            o = Invoker.encode(encoders.get(m.method), newMsg);
            if (o != null) {
                event.setMessage(o);
                break;
            }
        }
    }
}
```

**Comment by jfarcand** [comment]
Indeed, your fix is much better. Applied. Thanks. 

Please continue reviewing,...I like that :-)
