### ISSUE TITLE
java.lang.IllegalStateException: No SessionManager in Atmosphere-2.3.1 with some jetty

### ISSUE THREAD

**Issue by elakito** [Atmosphere/atmosphere#1978]
This seems to be causing a regression error in atmosphere-2.3.1 when using jetty.

In earlier atmosphere versions, the following code was in AtmosphereRequest's getSession(boolean create) method.

            if (ex.getMessage() != null || ex.getMessage().equalsIgnoreCase("No Session Manager")) {
                return null;
            }

which was changed in 2.3.1 into
            if (ex.getMessage() != null && ex.getMessage().equalsIgnoreCase("No Session Manager")) {
                return null;
            }

This was not really working as intended, as the message text in jetty could be "No SessionManager". In fact, many jetty versions that I looked at have this string.

We should change the equality check to also match "No SessionManager".

**Comment by elakito** [comment]
@jfarcand 
do you think we should change the check to
just ex.getMessage().startsWith("No Session")?
or do we need to use a case-insensitive match on both kinds "No SessionManager" and "No Session Manager"?
I don't know if it was ever "No Session Manager".
thanks.
aki

**Comment by elakito** [comment]
@jfarcand 
Since I don't see any use of the wording "No Session Manager" in jetty. I switched this condition check to  equals("No SessionManager"). Since the equality check of the second claus of the old check of "ex.getMessage() != null || ex.getMessage().equalsIgnoreCase("No Session Manager")" was never fired before, I don't think the text to "No SessionManager" in the new check will introduce any regression.
I hope you find it also okay.
regards, aki

**Comment by jfarcand** [comment]
+1
