### ISSUE TITLE
org.atmosphere:atmosphere-runtime-native Maven Central sources jars do not contain source for all classes in binary jars

### ISSUE THREAD

**Issue by rgoldberg** [Atmosphere/atmosphere#1979]
The org.atmosphere:atmosphere-runtime-native Maven Central sources jars do not contain the source for all classes in their corresponding binary jars.

e.g., atmosphere-runtime-native-2.2.7-sources.jar only has one java file:

org.atmosphere.cpr.AtmosphereServlet.java

Can you include in the *-sources.jar the sources for all classes in the corresponding *.jar?

If you cannot do this, where are the sources for other classes?  Why wouldn't you include sources for all classes?

**Comment by jfarcand** [comment]
The source are inside `atmosphere-runtime-source` for all remaining classes. Open a pull request with a solution for a fix :-)
