### ISSUE TITLE
Samples are outdated

### ISSUE THREAD

**Issue by krissco** [Atmosphere/atmosphere#1985]
Samples such as https://github.com/Atmosphere/atmosphere/wiki/Getting-Started-with-Meteor,-WebSocket-and-Long-Polling are outdated and do not compile on recent versions of Atmosphere. Please refactor using the new javax.inject.Inject functionality added in 2.3.

Thank you!

**Comment by gdrouet** [comment]
@jfarcand with a tool like asciidoctor we can include in the documentation some pieces of code from our compiled source code. I think this could really help to maintain the documentation and make sure our samples contains up to date stuffs. Did you already investigate this approach?

**Comment by jfarcand** [comment]
@gdrouet Never used asciidoctor. Could be a good idea to take a look...

**Comment by gdrouet** [comment]
I'm currently working on it for WUIC and it's look very promising. I'll back to you with feedbacks next week.

**Comment by krissco** [comment]
Looks like the samples are already written, but the wiki is the outdated part.

https://github.com/Atmosphere/atmosphere-samples/blob/master/samples/meteor-chat/src/main/java/org/atmosphere/samples/chat/MeteorChat.java

**Comment by gdrouet** [comment]
So I finished the migration of the GitHub wiki for my project. Now, if I want to add pieces of code like in [this page](http://wuic.github.io/api.html#_java_config), I can write something like [this](https://github.com/wuic/wuic.github.io/blob/sources/src/main/asciidoc/api.adoc#user-content-create-the-facade). The code lives in the repository and is compiled each time you build the project. Any breaking change will be fixed and the documentation is still up to date.

However for Atmosphere it's tedious and time consuming to migrate a lot of pages to .adoc files. I quickly check on the web but did'nt find a way to use this kind of feature in GitHub wiki...
