### ISSUE TITLE
js Client Messages gets dropped/ignored by atmosphere 

### ISSUE THREAD

**Issue by mmhmmh** [Atmosphere/atmosphere#1991]
For some reason, the atmosphere will drop all messages sent from the js client when it get into a bugged state.

Debug tracing points to the following block of code.

            Method invokedMethod = (Method) request.localAttributes().remove(getClass().getName());
            if (invokedMethod != null) {
                for (MethodInfo m : onRuntimeMethod) {
                    if (invokedMethod.equals(m.method)) {
                        return m.encode(encoders, o);
                    }
                }
            }

**Additional details:**
There are 3 @Message annotation used. One of which has two parameters of the resource + the message, lets call this method A. The other two only has the message and no resource as parameter lets call this method B and C.

The message is for sure received by atmosphere through the use of debug interceptor.

**Problem:**
When the message comes in from the client side that is supposedly be parsed by method B decoder, the first line will return an invokeMethod that is the @Message annotated method A and thus skip the decoding and invoking method B.

This will happen for ALL subsequent messages coming form the client.

This bugged state will not happen always but when it gets into the bugged state it will stay there until either server restart. Refreshing the page will sometimes help.

Any insight in why this is happening is greatly appreciated. I tried reading the code but could not grasp what is going on.

**Comment by jfarcand** [comment]
@mmhmmh The only way to help here is to add a full unit test or application that demonstrate the issue on github.

**Comment by jfarcand** [comment]
Closing for now, reopen once you have a test case.
