### ISSUE TITLE
atmosphere-jersey @Suspend(writeEntity=false) not working

### ISSUE THREAD

**Issue by sachtilah** [Atmosphere/atmosphere#1993]
When creating filters in AtmosphereFilter class based on method's anotations the writeEntity attribute of Suspend annnotation is  ignored and always set to true.

 if (am.isAnnotationPresent(Suspend.class)) {

            long suspendTimeout = am.getAnnotation(Suspend.class).period();
            TimeUnit tu = am.getAnnotation(Suspend.class).timeUnit();
            suspendTimeout = translateTimeUnit(suspendTimeout, tu);

            Suspend.SCOPE scope = am.getAnnotation(Suspend.class).scope();

            if (am.getAnnotation(Suspend.class).resumeOnBroadcast()) {
                f = new Filter(Action.SUSPEND_RESUME,
                        suspendTimeout,
                        0,
                        scope,
                        null,
                        null,
                        true,  ///// tho should be am.getAnnotation(Suspend.class).writeEntity(),
                        am.getAnnotation(Suspend.class).contentType());
            } else {
                f = new Filter(Action.SUSPEND,
                        suspendTimeout,
                        0,
                        scope,
                        null,
                        null,
                        true, ///// same here tho am.getAnnotation(Suspend.class).writeEntity(),
                        am.getAnnotation(Suspend.class).contentType());
            }
            f.setListeners(am.getAnnotation(Suspend.class).listeners());

            list.addFirst(f);
        }

**Comment by jfarcand** [comment]
@sachtilah Good catch, fixed in 2.2.x. and 2.3.x
