### ISSUE TITLE
long-polling transport problem with chat example

### ISSUE THREAD

**Issue by john-rambo1** [Atmosphere/atmosphere#1996]
Hi,

We are trying to run chat application example over long-polling transport (no web socket).
When application is started:
```text
11:34:12.708 [RMI TCP Connection(3)-127.0.0.1] INFO  o.atmosphere.cpr.AtmosphereFramework - Atmosphere Framework 2.3.2 started.
11:34:12.708 [RMI TCP Connection(3)-127.0.0.1] INFO  o.atmosphere.cpr.AtmosphereFramework - 
[2015-06-11 11:34:12,730] Artifact atmospheredemo:war exploded: Artifact is deployed successfully
[2015-06-11 11:34:12,731] Artifact atmospheredemo:war exploded: Deploy took 5,052 milliseconds
11:34:13.235 [Thread-7] INFO  o.atmosphere.cpr.AtmosphereFramework - Latest version of Atmosphere's JavaScript Client 2.2.11
```
Then when we visit index page it takes __60 seconds__ to see: "Choose name:" input box.
This problem was observed on:
__Firefox 38.0.5__ and __Chrome 43.0.2357.124 m__
On __IE 11__  seems to works fine.

With web-socket transport everything is working fine and "Choose name:" input box is seen immediately in the browser.

War file was tested on __Tomcat 7.0.62__ and __Tomcat 8.0.22__

Is this a known limitation of long-polling transport or this is a bug somewhere?

**Comment by jfarcand** [comment]
@john-rambo1 Please use the mailing list for question https://groups.google.com/group/atmosphere-framework?pli=1. Please specify the version used and if you are running with a proxy/firewall
