### ISSUE TITLE
websocket servlet object doesn't want to write the header

### ISSUE THREAD

**Issue by JessySod** [Atmosphere/atmosphere#2000]
I need to pass in a request parameter between my server jboss and my automate.
The plan is to use a servlet filter to go from parameter to header value and both communicates with the same sec-websocket protocol.
but the websocket servlet object doesn't want write the header.
I use a server jboss 7.1.2, spring 3.6.4 release and atmosphere framework ( atmosphere-samples chat).

http://www.megafileupload.com/4Eyn/chat.zip

**Comment by aferre** [comment]
Hi,

I have the same behaviour:

Using @AtmosphereHandlerService annotation, disabling defaults interceptor, and overriding AtmosphereResourceLifecycleInterceptor with a custom implementation I am not able to add cutsom headers to the response of the first get request.

Isn't it sufficient in the public Action inspect(AtmosphereResource r) method to add the header to the response?

I see in the code of AtmosphereReponse that a parameter called "delegateToNativeReponse" exists and should be related to the problem, but I have to say i don't understand how to override it.

FYI, I am using WildFly 8.2

**Comment by jfarcand** [comment]
@JessySod Next time please use the mailing list for question. Issue is for Issues :-)

You eed to write a new `WebSocketProcessor#onHandshake#onHandshake` to do what you want. Check the Javadoc/wiki form mre info.

**Comment by aferre** [comment]
Ok thank you.

Please see thread on googlegroup: https://groups.google.com/forum/#!topic/atmosphere-framework/GM3lNaryjaQ
