### ISSUE TITLE
messages cached to wrong clients when broadcasting to subset (UUIDBroadcasterCache)

### ISSUE THREAD

**Issue by krskrs** [Atmosphere/atmosphere#2004]
Hi @jfarcand this is a subtle and hard to occur bug but, if confirmed, it might be a critical one, so please double check that my findings and reasoning are correct.

let's say we broadcast a message to a subset of AtmosphereResource, then when we got to 

https://github.com/Atmosphere/atmosphere/blob/atmosphere-2.3.x/modules/cpr/src/main/java/org/atmosphere/cpr/DefaultBroadcaster.java#L642

since deliver.type = Deliver.TYPE.SET , addToCache in UUIDBroadcasterCache won't take into consideration that we're broadcasting to a limited subset of atmoresources and will cache the message for all of its currently active clients.

So, under particular circumstances, when cached messages are pushed, a message might be pushed to an atmosphereResource which was not an intended recipient for such message, and this is the critical part.

**Comment by jfarcand** [comment]
@krskrs You are right, that something that can happens. Workaround for now is to create a Broadcaster per subset.

**Comment by jfarcand** [comment]
OK a closer look, I see this is not an issue as the cache will be added for the `AtmosphereResource` which is part of the `Set`, hence the proper one.

**Comment by krskrs** [comment]
Hi @jfarcand , can you show me where is the code which adds cached message only for the AtmosphereResource which is part of the set?

**Comment by krskrs** [comment]
Hi,
this is not fixed. At present I've no time to elaborate more, but I just wanted to advise that messages broadcasted to set might still be delivered to wrong recipients. 

  AtmosphereResource cache = entry.type == Entry.TYPE.ALL ? null : entry.resource;

in case of SET entry.resource is null, so your fix didn't change much.

regards,
fc

**Comment by jfarcand** [comment]
@krskrs Thanks.
