### ISSUE TITLE
BroadcasterCache excludeFromCache 

### ISSUE THREAD

**Issue by uberstud87** [Atmosphere/atmosphere#2007]
I saw that a BroadcasterCache issue, https://github.com/Atmosphere/atmosphere/issues/2004, has been fixed. Out of curiosity, I went to look at [Understanding-BroadcasterCache](https://github.com/Atmosphere/atmosphere/wiki/Understanding-BroadcasterCache) and did this [change] (https://github.com/Atmosphere/atmosphere/wiki/Understanding-BroadcasterCache/_compare/d73a95f73563ded73184499fda52d6c45b7da1a1...b4c6301d77e5e7f7f00e49bee804a45df8792da5) to update the documentation.

I was just reading through the source codes of [UUIDBroadcasterCache.java](https://github.com/Atmosphere/atmosphere/blob/master/modules/cpr/src/main/java/org/atmosphere/cache/UUIDBroadcasterCache.java). If I'm not wrong, perhaps `excludeFromCache` doesn't really work.

True enough, `excludeFromCache` does `activeClients.remove(r.uuid())`.

But it is re-added via `cacheCandidate(broadcasterId, uuid)` whenever `addToCache` or `retrieveFromCache` is used by [DefaultBroadcaster.java](https://github.com/Atmosphere/atmosphere/blob/master/modules/cpr/src/main/java/org/atmosphere/cpr/DefaultBroadcaster.java).

I have no test case for this though, it was just based on a quick glimpse the codes.
I'm unsure if I'm actually right on this due to my inexperience. 

Anyone mind taking a look?

**Comment by jfarcand** [comment]
`excludeFromCache` is a one call operation. Check
```java
    @Test
    public void testBasicExcludeCache() throws ExecutionException, InterruptedException, ServletException {
        BroadcasterCache cache = new UUIDBroadcasterCache();
        cache.configure(config);

        AtmosphereResource r = config.resourcesFactory().create(broadcaster.getBroadcasterConfig().getAtmosphereConfig(), "1234567");

        cache.excludeFromCache(broadcaster.getID(), r);

        broadcaster.getBroadcasterConfig().setBroadcasterCache(cache);
        broadcaster.removeAtmosphereResource(r);
        broadcaster.broadcast("foo").get();

        List<Object> l = cache.retrieveFromCache(broadcaster.getID(), ar.uuid());
        assertNotNull(l);
        assertEquals(l.isEmpty(), true);
    }
```
for [more info](https://github.com/Atmosphere/atmosphere/blob/atmosphere-2.4.x/modules/cpr/src/test/java/org/atmosphere/cpr/BroadcasterCacheTest.java#L198-214)

**Comment by jfarcand** [comment]
`excludeFromCache` is a one shut operation. See [this](https://github.com/Atmosphere/atmosphere/blob/atmosphere-2.4.x/modules/cpr/src/test/java/org/atmosphere/cpr/BroadcasterCacheTest.java#L198-214) for more information
