### ISSUE TITLE
Provide an option for the client to request for websocket responses without the length delimiter

### ISSUE THREAD

**Issue by elakito** [Atmosphere/atmosphere#2013]
The motivation for this feature is described in:

https://groups.google.com/forum/#!searchin/atmosphere-framework/content-lelngth/atmosphere-framework/TYoIDBeyTFQ/GkfAJdmP8tMJ

**Comment by elakito** [comment]
@jfarcand  I can work on this next week. I don't know which parameter is more suitable: a query string parameter or an x-header header? So, if you can give me some suggestion, that would be appreciated.

**Comment by jfarcand** [comment]
@elakito I think we need to support both...for example, if you use CORS with Amazon's ELB it will remove the header, hence I think we can improve the [Atmosphere's protocol](https://github.com/Atmosphere/atmosphere/wiki/Understanding-the-Atmosphere-Protocol) by adding a query string. Thanks a lot Aki!

**Comment by elakito** [comment]
@jfarcand I'm sorry that I had been distracted and had not spent time on this issue for a while.
I looked into it finally today and would like to discuss over the points that we discussed earlier and about a possible solution.

Regarding the use of query-paramters or headers, I noticed that AtmosphereFramework.configureRequestResponse moves all the X-Atmosphere query parameters to the request headers. So we can assume that the server side code needs to just react to the header that we choose.

Regarding the header name, could we simply use the existing X-Atmosphere-TrackMessageSize? That means, if this header is not set to true, we can just disable the size tracker interceptor's transformation. I think this will make sense, assuming the client requesting the size-tracked message is setting this parameter.

I'll definitely stick to this task and would like to resolve it by next week. ;-)

thanks.
regards, aki

**Comment by jfarcand** [comment]
```
Regarding the use of query-paramters or headers, I noticed that AtmosphereFramework.configureRequestResponse moves all the X-Atmosphere query parameters to the request headers. So we can assume that the server side code needs to just react to the header that we choose.
```
Yes, that's true. 
```
Regarding the header name, could we simply use the existing X-Atmosphere-TrackMessageSize? That means, if this header is not set to true, we can just disable the size tracker interceptor's transformation. I think this will make sense, assuming the client requesting the size-tracked message is setting this parameter.
```
+1

Thanks Aki!

**Comment by elakito** [comment]
@jfarcand 
I committed the fix shown above (only in master at the moment). Let me know if that is okay and also okay to integrate it into 2.4.0. 

I have removed the javascript label because we don't need any change in the javascript part.
regards, aki

**Comment by jfarcand** [comment]
+1 Great work.
