### ISSUE TITLE
Shiro + Tomcat 8 websocket (JSR356) 

### ISSUE THREAD

**Issue by ericvandever** [Atmosphere/atmosphere#2014]
ShiroInterceptor added attribute FrameworkConfig.SECURITY_SUBJECT is not available from WebSocketHandler when using Tomcat8 and JSR356 API.  

Version info: 
Atmosphere is using async support: org.atmosphere.container.JSR356AsyncSupport running under container: Apache Tomcat/8.0.23 using javax.servlet/3.0 and jsr356/WebSocket API
atmosphere.cpr.AtmosphereFramework - Atmosphere Framework 2.3.3 started.

The websocket is successfully created/opened and I'm able to send messages back and forth with a client.  The issue seems to be that the JSR356 AtmosphereRequest is created with the default destroyable value of true, instead of the set to false (or the value of the Application config parameter) as in Jetty9 or Tomcat7 in the corresponding WebSocketUtils

```java
            boolean isDestroyable = false;
	            s = config.getInitParameter(ApplicationConfig.RECYCLE_ATMOSPHERE_REQUEST_RESPONSE);	
	            if (s != null && Boolean.valueOf(s)) {
	                isDestroyable = true;
	            }
```

Because destroyable is true, the destroy call at the bottom of AtmosphereFramework doCometSupport removes the localAttributes, including ShiroInterceptor's SECURITY_SUBJECT from the request before it is passed to my custom handler.

**Comment by jfarcand** [comment]
@ericvandever Good catch. Fixed in `2.2.8-SNAPSHOT/2.3.4-SNAPSHOT/2.4.0-SNAPSHOT`
