### ISSUE TITLE
Jetty9WebSocket.write tries to write on CLOSING connection

### ISSUE THREAD

**Issue by fpn** [Atmosphere/atmosphere#2015]
Hi,

Jetty9WebSocket.write checks webSocketConnection.isOpen() before write, but 
org.eclipse.jetty.websocket.common.io.IOState.isOpen()
only checks:  (getConnectionState() != ConnectionState.CLOSED)

In our case the connection state is ConnectionState.CLOSING and the write throws an exception:

org.eclipse.jetty.websocket.api.WebSocketException: RemoteEndpoint unavailable, current state [CLOSING], expecting [OPEN or CONNECTED]

best regards,
Florian

**Comment by jfarcand** [comment]
Jetty doesn't expose any method to catch that case.
