### ISSUE TITLE
Add support for Spring WebSocket in order to support Spring Security

### ISSUE THREAD

**Issue by jfarcand** [Atmosphere/atmosphere#2016]
As bad as it sound, Spring Security only support Spring WebSocket and not jsr 356 (quite unfair)

http://docs.spring.io/spring-security/site/docs/current/reference/html/websocket.html

(bullshit comment included...if it works with Spring WebSocket on Tomcat 8, that means the implementation is using jsr356!!!).

For enterprise that require support of Spring Security with Atmosphere, the workaround would consist of bridging a Spring WebSocket Endpoint the same way we support native websocket implementation.

**Comment by rstoyanchev** [comment]
Spring Security provides HTTP URL-based security, as it always has, and that can also protect the handshake for WebSocket endpoints. It's just a filter. As long as you after it, you should be okay. What is it that is not working exactly? 

The comment about JSR-356 simply means that there is nothing more that Spring Security can do beyond securing the URLS since there is no knowledge of what's in the message. By contrast the Spring WebSocket support include STOMP as a sub-protocol. You can authorize based on the STOMP destination, the type of STOMP frame, etc.

**Comment by jfarcand** [comment]
@rstoyanchev Thanks for the explanation :-) Spring Security Filter can be run on top of Atmosphere (instead of before) and I suspect this is where some issues arise, mostly because Atmosphere wraps websockets messages as if they where normal http (to over simplify it). I'm waiting for my customer to share a test case so I will have more information, but some scenarios seems to [work fine](https://github.com/AndreasKl/springboot-angular-atmosphere-quickstart)

I've filled the issue as I was under the impression we where in the [same situation](https://github.com/spring-projects/spring-boot/issues/2341) of Spring Boot dependency with Spring WebSocket, which is now fixed. I just hope we aren't in the same situation, but if we are, then I can always run Atmosphere on top of Spring WebSocket if it gives my community easy access to Spring WebSocket's companion project.

**Comment by gdrouet** [comment]
@jfarcand do you have any update on this? I don't see any wbesocket security in [this application](https://github.com/AndreasKl/springboot-angular-atmosphere-quickstart). So the problem is that spring security is filtering endpoint URLs handled by Atmosphere or that we can't add security to websocket messages?

@rstoyanchev if there any possibility to define our own sub protocol and then allow the user to give an implementation that identifies what kind of message is going to be filtered? Or is it not possible because the spring websocket implementation is tightly coupled to STOMP protocol?

Thanks

**Comment by jfarcand** [comment]
@gdrouet It involve a lot of work so I won't be able to work on that, so it will be community driven :-)

**Comment by gdrouet** [comment]
@jfarcand I know actually I was asking if you have an update for `I'm waiting for my customer to share a test case so I will have more information` ;-)

**Comment by rstoyanchev** [comment]
I honestly don't understand what this issue really is about. As I commented above the original title and description don't really give me anything concrete I can understand or make suggestions about. What is the real issue?

**Comment by gdrouet** [comment]
@rstoyanchev it is not sure that we have any bug here. I feel it´s just a lack of example on how we can secure some endpoints in atmosphere using spring security. After reading the documentation, I think we have all what we need in the spring security api to manage autorization in atmosphere, and maybe we need a little extension that install an interceptor checking authentication (maybe!). I'll take a look.

**Comment by gdrouet** [comment]
@rstoyanchev I finished to deeply rely on spring-security in an application that uses Atmosphere, and I don't faced any clash between the two frameworks. IMO there is absolutely no bug related to spring-security support with Atmosphere.

Now, I was thinking that we can keep this issue opened if we want an extension where Atmosphere can rely on spring-security to completly secure its own subprotocol. One of the fundamental aspect of spring-security to secure resources is the [RequestMatcher](http://docs.spring.io/autorepo/docs/spring-security/3.2.6.RELEASE/apidocs/org/springframework/security/web/util/matcher/RequestMatcher.html) that allows the framework to know which security rules must be applied or not. The `RequestMatcher` explicitely manipulates the `HttpServletRequest` object, which is an issue for me. In fact, what helps us to access to subprotocols information is tipically the [AtmosphereResource](http://atmosphere.github.io/atmosphere/apidocs/org/atmosphere/cpr/AtmosphereResource.html) that actually wraps the `HttpServletRequest` with a lot of additional information related to the framework. What needs spring-security in that case is matchers manipulating the `AtmosphereResource`.

My first conclusion is that developing an extension of spring-security supporting atmosphere (typically a subclass of `WebSecurityConfigurerAdapter `) is tricky until we register `RequestMatcher` that explicitely manipulates the `AtmosphereResource`. More things will be possible If the security architecture can rely on a parameterized matcher interface like this:

```java
public interface RequestMatcher<T> {
	boolean matches(T request);
}
```

This way we can register a matcher for `AtmosphereResource`. This extension point could interest a lot of framework that would rely on spring-security, not just Atmosphere.

Your thoughts?

**Comment by rstoyanchev** [comment]
Conceptually it makes sense but I'll let @rwinch comment whether Spring Security can be parameterized like that and if it makes sense to open a ticket in the Spring Security issue tracker. 

Thanks for the comments and feedback!

**Comment by rwinch** [comment]
@gdrouet Thanks for the feedback. I'm not certain that simply providing a generic `RequestMatcher<T>` will provide a lot of value.

The first problem is that objects that are passing in the `HttpServletRequest` will need to convert to the correct type of object. We could add hooks to allow for conversion of this, but this adds quite a bit of complexity. It also won't solve the next point.

The second problem is that this is really the tip of the iceberg. Spring Security's web tier is built on top of the Servlet Filter which uses `HttpServletRequest` quite heavily. This means that things like authorization, HTTP response headers, CSRF Protection, etc are still built on top of `HttpServletRequest`.

Perhaps a better approach is to provide an `AbstractAtmosphereResourceRequestMatcher` which does the conversion for users and allows a match based upon `AtmosphereResource`. What are your thoughts?

**Comment by rstoyanchev** [comment]
Also not sure if this makes sense or not but I'm wondering if given an HttpServletRequest instance there is a way to obtain the associated AtmosphereResource?

**Comment by jfarcand** [comment]
@rstoyanchev Yes, by doing
```java
AtmosphereResource r = httpServletRequest.getAttribute(FrameworkConfig.ATMOSPHERE_RESOURCE);
```

**Comment by rstoyanchev** [comment]
Okay so then Spring Security RequestMatcher can obtain the AtmosphereResource through the request and hence a `AtmosphereResourceRequestMatcher` should be an option.

**Comment by gdrouet** [comment]
Yes that's a good tip! thx @jfarcand!

But as mentionned by @rwinch we still need to figure out how we adapt the filter chain. Atmosphere provides an equivalent built-in API called `AtmosphereInterceptor`. It's should be easy to create a bridge to an authorization filter that checks endpoint subscriptions.

However I think we need a complete custom implementation for CSRF, as token is transferred through the sub protocol messages over the same request (websocket). I need to do more investigations...

**Comment by jfarcand** [comment]
Will be done here https://github.com/Atmosphere/Atmosph4rX
