### ISSUE TITLE
[WebLogic] 12.1.3 BlockingIOCometSupport selected

### ISSUE THREAD

**Issue by oyvindhorneland** [Atmosphere/atmosphere#2018]
Atmosphere-runtime: 2.3.3
WebLogic: 12.1.3

This issue has been discussed before in #1234 and as part of #1856 but it seems it is not resolved in 2.3.3.

When deploying on WebLogic 12.1.3 the JSR356AsyncSupport fails to resolve and BlockingIOCometSupport is chosen even if Servlet30CometSupport is available.

--
The method DefaultAsyncSupportResolver.resolve(boolean useNativeIfPossible, boolean defaultToBlocking, boolean useServlet30Async) is called with
* useNativeIfPossible: false
* defaultToBlocking: false
* useServlet30Async: true

This resolves to true
useServlet30Async = testClassExists(SERVLET_30); 

resolveWebSocket is trying to resolve org.atmosphere.container.JSR356AsyncSupport, which fails with java.lang.reflect.InvocationTargetException. The problem here is that newCometSupport returns BlockingIOCometSupport and when DefaultAsyncSupportResolver.resolve checks:
```
        if (cs == null) { // cs has already been set to BlockingIOCometSupport  here!
            AsyncSupport nativeSupport = resolveNativeCometSupport(detectContainersPresent());
            return nativeSupport == null ? defaultCometSupport(defaultToBlocking) : nativeSupport;
        } else {
            return cs;
        }
```

cs has already been set to BlockingIOCometSupport and will never attempt to fallback to Servlet30CometSupport when if available.

While I'm not sure why WebLogic fails to resolve JSR356AsyncSupport, it should probably default to Servlet30CometSupport if available and BlockingIOCometSupport as a last resort.

**Comment by jfarcand** [comment]
@oyvindhorneland I agree. Contribution welcomed if you have the cycle! Thanks for your help, as usual!

**Comment by oyvindhorneland** [comment]
Just added PR #2019 with fix for this issue.
