### ISSUE TITLE
jquery.atmosphere.js - long polling request is being aborted by firefox

### ISSUE THREAD

**Issue by snimavat** [Atmosphere/atmosphere#2020]
we have an angualr application which calls subscribe() with long polling transport when some even occours (route change) on the scree. however the issue is, as soon as the subscribe is called, i can see the ajax call for the subscribe url is being aborted by firefox.

With chrome, the error is 
"Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience".

And i see in firebug that the request does not have Requested with Xml http request header.

**Comment by jfarcand** [comment]
Please file the issue here => https://github.com/Atmosphere/atmosphere-javascript

Also please put the version used and some code. Thanks!

**Comment by jfarcand** [comment]
But first, please use the mailing list as the issue seems to be with your code :-)

https://groups.google.com/group/atmosphere-framework?pli=1
