### ISSUE TITLE
JgroupBroadcaster

### ISSUE THREAD

**Issue by contactakagrawal** [Atmosphere/atmosphere#2022]
Hi,

I am having trouble using JGroupBroadcaster, in JGroupBroadcaster we are creating JChannel with default constructor which reads udp.xml inside jgroup jar, Where should I provide tcp-ip configuration to configure multiple ip addresses in a cluster which JGroupBroadcaster can use.

like while using HazelCastBroadcaster it uses hazelcast.xml from classpath, I want similar thing with jgroup.

Thanks,
Amit.

**Comment by jfarcand** [comment]
Pull request welcomed :-)
