### ISSUE TITLE
Problem with long-pooling in atmosphere-samples in IE 9 (browser without websocket support)

### ISSUE THREAD

**Issue by gorshkov-leonid** [Atmosphere/atmosphere#2023]
Hello,
we are trying to run examples:
https://github.com/Atmosphere/atmosphere-samples/tree/master/samples/jersey2-chat
https://github.com/Atmosphere/atmosphere-samples/tree/master/samples/meteor-chat
and others.
All examples work in browsers with websocket support, but no one example works with long-pooling protocols (tested in IE 9). We get exception:  "Sorry, but there's some problem with your socket or the server is down".
I’m trying to run examples on old versions of atmosphere-samples. In version 2.3 and higher it doesn’t work with the same problem. In version 2.2.8 I got a message "Connecting..." in IE 9, until I send a message in chat from Google Chrome. After that long-pooling start work in IE, but name in chat displayed as “false”.
Could you fix examples for long-pooling?

**Comment by jfarcand** [comment]
Please use the mailing list for question. IE 9 works fine, you have a local issue.

**Comment by gorshkov-leonid** [comment]
Description was updated with screenshots and logs. Local problem? It is strange.....

**Comment by gorshkov-leonid** [comment]
Problem published in 
https://groups.google.com/forum/#!topic/atmosphere-framework/M53ijxv79xo
