### ISSUE TITLE
atmosphere-redis functioning differently in aws elasticcache then local redis

### ISSUE THREAD

**Issue by Unbr8kbal** [Atmosphere/atmosphere#2028]
Hello,

I have a project, it all works fine and good locally, except now i have to put it into the cloud, and i'm seeming to have a few issues using in my aws elasticache. Now the client connections get created in redis aws like i thought they would and the channels are there, however every time

 i open a channel and post a message, i'm using a chat example, it seems to always be creating a new broadcaster.

I'm attaching a jpg(just a renamed zip) of the project, it's all code
![archive](https://cloud.githubusercontent.com/assets/1782545/8842920/f2ef531e-3143-11e5-867b-8b8f3dd9d76b.jpg)
.

**Comment by jfarcand** [comment]
Please use the mailing list for question https://groups.google.com/group/atmosphere-framework?pli=1
