### ISSUE TITLE
ManagedAtmosphereHandler bypass the @Message method for the second broadcasted message

### ISSUE THREAD

**Issue by dreamershl** [Atmosphere/atmosphere#2029]
This is similar to the previous issue "V2.3.0-RC3 ManagedAtmosphereHandler:message discard the second request on the same method". But this time, it causes issue on sending instead of receiving.

I am using the google protobuf for my message. Before sending the message, I need use the protobuf message class encode method to encode them into the bytes array. The default protobuf toString() just print them self in text format.

Wrong messages:
![image](https://cloud.githubusercontent.com/assets/1271739/8921151/95ee7356-3504-11e5-99ad-0c6895478902.png)

Correct messages: 
add this line in the Message method     

    r.getRequest().localAttributes().remove(ManagedAtmosphereHandler.class.getName()); 
![image](https://cloud.githubusercontent.com/assets/1271739/8920934/7295f71e-3502-11e5-906f-d1505707a545.png)

Based on the debugging, the issue is caused by this  ManagedAtmosphereHandler:message

    Method invokedMethod = (Method) request.localAttributes().remove(getClass().getName());
            if (invokedMethod != null) {
                for (MethodInfo m : onRuntimeMethod) {
                    if (invokedMethod.equals(m.method)) {
                        return m.encode(encoders, o);
                    }
                }
            }

I believe this block is try to speed up the process by caching the invoked flag in the attribute. In my case, the second broadcasted message has the same request instance as the previous one.

**Comment by jfarcand** [comment]
@dreamershl I will need a test case to reproduce it as the request is per message....how do you broadcast?

**Comment by dreamershl** [comment]
The following is my broadcasting function. It is called in a background thread. To reduce the traffic, the background thread will only publish the message every 1 second. There are 2 types of payload, 1 is able to be consolidated, another one is can't. 

        private void deliverQueuedMessages()
        {
        if (messageReadyUsers.size() == 0)
        {
            return;
        }

        //broadcast the message to those ready users
        final long nowUTC = Instant.now().toEpochMilli();
        TIntArrayList processedUserIDList = new TIntArrayList();

        messageReadyUsers.forEach(userID -> {
            Triple<MutableLong, UUID, Pair<SubscriptionUpdates, List<CometResponse>>> payload =
                    userPayloadMap.get(userID);

            if (payload != null)
            {
                if ((nowUTC - payload.getLeft().longValue()) >= MAX_BROADCAST_DELAY)
                {
                    AtmosphereResource resource = cometServlet.findResource(payload.getMiddle().toString());

                    //for the long polling, it may be the client is re-connecting, just wait for the next broadcast
                    if (resource != null)
                    {
                        Pair<SubscriptionUpdates, List<CometResponse>> pair = payload.getRight();

                        StockProto.StockMsgPack msgPack = pair.getLeft().pollQueuedMessage();

                        Broadcaster broadcaster = resource.getBroadcaster();

                        broadcaster.broadcast(msgPack, resource);

                        pair.getRight().forEach(response -> broadcaster.broadcast(response, resource));

                        payload.getLeft().setValue(Instant.now().toEpochMilli());
                        processedUserIDList.add(userID);
                    }
                }
            }
            else
            {
                processedUserIDList.add(userID);
            }

            return true;
        });

        if (processedUserIDList.size() == messageReadyUsers.size())
        {
            messageReadyUsers.clear();
        }
        else
        {
            messageReadyUsers.removeAll(processedUserIDList);
        }
    }

**Comment by jfarcand** [comment]
@dreamershl So you aren't broadcasting from an annoted @Message method right? Please try the following patch.

**Comment by dreamershl** [comment]
No. My understanding is the @Message is for the message process after the broadcasting. So I put the additional logic there. 

I can't see ur patch.

**Comment by jfarcand** [comment]
@dreamershl OK rolling back #1620 again as this is the root cause and I don't see how this can be fixed.

**Comment by dreamershl** [comment]
I see. Now I am clear why you put the processed flag. In this case, you can keep this. In my case, after I remove the flag, every thing works fine.

**Comment by jfarcand** [comment]
@dreamershl I can't find a way to differenciate the two scenarios as I don't know where the broadcast operation is initiated.
