### ISSUE TITLE
Install without maven

### ISSUE THREAD

**Issue by voneddy** [Atmosphere/atmosphere#2030]
Hi I'm a total newb to Atmosphere but very impressed with what it can do based on the spec.

I hope I'm posting in the right place.

The problem I'm having I think is installing without using maven, in your docs you say just to download the JARs... I'm trying to have front end SocketIO or atmosphere.js talk to a servlet using Tomcat 7.0.34 but get no matter what path values I use I get:

SEVERE: Servlet.service() for servlet [AtmosphereServlet] in context with path [] threw exception
org.atmosphere.cpr.AtmosphereMappingException: No AtmosphereHandler found.

My suspicion is that the maven dependencies mentioned in a lot of your setup docs need to be there but like I said I'm not using maven. 

Is what I'm trying even possible? Sorry if I'm totally missing the point / being spectacularly stupid but been on this for two days and not getting anywhere and searched / researched a lot and not found any solutions so going a little mad:) ....

\i've downloaded and included the JARs mentioned in my Tomcat setup page (I don't need to worry about running on other servers) and I've set in web.xml:

<servlet>
        <description>AtmosphereServlet</description>
        <servlet-name>AtmosphereServlet</servlet-name>
        <servlet-class>org.atmosphere.cpr.AtmosphereServlet</servlet-class>
        <async-supported>true</async-supported>
    </servlet>
<servlet-mapping>
        <servlet-name>AtmosphereServlet</servlet-name>
        <url-pattern>/servlet/atmos/*</url-pattern>
</servlet-mapping>

And tried in SocketIoServlet servlet said:
@AtmosphereHandlerService(path="/servlet/atmos")
But doesn't work... 

I've also tried in the atmosphere.xml (but would rather control / route in the servlet) going:

<?xml version="1.0" encoding="UTF-8"?>
<atmosphere-handlers>
    <atmosphere-handler support-session="true"
                        context-root="/servlet/atmos"
                        class-name="net.sportplan.struts.scaffold.process.socketio.SocketIoServlet">
    </atmosphere-handler>
</atmosphere-handlers>
Still no good.

I just can't get the AtmosphereServlet talking to my class SocketIoServlet... I've tried every combination of path I can think of and think it's a set up issue...

Any would would be awesome. And thanks for reading

JM

**Comment by jfarcand** [comment]
Please use the mailing list for question https://groups.google.com/group/atmosphere-framework?pli=1
