### ISSUE TITLE
AtmosphereResource.close() sends statuscode 1005 instead of 1000

### ISSUE THREAD

**Issue by crowriot** [Atmosphere/atmosphere#2032]
When using AtmosphereResource.close() the status code a websocket client receives is always 1005 (CLOSE_NO_STATUS) whereas status code 1000 (CLOSE_NORMAL) would be more appropriate.

An API to set the status externally would be great.

**Comment by jfarcand** [comment]
@crowriot Pull request welcomed BTW :-)

**Comment by amit2103** [comment]
@jfarcand Can I work on this? I have used Atmosphere in production a lot. However it will still be great if you can give some pointers for the issue.

**Comment by crowriot** [comment]
I don't know where to start either, I've tracked everything down, if you search the code for 1005, you'll find the places where it's hardcoded. I personally would have added a property on the AtmosphereResource which status code to send on close and just lookup that attribute instead of using 1005. But i don't know if that's the preferred way to go.

**Comment by amit2103** [comment]
I will check and try to submit a Pull request

**Comment by jfarcand** [comment]
@amit2103 +1. Starts in `DefaultWebSocketProcessor`. Note that this is container based, so Jetty may not send the same number than Tomcat.

**Comment by amit2103** [comment]
@jfarcand Will try to submit a pull request by this weekend
