### ISSUE TITLE
IllegalStateException exception for the session Check

### ISSUE THREAD

**Issue by dreamershl** [Atmosphere/atmosphere#2034]
In the AsynchronousProcessor::action() function, the following block will get the IllegalStateException exception if the session is expired. It is thrown by the "s.isNew()".

      if (supportSession()) {
            // Create the session needed to support the Resume
            // operation from disparate requests.
            HttpSession s = req.getSession(config.getInitParameter(PROPERTY_SESSION_CREATE, true));
            if (s != null && s.isNew()) {
                s.setAttribute(FrameworkConfig.BROADCASTER_FACTORY, config.getBroadcasterFactory());
            }

        }

**Comment by jfarcand** [comment]
@dreamershl What should be the behavior in that case? Re-create the session?

**Comment by dreamershl** [comment]
It seems the disconnect method won't get chance call. The system itself will be re-connected again.

This exception is found when client side idle for too long (only keep the websocket connection without the HTTP interaction)

**Comment by dreamershl** [comment]
Another side effect is the request(s) which cause this exception won't be able to be proceed  accordingly. And the websocket connection is still alive. So the client side won't be able to know the connection in fact is dead.

Although the requests encounter exceptions, the heartbeat message is still received as usual.
![image](https://cloud.githubusercontent.com/assets/1271739/9116352/947db4ac-3c96-11e5-98f1-5f4c63ed9d31.png)

Server side error for the requests

    GMT 15:53:01,986 W  o.a.w.p.SimpleHttpProtocol [qtp71587369-31]({}) java.lang.IllegalStateException. Unable to deliver the websocket messages to installed component. Status 500 Message Server Error
    GMT 15:53:01,991 E  o.a.c.AtmosphereFramework [qtp71587369-30]({}) AtmosphereFramework exception java.lang.IllegalStateException
	at org.eclipse.jetty.server.session.AbstractSession.checkValid(AbstractSession.java:104) ~[jetty-server-9.2.12.v20150709.jar:9.2.12.v20150709]
	at org.eclipse.jetty.server.session.HashedSession.checkValid(HashedSession.java:79) ~[jetty-server-9.2.12.v20150709.jar:9.2.12.v20150709]
	at org.eclipse.jetty.server.session.AbstractSession.isNew(AbstractSession.java:364) ~[jetty-server-9.2.12.v20150709.jar:9.2.12.v20150709]
	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:151) ~[atmosphere-runtime-2.3.3.jar:2.3.3]
	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:108) ~[atmosphere-runtime-2.3.3.jar:2.3.3]
	at org.atmosphere.container.Jetty9AsyncSupportWithWebSocket.service(Jetty9AsyncSupportWithWebSocket.java:180) ~[atmosphere-runtime-2.3.3.jar:2.3.3]
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2262) ~[atmosphere-runtime-2.3.3.jar:2.3.3]
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:566) ~[atmosphere-runtime-2.3.3.jar:2.3.3]

**Comment by jfarcand** [comment]
@dreamershl OK so I can catch the exception and continue the request processing AND re-create a new session. Does it makes sence?

**Comment by dreamershl** [comment]
My 5 cents suggestion, I believe following the session idea, should disconnect the connection. Because the session is gone. The program should be the one to renew the session if it really need. Since the session isn't from your library, the renew should be done through the HTTP. 

Because normally the session is to differentiate the login/non-login status. When the client is 'idle' for 'too long', program would like to stop the access for protection purpose. Currently I use the auth2 login and try to migrate all the communication to your library (because it is awesome and l love it. Thank you for your great work). Then I encounter this issue.

**Comment by jfarcand** [comment]
@dreamershl OK pushed a fix on `2.3` and `2.4` branch. Let me know how it goes.

**Comment by aponyrko** [comment]
In my case the client never gets notified of the cancel event. I'm using a ReflectorServletProcessor. The resulting AtmosphereResourceEvent has a null message and I think the reason the client never receives is the message is because of the following code in AbstractReflectorAtmosphereHandler:
```
    public void onStateChange(AtmosphereResourceEvent event)
            throws IOException {

        Object message = event.getMessage();
        AtmosphereResource resource = event.getResource();
        AtmosphereResponse r = resource.getResponse();
        AtmosphereRequest request = resource.getRequest();

        boolean writeAsBytes = IOUtils.isBodyBinary(request);
        if (message == null) {
            logger.trace("Message was null for AtmosphereEvent {}", event);
            return;
        }
```

Any advice?

**Comment by jfarcand** [comment]
@aponyrko Please do not hijack the thread, use the mailing list for question.
