### ISSUE TITLE
Support for per-message deflate Websocket extension

### ISSUE THREAD

**Issue by dmerc** [Atmosphere/atmosphere#2039]
Hi!
Is there any support for per-message deflate websocket protocol extension?
We have huge traffic over websockets and would really benefit from compression.
As far as i see in the org.atmosphere.websocket namespace its not implemented, am i looking at the right place?

**Comment by jfarcand** [comment]
@dmerc Soon in Nettosphere 3.0.0 and Netty 4.1. Jetty supports it as well, so later this year.

**Comment by alejandro-lares** [comment]
Hi, we are also very interested in this feature.

Any rough idea on when this will be released? In the meantime is there any patch that we could use?

**Comment by jfarcand** [comment]
Waiting for netty/netty#4273 to be integrated and then I will start the implementation in Nettosphere.

**Comment by alejandro-lares** [comment]
Thanks

**Comment by rcamposg** [comment]
Hello,

I've managed to support compression in Jetty 9.3 (as it has support for permessage-deflate compression) by commenting the line 132 in the file Jetty9AsyncSupportWithWebsocket: `req.getExtensions().clear();` (Atmosphere 2.3.4)

@jfarcand if you think there may be some problem by changing this, please let me know.


Regards

**Comment by jfarcand** [comment]
@rcamposg Good work. Pull request welcomed!

**Comment by rcamposg** [comment]
Pull request created.

**Comment by jfarcand** [comment]
Support for Jetty 9.3+ added, will be available in 2.4.0

**Comment by rcamposg** [comment]
Hello,

Compression also works for Tomcat 7 when using JSR 356 Websockets (tested with current latest version, 7.0.70 and Atmosphere 2.3.4). You just need to:

1. Create an instance of WsServerContainer and set it as a servletContext attribute:`servletContext.setAttribute(ServerContainer.class.getName(), WsServerContainerBuilder.create(servletContext));` where WsServerContainerBuilder is a class that I've created to be instantiate it.

2. Set the `ApplicationConfig.PROPERTY_COMET_SUPPORT` parameter to `"org.atmosphere.container.JSR356AsyncSupport"`

3. Set the `ApplicationConfig.JSR356_MAPPING_PATH` value to the proper path of your endpoint (I'm not sure if this latest step is mandatory, but my handlers were not found until I set it)

Regards

**Comment by SuperPat45** [comment]
Hello,

Using Wildfly, I finally succeeded in activating compression after a half day of work:  
First, You need to enable per-message-deflate in wildfly/standalone/configuration/standalone.xml:

```
           <servlet-container name="default">
               <websockets per-message-deflate="true" deflater-level="9"/>
           </servlet-container>
```

But it is not sufficient as undertow does not enable this extension in manually created Endpoints...  
So you need to patch the JSR356AsyncSupport to force extensions like this:

```

                container.addEndpoint(ServerEndpointConfig.Builder.create(JSR356Endpoint.class, b.toString())
                        .extensions(new ArrayList<Extension>(container.getInstalledExtensions())).configurator(configurator).build());
```
