### ISSUE TITLE
atmosphere breaks communication using apache cxf

### ISSUE THREAD

**Issue by lakiluk** [Atmosphere/atmosphere#2040]
Hi, 

I'm using java 1.6 with cxf on the backend and GWT on the frontend. When I set up AtmosphereServlet in web.xml and tries to call SOAP webservice at the backend I'm getting:

javax.xml.ws.soap.SOAPFaultException: org.apache.xerces.parsers.XIncludeAwareParserConfiguration cannot be cast to org.apache.xerces.xni.parser.XMLParserConfiguration
  at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:146)

Atmosphere adds some libs to the classpath on startup:

[WARN] Server class 'com.google.gwt.user.rebind.rpc.ProxyCreator' could not be found in the web app, but was found on the system classpath
   [WARN] Adding classpath entry 'file:/D:/m2/repository/com/google/gwt/gwt-user/2.7.0/gwt-user-2.7.0.jar' to the web app classpath for this session
[WARN] Server class 'com.google.gwt.core.ext.IncrementalGenerator' could not be found in the web app, but was found on the system classpath
   [WARN] Adding classpath entry 'file:/D:/m2/repository/com/google/gwt/gwt-dev/2.7.0/gwt-dev-2.7.0.jar' to the web app classpath for this session

Do you know how to deal with it? Does anyone gets this bug too?
When I switch to java 1.8 problem dissapears, but unfortunately I cannot switch java version in our project.

Libs I'm using:

      <dependency>
                <groupId>org.atmosphere.extensions</groupId>
                <artifactId>atmosphere-gwt20-client</artifactId>
                <version>2.3.0-GWT27</version>
            </dependency>
            <dependency>
                <groupId>org.atmosphere</groupId>
                <artifactId>atmosphere-runtime</artifactId>
                <version>2.3.4</version>
            </dependency>
            <dependency>
                <groupId>org.atmosphere.extensions</groupId>
                <artifactId>atmosphere-gwt20-server</artifactId>
                <version>2.3.0-GWT27</version>
            </dependency>
            <dependency>
                <groupId>org.atmosphere.extensions</groupId>
                <artifactId>atmosphere-gwt20-managed</artifactId>
                <version>2.3.0-GWT27</version>
            </dependency>

**Comment by jfarcand** [comment]
@lakiluk Github is for issue, not question. Please ask using the mailing list https://groups.google.com/group/atmosphere-framework?pli=1
