### ISSUE TITLE
Support to retrieve factory outside the AtmosphereServlet class

### ISSUE THREAD

**Issue by vsabato** [Atmosphere/atmosphere#2043]
Hi,
I created a simple project to use Atmosphere for client engagement from the server.
Basically I have the AtmosphereServlet class (A) and another Servlet (B) that receives some events from other source. My need is to access to the BroadcasterFactory from the Servlet (B) and then execute a lookup from Broadcaster collection to send a message to a specific client.

<i>From  Class (B) How to get BroadcasterFactory factory ?</i>

	Collection<Broadcaster> broadcasters = factory.lookupAll();
    	for (Broadcaster broadcaster : broadcasters) {
    	    String[] p = broadcaster.getID().split("/");
            String d = p.length > 2 ? p[2] : "";
            if (d.equals(client_id)) {
            	return broadcaster;
            }
        };

I tried with suggestion for <a href="https://github.com/Atmosphere/atmosphere/wiki/Getting-BroadcasterFactory-and-AtmosphereResourceFactory-with-2.2-and-newer">Getting BroadcasterFactory and ... - GitHub</a> but without success.

Is there something I missed ?
Could someone help me ?
Thank you

**Comment by jfarcand** [comment]
Please use the mailing list for question https://groups.google.com/group/atmosphere-framework?pli=1
