### ISSUE TITLE
Issue with long-polling and broadcast to a single client

### ISSUE THREAD

**Issue by chico1198** [Atmosphere/atmosphere#2045]
I have noticed that trying to broadcast to a single long-poll session seems to have mixed results. When I use this code, my long-poll client works as I expect, but all clients get the messages, which is undesirable.

private void sendMsg(AtmosphereResource session, String msg) {
      /\* This works correctly with my long-poll client, but broadcasts to everyone, which in undesirable. */
      session.getBroadcaster().broadcast(msg);
}

However, when I attempt to send to only to one client, it works only sporadically, i.e., only a few messages get through.

private void sendMsg(AtmosphereResource session, String msg) {
      /\* Added single 'session' as second parameter. */
      session.getBroadcaster().broadcast(msg, session);
}

Any ideas why? Please note, I am using the @ManagedService annotation, so, as I understand, broadcast caching should be on-and-working. Also, the second code block works fine with web-socket clients.

Thanks,

Chris

**Comment by jfarcand** [comment]
@chico1198 Please share a complete test case with the Atmosphere's version you are using. Make sure you are using the latest version of `2.2.x` or `2.3.x` as the where a fix made recently in this area.

**Comment by chico1198** [comment]
I am using version 2.4.0-RC4.

The test case involves multiple, independent tasks running on the server and reporting back status to separate clients. Each task reports back periodically and then Atmosphere relays this status back to a respective client. This is the call, using the default broadcaster, that I use to relay this status:

private void sendMsg(AtmosphereResource session, String msg) {
/* Added single 'session' as second parameter. */
session.getBroadcaster().broadcast(msg, session);
}

The failure comes when using long-polling. Here the application only works with a single client and only if the single client broadcasts to all clients (although there is only one) on the default broadcaster, like this:

private void sendMsg(AtmosphereResource session, String msg) {
/* This works correctly with my long-poll client, but broadcasts to everyone, which in undesirable. */
session.getBroadcaster().broadcast(msg);
}

As noted, I want each channel to work independently.

One experiment that I tried was to create separate broadcasters for each task/client pair, using the onOpen call to create and associate a resource with a session on first use. 

    public void onOpen(AtmosphereResource session) {
        LOG.info("Connection opened ...");
        LOG.info("BroadcasterFactory used {}", factory.getClass().getName());
        if(sessions.get(session) == null) {
            LOG.info("New broadcaster being created for browser {}", session.uuid());
            Broadcaster b = factory.get(session.uuid());
            b.addAtmosphereResource(session);
            sessions.put(session, new TaskConnector(b));
        } else {
            LOG.info("Re-using broadcaster previously created for browser {}", session.uuid());
        }
    }

This does not seem to have the desired effect as the broadcaster seems to lose connection to the client after the first message. 

Again, any assistance would be appreciated.

**Comment by jfarcand** [comment]
@chico1198 Ok I will need a test case to reproduce :-) Thanks

**Comment by jfarcand** [comment]
@chico1198 One thing you can do is run with the log level set to TRACE and post it here. You can correlate the client's uuid with the message that get lost. That will help debugging. Thanks

**Comment by jfarcand** [comment]
@chico1198 Any update?
