### ISSUE TITLE
Typecast error in AtmosphereFramework.defaultInterceptors()

### ISSUE THREAD

**Issue by manikantag** [Atmosphere/atmosphere#2046]
Hi,

org.atmosphere.cpr.AtmosphereFramework.defaultInterceptors() is throwing `ClassCastException` at https://github.com/Atmosphere/atmosphere/blob/atmosphere-project-2.3.4/modules/cpr/src/main/java/org/atmosphere/cpr/AtmosphereFramework.java#L3194

    Caused by: java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Ljava.lang.Class;
        	at org.atmosphere.cpr.AtmosphereFramework.defaultInterceptors(AtmosphereFramework.java:3194)

Shouldn't it be 

	public Class<? extends AtmosphereInterceptor>[] defaultInterceptors() {
	    return (Class<? extends AtmosphereInterceptor>[]) DEFAULT_ATMOSPHERE_INTERCEPTORS.toArray(new Class[0]);
	}

**Mind the `.toArray(new Class[0])`**

**Comment by jfarcand** [comment]
@manikantag Any test for that exception or describe how to reproduce it?

**Comment by manikantag** [comment]
I just took the code directly from https://github.com/Atmosphere/atmosphere/wiki/Configuring-Atmosphere-as-a-Spring-Bean. 

    @Bean
    public AtmosphereFramework atmosphereFramework() throws ServletException, InstantiationException, IllegalAccessException {
        ...
        for (Class<? extends AtmosphereInterceptor> a : atmosphereFramework.defaultInterceptors()) {
            interceptors.add(a.newInstance());
        }
        ...
    }

**Comment by jfarcand** [comment]
OK so the bug is in that code
```java
        List<? extends AtmosphereInterceptor> interceptors = new ArrayList<>();
        for (Class<? extends AtmosphereInterceptor> a : atmosphereFramework.defaultInterceptors()) {
            interceptors.add(a.newInstance());
        }
```

**Comment by manikantag** [comment]
But https://github.com/Atmosphere/atmosphere/blob/atmosphere-project-2.3.4/modules/cpr/src/main/java/org/atmosphere/cpr/AtmosphereFramework.java#L3194 aslo typecasts to `Class<? extends AtmosphereInterceptor>[]`. 

Quoting from source: 

    public Class<? extends AtmosphereInterceptor>[] defaultInterceptors() {
        return (Class<? extends AtmosphereInterceptor>[]) DEFAULT_ATMOSPHERE_INTERCEPTORS.toArray();
    }

**Comment by jfarcand** [comment]
The code is wrong. You need
```java
        List<? extends AtmosphereInterceptor> interceptors = new ArrayList<>();
```

**Comment by manikantag** [comment]
Hmmm, but I m getting below error with above code:

		List<? extends AtmosphereInterceptor> interceptors = new ArrayList<>();
		for (Class<? extends AtmosphereInterceptor> a : atmosphereFramework.defaultInterceptors()) {
			interceptors.add(a.newInstance()); // ERROR HERE
		}

Error: 

    The method add(capture#1-of ? extends AtmosphereInterceptor) in the type List<capture#1-of ? extends AtmosphereInterceptor> is not applicable for the arguments (capture#2-of ? extends AtmosphereInterceptor)

**Comment by jfarcand** [comment]
Ok try `2.3.5-SNAPSHOT`

**Comment by jfarcand** [comment]
git checkout

**Comment by lewie** [comment]
Hi,
have exactly same problem:
````
The method add(capture#1-of ? extends AtmosphereInterceptor) in the type List<capture#1-of ? extends AtmosphereInterceptor> is not applicable for the arguments (capture#2-of ? extends AtmosphereInterceptor)
````
with
````
		<dependency>
    		<groupId>org.atmosphere</groupId>
			<artifactId>atmosphere-spring</artifactId>
    		<version>2.4.0-RC2</version>
		</dependency>
````
Spring Boot v1.3.0.RC1
Java jdk 1.8.0_60

**Comment by jfarcand** [comment]
@lewie Try latest version `2.4.0-RC7`

**Comment by lewie** [comment]
Hi @jfarcand,
Using:
````List<AtmosphereInterceptor> interceptors=new LinkedList<>();````
instead of
````List<? extends AtmosphereInterceptor> interceptors = new ArrayList<>();````
then add can be used:
````
for (Class<? extends AtmosphereInterceptor> a : atmosphereFramework.defaultInterceptors()) {
	interceptors.add(a.newInstance());
}
````
seams to work now.

Should be changed in this example: https://github.com/Atmosphere/atmosphere/wiki/Configuring-Atmosphere-as-a-Spring-Bean

Rgds
Helmut

**Comment by jfarcand** [comment]
@lewie Pull request welcomed ... for the wiki you can edit it. Thanks!
