### ISSUE TITLE
Impossible to connect using the last version of Socket.io-client

### ISSUE THREAD

**Issue by MartinMoizard** [Atmosphere/atmosphere#2047]
I tried connecting a client using socket.io-client (javascript) to my java backend using atmosphere, but I did not manage to make it work. I looks like the latest version of socket.io is not supported

**Comment by jfarcand** [comment]
Please use the mailing list for question. True Socket.io 1.x is not supported, contribution welcomed.

**Comment by MartinMoizard** [comment]
It was more a bug report than a question, but if it's expected fine :) I'd expect a note about it somewhere though.

**Comment by jfarcand** [comment]
@MartinMoizard OK just file an RFE here https://github.com/Atmosphere/atmosphere-extensions/issues. The issue is not filled under the proper project. Thanks!
