### ISSUE TITLE
Broadcaster resending message to @Message

### ISSUE THREAD

**Issue by umbreak** [Atmosphere/atmosphere#2051]
In the server side I have a `ManagedService` and inside the annotation `@Message` I am receiving messages. 

In some cases, I don't want to broadcast the message received to everybody, so I did as documented [here](https://github.com/Atmosphere/atmosphere/wiki/Creating-private-channel-of-communication-between-Browsers). A privat Broadcaster and sending the message to only the desired `AtmosphereResource`. 

	 @org.atmosphere.config.service.Message(encoders = {ConferenceRoomEvent.JacksonEncoder.class}, decoders = {ConferenceRoomEvent.JacksonDecoder.class})
	    public ConferenceRoomEvent onMessage(AtmosphereResource r, ConferenceRoomEvent event) throws IOException {
		System.out.println("Message comming");
		if(event.type == MESSAGE){
			System.out.println("Broadcasting message");
			agentBroadcaster.broadcast(event);
			return null;	
		}
		return event;
	}
With that code, the output sometimes is:

    Message comming
    Broadcasting message
And sometimes

    Message comming
    Broadcasting message
    Message comming
    Broadcasting message

Why sometimes is going 2 times through `onMessage`?

**Comment by jfarcand** [comment]
Please use the mailing list for question...and also please make sure you have a test case as I can't help with just that information, e.g I need the transport used, version, etc.
