### ISSUE TITLE
Report a possible race issue

### ISSUE THREAD

**Issue by baigd** [Atmosphere/atmosphere#2055]
Hi, Developers of Atmosphere/atmosphere,

I am writing to report a race issue on use of ConcurrentHashMap. The issue is reported by our tool in an automatic way. Although manually confirmed, it would be a false positive, given we do not know the specification of the program. We would very appreciate if you could check below for details and confirm with us whether it is a real problem. For more information, please refer to our website: http://sav.sutd.edu.sg/?page_id=2845

File: 
"Atmosphere/atmosphere/modules/cpr/src/main/java/org/atmosphere/websocket/DefaultWebSocketProcessor.java"
Location: Line (295/313, 175)
Description: 
The get-get operation (line 295, 313) in method "postProcessMapping()" is guarded by lock "hadlers". I assume the intention is to guarantee the atomicity of the get-get operations. However, the write operation in line 175 is not properly guarded by any lock. Therefore it may break the atomicity of the get-get operation in method "postProcessMapping()". Relying on the ConcurrentHashMap to ensure exclusive access is dangerous since ConcurrentHashMap has no guarantee of exclusive access.

**Comment by jfarcand** [comment]
The `registerWebSocketHandler` is externally invoked at startup and only one thread can invoke that method at a time (no concurrent deploy). Hence the lock in `postProcessMapping` is enough in that case.  I do agree there is a potential race if and only if concurrent deployment of Atmosphere's components occurs, but that condition cannot happens with the current architecture.
