### ISSUE TITLE
WriteOperation instances climbing

### ISSUE THREAD

**Issue by poi212003** [Atmosphere/atmosphere#2056]
Hi,
I did a heap dump and for some reason the instance count of WriteOperation is climbing, the strange thing is that every instance is already marked as executed and completed.
Is it possible that due to high sent rate, the scheduler executes slower than the rate the tasks are being added?

Is there a way around it? or should I just remove the writeTimeout (use the default -1)? 

I'm using atmoshphere 1.0.13 - I know it's an old version, but I've checked the logic of the write timeout in the latest commit and it's still the same :)

See images attached:
![instancecount](https://cloud.githubusercontent.com/assets/1898309/10044796/3973bb8e-61ed-11e5-83cd-79f79a025ad8.png)
![instancecount1](https://cloud.githubusercontent.com/assets/1898309/10044801/3edb68f6-61ed-11e5-8ccb-1d8bcd41c228.png)

Running on:
Windows server r2 x64 2008 standard
Ram 32GB
Network 1gbps
xeon e3-1230 v3
Apache Tomcat/7.0.62	
java 1.7.0_79-b15

Thanks.
Pavel

**Comment by jfarcand** [comment]
@poi212003 Next time use the mailing list for question :-) Seems you have set the time out to a too high value and the 'ScheduledExecutor` is lagging.
