### ISSUE TITLE
CleanUp IOUtils.guestServletPath and Servlet Path Calculation for Jsr356

### ISSUE THREAD

**Issue by jfarcand** [Atmosphere/atmosphere#2057]
https://github.com/Atmosphere/atmosphere/blob/master/modules/cpr/src/main/java/org/atmosphere/util/IOUtils.java#L245-L268

**Comment by Artur-** [comment]
Does this change intentionally change which servlet is picked if there are multiple mappings or is it by accident? The old code used `...getMappings().iterator().next();`which returns the first match, the new code uses 
```
for (String m : s.getMappings()) {
    servletPath = m;
}
```
i.e. the last match
