### ISSUE TITLE
atmosphere-runtime limits org.eclipse.jetty.continuation imports to version 8

### ISSUE THREAD

**Issue by WouterBanckenACA** [Atmosphere/atmosphere#2058]
The atmosphere-runtime package defines an import-package of org.eclipse.jetty.continuation as follows:
org.eclipse.jetty.continuation;resolution:=optional;version="[7.6,9)",

This limits imports to versions greater or equal than 7.6 and smaller than 9.0.0. However, the code base also seems to work with versions higher than 9.0.0 so the import package can be increased to 

org.eclipse.jetty.continuation;resolution:=optional;version="[7.6,10)",

**Comment by jfarcand** [comment]
@WouterBanckenACA Pull request welcomed. Whcih version are you using of Atmosphere

**Comment by WouterBanckenACA** [comment]
Currently using 2.2.8 so we'd like a 2.2.9 release including this small fix.
I'm creating the pull request as we speak.

**Comment by WouterBanckenACA** [comment]
Pull request at https://github.com/Atmosphere/atmosphere/pull/2059

**Comment by WouterBanckenACA** [comment]
@jfarcand I saw you applied the fix to the 2.3.x branch but not the 2.2.x branch. Is there a reason why it's not included in the 2.2.9 release?

**Comment by WouterBanckenACA** [comment]
The reason we'd like to stay on the 2.2.9 is that some changes in the 2.3.x branch are causing issues for the deployment of our application. For example, the new sun.misc dependency requires changes in our application and we're getting injection issues (AtmosphereConfigInjectable not found) that prevent our application from starting. 

Our application works fine for the 2.2.x branch.

**Comment by jfarcand** [comment]
@elakito , do you have the cycle for releasing 2.2.x ? @WouterBanckenACA it will happens for sure, just don't have the cycle to work on it now.

**Comment by elakito** [comment]
@jfarcand <https://github.com/jfarcand> I think I can do it sometimes this
week.



2015-09-29 15:21 GMT+02:00 Jeanfrancois Arcand <notifications@github.com>:

**Comment by elakito** [comment]
I just almost released 2.2.9 today but noticed during the staging that the fix wasn't included. So I dropped the staged version for now.

As the fix is currently included only in 2.3.x, I will need to first bring the fix to master and then all down to 2.2.x.

**Comment by elakito** [comment]
@WouterBanckenACA 
I just merged the fix everywhere including 2.2.x.
i'll run the release job tomorrow. Let me know if you still find some issue with the current 2.2.9-SNAPSHOT.

**Comment by WouterBanckenACA** [comment]
@elakito I just tested our application against the current 2.2.9-SNAPSHOT and it works fine. Thanks!
