### ISSUE TITLE
org.sonatype.oss oss-parent version 5 does not exists

### ISSUE THREAD

**Issue by eqlbin** [Atmosphere/atmosphere#2061]
Impossible to build atmosphere with 

    <parent>
          <groupId>org.sonatype.oss</groupId>
          <artifactId>oss-parent</artifactId>
          <version>5</version>
    </parent>

...because this version does not exist. 

You can see by clicking on the link: https://oss.sonatype.org/content/repositories/releases/org/sonatype/oss/oss-parent/5/oss-parent-5.pom

I have successfully built atmosphere with version 9.

**Comment by jfarcand** [comment]
Fixed, thanks!
