### ISSUE TITLE
Sending information to Atmosphere's Google Analytics without requesting user

### ISSUE THREAD

**Issue by fmassot** [Atmosphere/atmosphere#2068]
When setting debugging to INFO level, I discovered this log line : 

> DEBUG o.a.util.analytics.HTTPGetMethod - Sending Server's information to Atmosphere's Google Analytics http://www.google-analytics.com/__utm.gif?utmwv=1&utmn=1760768023&utmcs=UTF-8&utmsr=1440x900&utmsc=32-bit&utmul=en-us&utmje=1&utmfl=9.0%20%20r28&utmcr=1&utmdt=jersey2-2.3.5-jetty%2F9.2.10.v20150310&utmhn=clardeur-yanport&utmr=http://async-io.org&utmp=/jersey2/2.3.5/jetty%2F9.2.10.v20150310&utmac=UA-31990725-1&utmcc=__utma%3D'-123998601.1632124519.1445594899382.1445594899382.1445594899382.2%3B%2B__utmb%3D-123998601%3B%2B__utmc%3D-123998601%3B%2B__utmz%3D-123998601.1445594899382.2.2.utmccn%3D(direct)%7Cutmcsr%3D(direct)%7Cutmcmd%3D(none)%3B%2B__utmv%3D-123998601

So you're sending information to your server without requesting the user of your library ???????

First please first ask the user.

Second question, are there other sneaky stuff in atmosphere ?

**Comment by fmassot** [comment]
Typo in my previous comment : the log is in DEBUG level :/

**Comment by jfarcand** [comment]
@fmassot This has been discussed many times and there are property to disable it.
