### ISSUE TITLE
FrameworkConfig.SUPPORT_SESSION is not used

### ISSUE THREAD

**Issue by kumarpch** [Atmosphere/atmosphere#2079]
Hi,

I am using Richfaces 4.2.2 Push component which in turn requires Atmosphere 0.8.5

Class: org.atmosphere.cpr.AsynchronousProcessor 
Method: action
Line: 202
 req.setAttribute(FrameworkConfig.SUPPORT_SESSION, supportSession());

From the source code, I am finding that the value set for FrameworkConfig.SUPPORT_SESSION in HttpServletRequest is not being used anywhere. Is it a defect ? or my incorrect understanding, and in that case please help with info of where/how/why it is being used. I have checked the latest release source code (3.0.0-SNAPSHOT) too but I could not find any references for using FrameworkConfig.SUPPORT_SESSION.

I am setting org.atmosphere.cpr.sessionSupport to false in web.xml (), and in that case it sets attribute FrameworkConfig.SUPPORT_SESSION as false. I am not sure if having false effects any scenarios (such as cluster or non-cluster web server setup etc)

Thank you very much

Kumar

**Comment by jfarcand** [comment]
Atmospjere 0.8 is not supported...upgrade to 2.3.5!

**Comment by kumarpch** [comment]
Well, unfortunately we are at the end of our release cycle and therefore upgrade of RichFaces and then atmosphere is really not an option we have got. Thank you for your response.  As I had mentioned, I have checked the latest 2.3.5 code too, and finding that the value set for FrameworkConfig.SUPPORT_SESSION in HttpServletRequest is not being used anywhere. Could you please confirm if that is indeed the case, and any issue you foresee setting  FrameworkConfig.SUPPORT_SESSION to false. Thank you in advance.

**Comment by jfarcand** [comment]
This variable is for Framework integrator and an application shouldn't use it.

**Comment by kumarpch** [comment]
I am setting context-param org.atmosphere.cpr.sessionSupport to false in my web.xml. This in turn sets attribute FrameworkConfig.SUPPORT_SESSION as false in Atmosphere code (AsynchronousProcessor).  From your response, I am taking no issues with this approach. It will be very helpful if you may please confirm. Thanks very much again. We will certainly upgrade to latest 2.3.5 with our next release.
