### ISSUE TITLE
Websocket reconnect fails when disconnecting network

### ISSUE THREAD

**Issue by jdahlstrom** [Atmosphere/atmosphere#2082]
1. Open atmosphere-chat with Chrome
2. Kill network connection (disable Wi-Fi or unplug Ethernet)
3. Re-enable network connection
4. App will try to reconnect with websocket but fallback to Comet

With Firefox the websocket connection is not lost (difference in onoffline handling?)

Vaadin ticket: https://dev.vaadin.com/ticket/19201

**Comment by jfarcand** [comment]
@jdahlstrom wrong project -> https://github.com/Atmosphere/atmosphere-javascript
