### ISSUE TITLE
Setup with jetty, jersey and guice

### ISSUE THREAD

**Issue by anthonycorbacho** [Atmosphere/atmosphere#2085]
Bonjour~

I am trying to build an app with jetty, jersey and juice that mix rest api and websocket.

I have done the rest api part and its working just fine.
But I am facing some difficulty with Atmosphere.
I keep getting an error about The Atmosphere Framework is not installed properly and unexpected result may occurs.
And to be honest I have no idea why :(

I have created a gist with the code of server, guice, Atmosphere and the full log stack: https://gist.github.com/anthonycorbacho/0622cf2c0550dcec2cc4

If someone can point out where i need to change stuffs i would really appreciate it.
Thank you.

**Comment by jfarcand** [comment]
Use mailing list for question.
