### ISSUE TITLE
CDIObjectFactory IllegalStateException

### ISSUE THREAD

**Issue by kalos9173** [Atmosphere/atmosphere#2092]
CDIObjectFactory raises an exception at line 61:  BeanManager cannot find CDIProducer implementation bean.

How the AtmosphereProducers can be used ?

Atmosphere 2.4.0 + CDI module + WELD + Primefaces 5.3

**Comment by kalos9173** [comment]
anyone ?

**Comment by jfarcand** [comment]
@kalos9173 Stil having with the latest version?
