### ISSUE TITLE
I get "undefined" when i send a message

### ISSUE THREAD

**Issue by Chiuccolo** [Atmosphere/atmosphere#2099]
Hi!

recently i starting developing with Atmosphere for developeng a chat.
I try the sample at this link: 
https://github.com/Atmosphere/atmosphere/wiki/Getting-Started-with-AtmosphereHandler,-WebSocket-and-Long-Polling
but when i start to chat i get as output "undefined" instead of myu message..What i have forget? Where i miss/wrong something?

Here my web.xml:

	<display-name>SuitCase</display-name>
	<servlet>
        <description>AtmosphereServlet</description>
        <servlet-name>AtmosphereServlet</servlet-name>
        <servlet-class>org.atmosphere.cpr.AtmosphereServlet</servlet-class>
		<init-param>
            <param-name>org.atmosphere.cpr.packages</param-name>
            <param-value>com.gpi.suitecase.service</param-value>
        </init-param>

        <init-param>
            <param-name>org.atmosphere.interceptor.HeartbeatInterceptor.clientHeartbeatFrequencyInSeconds</param-name>
            <param-value>10</param-value>
        </init-param>
        <load-on-startup>0</load-on-startup>
		<async-supported>true</async-supported>
    </servlet>
	<servlet-mapping>
        <servlet-name>AtmosphereServlet</servlet-name>
		<url-pattern>/chat/*</url-pattern>
    </servlet-mapping>

and this are the jars that iuse to develop the sample:
- atmosphere-annotations-2.4.0.jar
- jackson-databind-2.4.1.3.jar
- jackson-core-2.4.1.1.jar
- jackson-annotations-2.4.1.jar
- atmosphere-runtime-2.4.0.jar
- slf4j-api-1.6.1.jar

![chat](https://cloud.githubusercontent.com/assets/16049347/11445417/26ae61f8-952c-11e5-8b6f-e55b24f3e40c.PNG)

thanks

**Comment by elakito** [comment]
what is different from the original samples/chat of atmosphere-samples?
and you have the same problem with the original sample?

**Comment by elakito** [comment]
this problem was caused likely by the old typo in the switch block of the sample code, which was corrected some time ago.
if the problem still persists, please reopen this ticket.
