### ISSUE TITLE
[Dropwizard 0.9.x] atmosphere-jersey JResponse classpath dependency Issue

### ISSUE THREAD

**Issue by crudbug** [Atmosphere/atmosphere#2108]
I am using Dropwizard 0.9.x which supports latest version of jersey.

```
<dependency>
            <groupId>org.glassfish.jersey.core</groupId>
            <artifactId>jersey-server</artifactId>
  </dependency>
 <dependency>
            <groupId>org.glassfish.jersey.containers</groupId>
            <artifactId>jersey-container-servlet</artifactId>
  </dependency>
```

But, atmosphere uses older version of jersey implementation with com.sun.jersey.api.JResponse class, which is not available in the latest jersey version. 

```
<dependency>
            <groupId>com.sun.jersey</groupId>
            <artifactId>jersey-server</artifactId>
            <version>${jersey-version}</version>
 </dependency>
 <dependency>
            <groupId>com.sun.jersey</groupId>
            <artifactId>jersey-servlet</artifactId>
            <version>${jersey-version}</version>
   </dependency>
```

Is there a plan to upgrade the jersey version ?

**Comment by gicappa** [comment]
Having the same issue here. Any plan to solve it? the jersey 1.19 version is very old!

**Comment by jfarcand** [comment]
As stated many time on the mailing list, Atmosphere won't supports natively Jersey 2 unless someone write the `glue` code. Jersey 2 can still be used via the `@AtmosphereService` annotation. Check the https://github.com/Atmosphere/atmosphere-samples/tree/master/samples/jersey2-chat for an example.
