### ISSUE TITLE
Update Latest version of Atmosphere's JavaScript Client 

### ISSUE THREAD

**Issue by confile** [Atmosphere/atmosphere#2113]
The following line points on an old version of the atmosphere js client: 

https://github.com/Atmosphere/atmosphere/blob/master/modules/cpr/src/main/java/org/atmosphere/cpr/AtmosphereFramework.java#L1153

It must be 

```
String clientVersion = "2.3.1";
```

**Comment by confile** [comment]
See: https://github.com/Atmosphere/atmosphere/pull/2114

**Comment by elakito** [comment]
actually the version value should be 2.3.0.
but as it is more work to maintain this constant in the code, i think we should just remove this constant and only print out this log line when the version number is retrieved from the async.o's registry.

**Comment by elakito** [comment]
closing this ticket as the latest version info is no longer hardcoded in the code.
https://github.com/Atmosphere/atmosphere/commit/31d6d000b8b69690d5fa39fafa6fad2f5354e7aa
