### ISSUE TITLE
UUIDBroadcasterCache not working on reconnect

### ISSUE THREAD

**Issue by bcoble** [Atmosphere/atmosphere#2117]
I am using the @ManagedService annotation to quickly utilize Atmosphere in our application. The only bit of custom atmosphere code below. The connection resumes correctly on a reconnect and can get/send messages, but any messages that occurred while the network is down are not sent on reconnect. I am using Atmosphere-Spring 2.3.1. This issue shows up in both websocket and long polling protocols, as well as on both Tomcat and Websphere. I'm not sure if this is a bug or if I'm doing something wrong. I've read through the wiki's and I believe the UUIDBroadcasterCache should be enabled by default. I've stepped through the code and noticed messages sent when one connection is offline do get stored in the cache but they do not seem to be retrieved and distributed on reconnection. Any pointers to go about locating the problem would be greatly appreciated.

``` Java
package com.company.project.product.async;

import com.company.project.product.conf.AtmosphereConstants;
import com.company.project.product.model.EngineVariable;
import com.company.project.product.model.VariableUpdatedMessage;
import com.company.project.product.service.CustomRuntimeService;
import com.company.project.product.service.ServiceException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.atmosphere.cache.UUIDBroadcasterCache;
import org.atmosphere.config.service.*;
import org.atmosphere.cpr.AtmosphereResource;
import org.atmosphere.cpr.AtmosphereResourceEvent;
import org.atmosphere.cpr.AtmosphereResourceFactory;
import org.atmosphere.cpr.Broadcaster;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;

import java.io.IOException;

/**
 * The path denotes:
 * tenantId - usually a company id
 * parentId - usually an instance Id
 * childId - usually a task id.
 */
@ManagedService(path = AtmosphereConstants.VARIABLE_UPDATE_PIPELINE)
public class VariablePipeline {

    private static final Logger logger = LoggerFactory.getLogger(VariablePipeline.class);

    @Autowired
   CustomRuntimeService runtimeService;

    @Autowired
    ObjectMapper mapper;

    @Ready
    public void onReady(AtmosphereResource resource) {
        logger.info("The resource " + resource.uuid() + " is connected.");
    }

    @Message(encoders = {JacksonEncoder.class})
    public EngineVariable variableUpdated(VariableUpdatedMessage message) throws ServiceException {
        logger.debug("Variable named " + message.getVariableName() + " updated");
        if (message.hasChildId()) {
            return runtimeService.getVariableFromTask(message.getChildId(), "global", message.getVariableName());
        }
        return runtimeService.getVariableFromInstance(message.getParentId(), "global", message.getVariableName());
    }
}
```

**Comment by saikiran939** [comment]
Messages will be cleared from broadcaster cache if the server thinks the status of atmosphere resource is valid. If you're working on tomcat it takes few seconds to identify that the suspended resource is not valid anymore. Then the messages will be stored in cache, so there is slight gap between the disconnection of client and server identification of invalid resource (this usually happens JSR356Endpoint.onError() is invoked) - and hence during this gap messages will be lost.

You may have to revisit - ApplicationConfig.SESSION_MAX_INACTIVE_INTERVAL setting in websphere so that connection will be closed from server side if the client has disconnected.
