### ISSUE TITLE
Possibly wrong (outdated?) package declaration in org.atmosphere.util.annotation.AnnotationDetector

### ISSUE THREAD

**Issue by radzionkow** [Atmosphere/atmosphere#2123]
Hi,

In AnnotationDetector class, when using VFS, class is loaded by:
`Class<?> vfs = c.loadClass("org.jboss.virtual.VFS");`
It seems that in newer versions of jboss-vfs library package declaration changed to:
`org.jboss.vfs.VFS`
Confirmed on wildfly-8.2.0.Final
It's preventing to read some annotated classes, especialy when using ear deployment.

**Comment by jfarcand** [comment]
@radzionkow Contribution welcomed....but for backward compat, we can't change the current package.
