### ISSUE TITLE
Reasource Leak - Waiting Threads with AJP/NIO / Duplicate reasource message

### ISSUE THREAD

**Issue by skasten** [Atmosphere/atmosphere#2125]
Hello,

we experience some problems with a PrimeFaces application using PrimePush and therefor Atmosphere. After some time of using the portal it seems to lock, like it has a resource leak.

After some investigation I found out, that there are > 150 ajp-nio-8009-exec-... Threads open. Most on a WAITING state.
The last usage of atmosphere in the stack trace is org.atmosphere.container.BlockingIOCometSupport.suspend(BlockingIOCometSupport.java:147).

In https://github.com/Atmosphere/atmosphere/issues/1028 it is stated, that this happens when using BIO with Atmospere. But at least we are not using BIO, which is also named in the thread names itself: ajp-**NIO**-8009-exec...

Also I have to mention, that the threads seem to open, when atmosphere logs "_Duplicate resource 1c20fc51-dac8-4074-8adc-85314d26048f. Could be caused by a dead connection not detected by your server. Replacing the old one with the fresh one_". (See https://github.com/Atmosphere/atmosphere/issues/2052)

**Our setup**:
- Apache2 2.2.22 (Debian) with mod_proxy_ajp, SSL terminated there;
- Tomcat 7.0.67 (also with 7.0.61) without any connector then the AJP one. (Protocol: org.apache.coyote.ajp.AjpNioProtocol)
- The application uses multiple p:socket in one view, because we need to listen on different channels at the same time (PrimeFace 5.1, Atmosphere 2.3.5).

If this is not a bug, but a configuration issue, please tell me what to change.

Best regards,
skasten

**Comment by skasten** [comment]
I have removed the Apache 2 Proxy before the Tomcat and tested again. Now it seems to cleanup correctly, even with the "Duplicate resource ..." messages. We use the Http11NioProtocol on plain and SSL.

**Comment by anantagarwal** [comment]
Hi Skasten, were u able to solve this issue with Apache 2 proxy?

**Comment by skasten** [comment]
Hi,
sorry, we simply moved the portal to another host, without the Apache2 configuration before. So I cannot state, if it is fixed now.

**Comment by anantagarwal** [comment]
I guess this issue has been fixed in Tomcat 7.0.70. 
https://bz.apache.org/bugzilla/show_bug.cgi?id=58970
