### ISSUE TITLE
Storing session in AtmosphereResource does not work with clustered sessions

### ISSUE THREAD

**Issue by bpapez** [Atmosphere/atmosphere#2133]
We are currently evaluating to save/load session data via external store, so that we can provide fallback support by switching to other cluster nodes and continue to use the same session. By using solutions like https://github.com/jcoleman/tomcat-redis-session-manager or https://docs.spring.io/spring-session/docs/current-SNAPSHOT/reference/html5/ we found that on each request a new HttpSession instance is being created. 

This way storing a reference of the session in AtmosphereResourceImpl is not good (reason to store the session was to fix #431 - we indeed still get problems in the HeartbeatInterceptor, because Tomcat request objects get recycled and reused by other request, so we also have a custom patch in the HeartbeatInterceptor to prevent corrupted responses). The problem is that for instance on disconnect the session passed with the event in a method annotated with org.atmosphere.config.service.Disconnect will not get a session with all the latest properties. To workaround that I made a fix in our for in the OnDisconnectInterceptor.inspect by adding

```
            // Work around the problem that session instances are recreated on every request when loaded from an external store
            HttpSession session = r.session(false);
            if (session != null) {
                AtmosphereResourceImpl.class.cast(ss).session(session);
            }
```

**Comment by jfarcand** [comment]
@bpapez Can you make a pull request with your fix?
