### ISSUE TITLE
Fix sources.jar artifact generation for sub-project atmosphere-runtime-native

### ISSUE THREAD

**Issue by dmaidaniuk** [Atmosphere/atmosphere#2135]
Currently sub-project `atmosphere-runtime-native` have almost same code base as parent `atmosphere-runtime`. But sources.jar generated without inclusion of classes and other sources from parent project. As a result such JAR file is useless for debugging purposes. Developer need for each new version repack correct sources.jar to be able debug Atmosphere classes.
Please fix sources.jar file for sub-project `atmosphere-runtime-native` in Sonatype repository.

**Comment by jfarcand** [comment]
@dmaidaniuk Contribution welcomed...it has been like that for years :-)

**Comment by dmaidaniuk** [comment]
@jfarcand OK, I'll try prepare fix for this issue. :)

**Comment by jfarcand** [comment]
@dmaidaniuk ping :-)

**Comment by dmaidaniuk** [comment]
Yep, I'm here. :) I will try to prepare pull request in new few days.

**Comment by dmaidaniuk** [comment]
Hi @jfarcand , I just pushed fix for given issue. Please review my pull request.

**Comment by dmaidaniuk** [comment]
Changes merged in master branch. Issue closed. Thanks @jfarcand !
