### ISSUE TITLE
NullPointerException while loading the servlet class

### ISSUE THREAD

**Issue by martin-g** [Atmosphere/atmosphere#2140]
I'm experiencing the following NPE while trying to start an application with Atmosphere 2.4.3 at Tomcat 8.0.17:

```
java.lang.NullPointerException
	org.atmosphere.handler.ReflectorServletProcessor.loadServlet(ReflectorServletProcessor.java:104)
	org.atmosphere.handler.ReflectorServletProcessor.loadWebApplication(ReflectorServletProcessor.java:84)
	org.atmosphere.handler.ReflectorServletProcessor.init(ReflectorServletProcessor.java:172)
	org.atmosphere.cpr.AtmosphereFramework.initAtmosphereHandler(AtmosphereFramework.java:1732)
	org.atmosphere.cpr.AtmosphereFramework.initAtmosphereHandler(AtmosphereFramework.java:1721)
	org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:917)
	org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:838)
	org.atmosphere.cpr.AtmosphereFrameworkInitializer.configureFramework(AtmosphereFrameworkInitializer.java:75)
	org.atmosphere.cpr.AtmosphereServlet.configureFramework(AtmosphereServlet.java:84)
	org.atmosphere.cpr.AtmosphereServlet.configureFramework(AtmosphereServlet.java:80)
	org.atmosphere.cpr.AtmosphereServlet.init(AtmosphereServlet.java:75)
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516)
	org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086)
	org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659)
	org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.lang.Thread.run(Thread.java:745)
```

The code of the application is at https://github.com/apache/wicket/blob/ad994436d859849b964957a4ffa9690129ba2a88/wicket-examples/.
atmosphere.xml is at https://github.com/apache/wicket/blob/ad994436d859849b964957a4ffa9690129ba2a88/wicket-examples/src/main/webapp/META-INF/atmosphere.xml.
To create the .war file you can clone the Git repo, `mvn package` and find it at `wicket-examples/target/wicket-examples.war`.
If this is not working for some reason then you can download it from https://www.dropbox.com/s/f5fwpe59hxmir06/wicket-examples.war?dl=0

I don't know much about Atmosphere but let me know if you have questions.

**Comment by elakito** [comment]
OK. it looks like we need a NPE guard there.

@martin-g what is the target servlet you are proxing to using atmosphere?
your atmosphere.xml doesn't set servletClassName
see
https://github.com/Atmosphere/atmosphere-samples/blob/master/samples/all-api-pubsub/src/main/webapp/META-INF/atmosphere.xml#L6

**Comment by martin-g** [comment]
@elakito Is servlet/servletClassName a new requirement ?
I'm not a user of Atmosphere. I just try to apply a Pull Request to upgrade Atmosphere from 2.2.x to 2.4.x for Apache Wicket.
In our demo application we setup AtmosphereServlet at https://github.com/apache/wicket/blob/76f289cc7a66c54640eb4296f964d717aa4e6197/wicket-examples/src/main/webapp/WEB-INF/web.xml#L869
Is this helpful or I should dig further ?

**Comment by elakito** [comment]
@martin-g this is not about AtmosphereServlet but about your target servlet that you specified using atmosphere.xml to be invoked over atmosphere's ReflectorServletProcessor. I see the logger.info has changed between 2.2.x. and a later release.
2.2.x.
https://github.com/Atmosphere/atmosphere/blob/atmosphere-2.2.x/modules/cpr/src/main/java/org/atmosphere/handler/ReflectorServletProcessor.java#L103

103 logger.info("Installing Servlet {}", servletClassName);

where as previously in 2.4.x
https://github.com/Atmosphere/atmosphere/blob/010ad7416cdd4c82c9531398acab7e5c56e6083d/modules/cpr/src/main/java/org/atmosphere/handler/ReflectorServletProcessor.java#L104

104 logger.info("Installing Servlet {}", servletClassName == null ? servlet.getClass().getName() : servletClassName);

so when the ReflectorServletProcessor is not configured correctly and the servlet is not loaded, that will still be ignored in 2.2.x but lead to an NPE in the above logger line. 

the current 2.4.x has the NPE guard.
https://github.com/Atmosphere/atmosphere/blob/faff68fba350a0aa1f97be6804e43f7f8f9ffaad/modules/cpr/src/main/java/org/atmosphere/handler/ReflectorServletProcessor.java#L103-L108

103        if (servlet != null) {
104           logger.info("Installing Servlet {}", servletClassName == null ? servlet.getClass().getName() : servletClassName);
105        } else {
106            // for now, not throw an exception, just in case if someone may call setServlet at later time
107            logger.warn("No servlet installed. Neither servlet nor servletClassName is set");
108       }

maybe your use-case falls into this else-block case?

regards, aki

**Comment by martin-g** [comment]
Yes, it looks like.
IMO the warn log message could be improved a bit and explain why this servlet is needed. Or link to some wiki page.
I have no idea what I could improve in my application by reading this message.
And should it be a WARN if Atmosphere could work without it ?
Thanks for your help!

**Comment by elakito** [comment]
@martin-g usually, it should not be working if the servlet is not set because the purpose of ReflectorServletProcessor is to internally forward the requests to the specified servlet. So, the servlet is not specified, this should lead to some error later when the requests are forwarded. 

I don't know whether you are setting the servlet at a later time before the requests are coming in or you don't need explicitly configure ReflectorServletProcessor in your use-case? In the latter case, you can just remove atmosphere.xml.

**Comment by martin-g** [comment]
Wicket-Atmosphere integration uses Atmosphere Meteor (https://github.com/apache/wicket/blob/e1661fe61d15c19975af17ab9eabfaa8831c2633/wicket-experimental/wicket-atmosphere/src/main/java/org/apache/wicket/atmosphere/AtmosphereBehavior.java#L109-L112).
Does this helps you anyhow ?

**Comment by elakito** [comment]
maybe, you use case is using the RequestDispatcher to find the default target. In that case, it is working without the servlet being explicitly set in ReflectorServletProcessor.
https://github.com/Atmosphere/atmosphere/blob/master/modules/cpr/src/main/java/org/atmosphere/util/AtmosphereFilterChain.java#L134-L142

I'll switch logger.warn to logger.info to the earlier patch shortly.

**Comment by martin-g** [comment]
Great, thanks!
Do you have -SNAPSHOT builds somewhere so I can test before you release 2.4.4 ?

**Comment by elakito** [comment]
we have yesterday's 2.4.4-SNAPSHOT version at the sonatype snapshot repo:

https://oss.sonatype.org/content/repositories/snapshots/org/atmosphere/atmosphere-runtime/2.4.4-SNAPSHOT/

that means, this one still has the logger.warn instead of logger.info, but other than that, it is identical to today's version, so you can use it for testing.

thanks.
regard, aki

**Comment by martin-g** [comment]
This issue is solved!
Opened #2142 for a new one.
