### ISSUE TITLE
Heartbeat frequency reported incorrectly in the log

### ISSUE THREAD

**Issue by Talon876** [Atmosphere/atmosphere#2144]
The HeartbeatInterceptor logs the client and server heartbeats with the values swapped.

I have `org.atmosphere.interceptor.HeartbeatInterceptor.heartbeatFrequencyInSeconds` set to 120 and `org.atmosphere.interceptor.HeartbeatInterceptor.clientHeartbeatFrequencyInSeconds` set to 60. With this configuration the log prints out `HeartbeatInterceptor configured with padding value 'X', client frequency 120 seconds and server frequency 60 seconds`

**Comment by saikiran939** [comment]
Yup, I think this is a tiny bug in info logger statement used in org.atmosphere.interceptor.HeartbeatInterceptor.configure(AtmosphereConfig) method. I will submit a pull request for this.

**Comment by jfarcand** [comment]
@saikiran939 Go!
