### ISSUE TITLE
Session Not Closed after inactive timeout limit

### ISSUE THREAD

**Issue by mkrsanac** [Atmosphere/atmosphere#2145]
Hi,

We have an application deployed on weblogic 10.3.4 which is using atmosphere-runtime-2.3.5 with long-polling, the applications is configured to use the native support for weblogic(by the AtmosphereWebLogicServlet - atmosphere-weblogic-2.3.2).Sessions on weblogic are not closed even when the browser is closed, this scenario produce an outofmemory, we are connecting directly to the application(no proxy in front). Also I tested de chat sample and the symptoms is the same, additional I see all sockets on CLOSE_WAIT state

thank you in advance,

Matías

**Comment by jfarcand** [comment]
Please use the mailing list for question, or at least upload a sample that demonstrate the issue on Github.
