### ISSUE TITLE
Unsubscribing from channel subscribes another resource in postInterceptors

### ISSUE THREAD

**Issue by jaltman7** [Atmosphere/atmosphere#2146]
When disconnecting in AsynchronouseProcessor.action() the Action a returned from invokeInterceptors 
has a type() of Action.TYPE.CANCELLED.  This causes the method to return, but since the call to postInterceptors is in a finally block it gets called anyway which then subscribes a new resource from the AtmosphereResourceLifecycleInterceptor.postInspect() leaving clients subscribed to channels.  In version 2.3.2 postInterceptors is not in the finally block and this issue does not occur.

**Comment by jfarcand** [comment]
Take a look at `https://github.com/Atmosphere/atmosphere/blob/c7e675b97db56f10fc3b8357a217f7e2c9b4ed56/modules/cpr/src/main/java/org/atmosphere/interceptor/AtmosphereResourceLifecycleInterceptor.java#L140-L140`, it does do the check

**Comment by jaltman7** [comment]
Ahh I see.  So where does the Action get set on the AtmosphereResource?  I see that the OnDisconnectInterceptor calls isClosedByClient(true), but that doesn't seem to get checked in the AtmosphereResourceLifecycleInterceptor, and the Action just seems to get returned.
