### ISSUE TITLE
Cookies not passed during upgrade with JSR356 implementations

### ISSUE THREAD

**Issue by jaltman7** [Atmosphere/atmosphere#2147]
When using JSR356 Implementations cookies are not available in the AtmosphereRequest.  This seems to be related to #485 since request.getHeader("cookie")[jetty] or request.getHeader("Cookie")[tomcat] does seem to have the cookies as a string.

**Comment by elakito** [comment]
https://groups.google.com/forum/#!topic/atmosphere-framework/qbicJoaKmpU
the fix is one the way.

**Comment by elakito** [comment]
@jfarcand as discussed, I added the Cookie decoding code in atmosphere's CookieUtil with some modification to the original code.

@jaltman7 the fix is in master and 2.4.x.

**Comment by jfarcand** [comment]
@elakito Great work!!!
