### ISSUE TITLE
AtmosphereResourceLifecycleInterceptor does not appear to work as advertised.

### ISSUE THREAD

**Issue by bb-work** [Atmosphere/atmosphere#2153]
I have an application where the server has multiple 'channels', each with its own Broadcaster.  The client chooses which channel(s) to subscribe to, and then recieves data from the desired channel(s).  It works great with websockets, but when I force the transport to long-polling, everything falls apart. Even though I include AtmosphereResourceLifecycleInterceptor, I get a warning that "Atmosphere Resource xxxx is not suspended..."  I thought the interceptor was supposed to take care of that for me.

Everything works fine with websockets, with or without the interceptor.

My application is a SpringBoot application, using Atmosphere-runtime 2.4.3 and atmosphere-spring 2.4.2 (the latest version I was able to find).  I'm able to use long-polling with the springboot chat example, but not with my application (or a very stripped down version).  

I've tried manually suspending and resuming, but then I start seeing problems where it recreates the resource every time I access it, losing the subscription info.

**Comment by jfarcand** [comment]
Please submit a full github sample or use a sample to demonstrate the issue.

**Comment by bb-work** [comment]
I took the chat sample and modified it as follows:
The client sends a subscribe request, which associates it with a broadcaster.
The server broadcasts messages that come in from an external source.

Works fine with Websockets, does not work when it falls back to long-polling or when transport is explicitly set to long-polling.

**Comment by jfarcand** [comment]
@bb-work Post the sample on Github :-)

**Comment by bb-work** [comment]
I would love to, but the external source is a local RabbitMQ exchange.  When I have time to modify it to something you can run, I will.
