### ISSUE TITLE
Tomcat 8.5

### ISSUE THREAD

**Issue by phansson** [Atmosphere/atmosphere#2156]
Tomcat team is getting ready to release final version of Tomcat 8.5.
This is a backport of certain features from Tomcat 9 (which is awaiting some JSRs to be final so won't be released any time soon). As far as I can tell v8.5 will be the new mainline version of Tomcat.

Most notably with relevance for Atmosphere is that Tomcat 8.5 (and the forthcoming 9.x) **drops native support for comet**.

For this reason I believe Tomcat 8.5 deserves a line of its own in [Supported Web Servers and Browsers page](https://github.com/Atmosphere/atmosphere/wiki/Supported-WebServers-and-Browsers). Will it work with Athmosphere, and if so what features will be supported ?

Here's the text of the announcement of the v8.5 beta on 2016-03-24 : 

> The Apache Tomcat Project is proud to announce the release of version 8.5.0 of Apache Tomcat. Apache Tomcat 8.5.0 is intended to replace 8.0.x and includes new features pulled forward from Tomcat 9.0.x. The minimum Java version and implemented specification versions remain unchanged. The notable changes compared to 8.0.x include:
> 
> * Added support for HTTP/2, and TLS virtual hosting
> * Added support for JASPIC 1.1
> * The BIO connectors, support for Windows Itanium and _support for Comet have been removed_
> 
> Full details of these changes, and all the other changes, are available in the Tomcat 8.5 changelog.

**Comment by elakito** [comment]
thanks for the info. I just updated the page for now. 
i keep this ticket open until testing atmosphere against 8.5.

**Comment by jfarcand** [comment]
Atmosphere will works as it is because jsr356 is the default Comet Support, same as Tomcat 8.

**Comment by elakito** [comment]
@jfarcand thanks. tried some samples and all fine.

**Comment by eugenegoncharuk** [comment]
Seems there are problems, when using LP + Tomcat 8.5. Some messages are not getting to the recipient. But with Tomcat 7 it's working.

**Comment by phansson** [comment]
@eugenegoncharuk. If you feel there are problems with Tomcat 8.5 and Atmosphere then you should open a bug report about the specific problem you are seeing, rather than just throwing in a random comment on an unrelated bug report. This bug report was about Tomcat 8.5 not being mentioned in Atmosphere official docs.
