### ISSUE TITLE
The session from the original message is lost when using Jetty 9.3's native websocket

### ISSUE THREAD

**Issue by elakito** [Atmosphere/atmosphere#2157]
this issue was reported by Artur and demonstrated with
https://github.com/Artur-/atmosphere-samples/commit/5091ffbdeb992904239ca483d8ce2a1cfcfc2478

**Comment by Artur-** [comment]
Awesome, all our tests now pass on Jetty 8, 9.2, 9.3!

**Comment by elakito** [comment]
@Artur- thanks for verifying!

**Comment by jfarcand** [comment]
Great work @elakito !!!!!!
