### ISSUE TITLE
Add an interceptor to handle jaxrs calls over various transport protocols

### ISSUE THREAD

**Issue by elakito** [Atmosphere/atmosphere#2160]
Adding an interceptor that can be used to execue jaxrs calls over various protocols.

This interceptor is based on the ideas developed from SwaggerSocket and it differs from the original in
- simplified the package structure
- uses atmosphere's completion-aware feature to support chunked mode (previously this was not possible when using jersey)
- allows the body payload to be detached from the json envelope part and placed after the json envelope part.
- it can be customized in some extent to change the format.

**Comment by manikantag** [comment]
Looking for something like this, and currently using custom JSON based solution. How to use this? Any documentation? Thanks.

**Comment by elakito** [comment]
@manikantag I have not had time to update the atmosphere doc. We only have a documentation that is specific to the usage of this interceptor in kaka-rest-atmosphere which is a websocket enabled version of kafka-rest gateway.
This binding document describes the message format
https://raw.githubusercontent.com/elakito/kafka-rest-atmosphere/master/kafka-rest-websocket-binding.adoc

and this code segment shows how to set up this interceptor.
https://github.com/elakito/kafka-rest-atmosphere/blob/master/src/main/java/de/elakito/kafka/atmosphere/AtmosphereApplication.java#L136-L153
