### ISSUE TITLE
onHeartbeat is never called

### ISSUE THREAD

**Issue by jonrimmer** [Atmosphere/atmosphere#2162]
I have a handler that looks roughly like this:

``` java
@AtmosphereHandlerService(path = "/client", interceptors = {
  HeartbeatInterceptor.class
})
public class ClientHandler extends AtmosphereHandlerAdapter {
  public void onRequest(AtmosphereResource resource) {
    resource.addEventListener(new AtmosphereResourceEventListenerAdapter() {
      public void onHeartbeat(AtmosphereResourceEvent event) {
        Logger.log("Received heartbeat from client");
      }
    });

    resource.suspend();
  }
}
```

The HeartbeatInterceptor is working and is receiving updates from the client, but these never reach the configured listener.

If I debug the HeartbeatInterceptor, I can see that the AtmosphereResource being passed into its inspect method is not the same as the one passed into the onRequest method. It has no attached listeners, so when the interceptor tries to notify the listeners, there's nothing to notify.

It seems like AsynchronousProcessor.action() will always create a new instance of AtmosphereResource before calling the interceptors. So I'm not sure how onHeartbeat could ever work, as implemented?

**Comment by jonrimmer** [comment]
I have created a very simple reproduction here: https://github.com/jonrimmer/on-heartbeat-is-broken

It is just an embedded Jetty server and a single handler. Despite heartbeats being sent from the client, and received by Atmosphere on the server, the onHeartbeat handler is not run.

**Comment by saikiran939** [comment]
No, it will work all you have to do is extend AtmosphereResourceHeartbeatEventListener into your MyHandler and then from org.atmosphere.interceptor.HeartbeatInterceptor.inspect(AtmosphereResource) will inspect and add your event listener if your handler extends AtmosphereResourceHeartbeatEventListener interface. 

The order of input request is processing is - it first invokes the interceptors and then onRequest()

I made this change to MyHandler class which you have provided and onHeartbeat() method is invoked.
