### ISSUE TITLE
Broadcaster with URI path template not getting destroyed on tomcat shutdown

### ISSUE THREAD

**Issue by Shabin** [Atmosphere/atmosphere#2165]
I am using atmosphere-runtime 2.2.0 with atmosphere-jgroups 2.1.3 on Tomcat 7. 
I have a @ManagedService class with path defined as "{path}/myPath". On server startup, a broadcaster with id "{path}/myPath" is getting created. On sending a request of the form /async/myPath, another broadcaster with id "async/myPath" is also created. But on tomcat shutdown, only the broadcaster with id "/async/myPath" is getting destroyed. So the threads created for "{path}/myPath" is still there and graceful shutdown of tomcat doesn't happen.

On debugging the code, I found that during creation of /async/myPath broadcaster, in the [mapAnnotatedService() method of ServiceInterceptor](https://github.com/Atmosphere/atmosphere/blob/master/modules/cpr/src/main/java/org/atmosphere/config/managed/ServiceInterceptor.java#L86), the broadcaster with curly braces is removed from the broadcasterFactory. 

``` java
// Remove the Broadcaster with curly braces
if (b.getID().contains("{")) {
    reMap = true;
    config.getBroadcasterFactory().remove(b.getID());
}
```

But that broadcaster is just removed from the broadcasterFactory's hashmap(store) and is not destroyed. 
At server shutdown, the broadcasterFactory store won't have the "{path}/myPath" broadcaster and hence it won't be destroyed. 

Currently I have removed with {path} variable from ManagedService and kept it as /async/myPath itself. I am not sure whether it is a bug or is some issue with my code. Please check and advice.

servlet config in web.xml

``` xml
    <servlet>
        <description>AtmosphereServlet</description>
        <servlet-name>AtmosphereServlet</servlet-name>
        <servlet-class>org.atmosphere.cpr.AtmosphereServlet</servlet-class>
        <init-param>
            <param-name>org.atmosphere.cpr.packages</param-name>
            <param-value>org.atmosphere.samples</param-value>
        </init-param>
         <init-param>
            <param-name>org.atmosphere.cpr.broadcasterLifeCyclePolicy</param-name>
            <param-value>EMPTY_DESTROY</param-value>
        </init-param>
        <load-on-startup>1</load-on-startup>
        <async-supported>true</async-supported>
    </servlet>

    <servlet-mapping>
        <servlet-name>AtmosphereServlet</servlet-name>
        <url-pattern>/async/*</url-pattern>
    </servlet-mapping>
```

**Comment by jfarcand** [comment]
@Shabin Pull request please :-)

**Comment by Shabin** [comment]
@jfarcand Destroying the broadcaster explicitly or not removing the id from store - both worked fine for my case. I am not sure which one to choose.
These are the code snippets:
- Not remove
```java
// Remove the Broadcaster with curly braces
if (b.getID().contains("{")) {
   reMap = true;
   //don't remove the broadcaster from the store
   //config.getBroadcasterFactory().remove(b.getID());
}
```
- Destroy
```java
// Remove the Broadcaster with curly braces
if (b.getID().contains("{")) {
    reMap = true;
    //destroy the broadcaster instead or remove
    config.getBroadcasterFactory().lookup(b.getID()).destroy();
}
```
Anyway in the second case, a new broadcaster with the name "{path}/myPath" again gets created. So may be the first way will suffice. You know better :-)

**Comment by Shabin** [comment]
Hi,
Any update on this?

**Comment by saikiran939** [comment]
You could also use overloaded version of lookup(String, boolean) if the second parameter is false it doesn't create a new one - returns you null in the case where broadcaster is not present. 

`// Remove the Broadcaster with curly braces
if (b.getID().contains("{")) {
    reMap = true;
    //destroy the broadcaster instead or remove
    config.getBroadcasterFactory().lookup(b.getID()).destroy();
}`
