### ISSUE TITLE
Wildcard mapping optimization only applied to first handler

### ISSUE THREAD

**Issue by jacobg** [Atmosphere/atmosphere#2166]
Repro steps:
1) In web.xml set org.atmosphere.cpr.packages to a package of websocket endpoint handler classes
2) In the package, create two endpoint classes, one called AWebsocketHandler that does not not have a wildcard path; and a second called BWebsocketHandler that does have a wildcard path.
3) Start up server, and call two different path params of BWebsocketHandler

Expected behavior: Two instances of BWebsocketHandler should be created, one for each path param.

Actual behavior: Only one instance is created, with the injected path param of the first request.

Workaround: If you see swap the AWebsocketHandler and BWebsocketHandler class names so that the AWebsocketHandler has the wild card mapping, then it works fine.

Explanation: It looks like when the Atmosphere annotation detector auto detects these classes at start up in alphabetical order, it only applies the DefaultWebSocketProcessor::optimizeMapping on configuring the first handler, since that function is only called when creating the processor the first time (see WebSocketProcessorFactory::getWebSocketProcessor).

Thanks!

**Comment by jacobg** [comment]
Another thought: I am kind of curious why DefaultWebSocketProcessor::postProcessMapping uses the wildcardMapping() check as an optimization across all the handlers, when it could do the optimization for the particular handler on its own?

**Comment by jfarcand** [comment]
@jacobg If you apply your recommendation, does it work?

**Comment by jacobg** [comment]
@jfarcand Thanks for the reply. Yes, my workaround to change alphabetical order does work.
