### ISSUE TITLE
NullPointerException on Atmosphere init - II

### ISSUE THREAD

**Issue by neopsis** [Atmosphere/atmosphere#2171]
@jfarcand: why did you close the issue so quickly. I do not agree. I have of course packages, but our framework does not return the package by calling getClass.getPackage()! Because we can run multiple package versions in parallel, we have to use our framework API to get the currently active package, anything like

`Api.getPackageForModule(module);`

IMO you should use a callback to get package / package name and give me a chance to override the callback with my implementation. Now I have to patch your framework and compile from source code.

**Comment by jfarcand** [comment]
Please use the mailing list for discussion https://groups.google.com/forum/#!forum/atmosphere-framework
