### ISSUE TITLE
@PathParam is always null

### ISSUE THREAD

**Issue by naveengopi** [Atmosphere/atmosphere#2173]
Hi,

I am using the 2..4.2 version of Atmosphere with Spring 4.2.6. I have created a Managed Service called as AtmosphereChat. The problem for me is the @PathParam is always returns null. The request uri (resource.getRequest().getRequestURI()) does contain the path param.

The java code is

`@ManagedService(path = "apis/chat/{email}", atmosphereConfig = MAX_INACTIVE + "=120000")
public class AtmosphereChat {

  private final Logger logger = LoggerFactory.getLogger(AtmosphereChat.class);

  @Autowired
  private AtmosphereUUID uuid;

  @PathParam("email")
  private String email;

  @Autowired
  private CustomerService customerService;

  // @PathParam("department")
  private long department;

  private final static String CHAT = "/chat/";

  @Autowired
  private BroadcasterFactory broadcastFactory;

  @Autowired
  private AtmosphereResourceFactory resourceFactory;

  @Get
  public void init(AtmosphereResource resource) {
    resource.getResponse().setCharacterEncoding("UTF-8");
  }

  @Heartbeat
  public void onHeartbeat(final AtmosphereResourceEvent event) {
    logger.trace("Heartbeat send by {}", event.getResource());
  }
`

**Comment by mkefd** [comment]
Hi @naveengopi,

Do you use atmosphere-spring? Seems to be the same problem as #2167
