### ISSUE TITLE
Edge & IE 11 websocket over https does not work

### ISSUE THREAD

**Issue by umbreak** [Atmosphere/atmosphere#2184]
Microsoft 10 with Edge browser, as well as Microsoft 7 with IE11 browser get the following in the console (when trying to subscribe to the websocket)

> SCRIPT12008: WebSocket Error: Incorrect HTTP response. Status code 200, OK

Only when using https. Using http it does work correctly.

The establishment of the connection is done:

>  var request = {
>         url: https://url,
>         contentType: "application/json",
>         logLevel: 'info',
>         transport: 'websocket',
>         trackMessageLength: true,
>         reconnectInterval: 1000,
>         maxReconnectOnClose: 10,
>         fallbackTransport: 'long-polling'
>     };
> 
> atmosphere.subscribe(request);

**Comment by jfarcand** [comment]
@umbreak Are you sure your server accept `wss`?

**Comment by umbreak** [comment]
That in the request.url I set https instead of wss is wrong?

Websockets is accepted and I used https. Otherwise It won't work in Firefox,  Chrome and Safari. But it does.

**Comment by umbreak** [comment]
Sorry. It was an issue in Apache handling the redirection to the internal proxy. The right way to do a rewrite rule is with the `RewriteCond`:

    RewriteCond %{HTTP:Upgrade} ^websocket$ [NC]
