### ISSUE TITLE
ERROR [org.atmosphere.cpr.AtmosphereFramework] (ServerService Thread Pool -- 74) Unable to configure Broadcaster/Factory/Cache: java.lang.ClassNotFoundException: JGroupsBroadcaster from [Module "deployment.sdp-jcm-ear.ear.sdp-jcm-restapp.war:main" from Service Module Loader]

### ISSUE THREAD

**Issue by skionsnow59** [Atmosphere/atmosphere#2185]
I am trying to use the JGroupBroadcaster for my application using Atmosphere websockets.  I have included the following dependencies:
	<dependency>
			<groupId>org.atmosphere</groupId>
			<artifactId>atmosphere-runtime</artifactId>
			<version>2.3.2</version>
		</dependency>
		<dependency>
         <groupId>org.atmosphere</groupId>
         <artifactId>atmosphere-jgroups</artifactId>
         <version>2.3.2</version>
      </dependency>

<build>
		<plugins>
			<plugin>
				<artifactId>maven-war-plugin</artifactId>
					<configuration>
						<archive>
							<manifestEntries>
							<Dependencies>org.apache.httpcomponents, org.jgroups</Dependencies>
							</manifestEntries>
						</archive>
					</configuration>
			</plugin>
		</plugins>
	</build>

I have verified that the WEB-INF/lib includes the atmosphere-jgroups-2.3.2.jar and atmosphere-runtime-2.3.2.jar.   At run time I am getting a classloader exception for JGroupsBroadcaster.  I am deploying this on JBOSS EAP 6.3.3.

What am I missing here?

Thanks,
Jim

**Comment by skionsnow59** [comment]
I edited my response and the dependency data was erased so here it is again:

	<dependency>
			<groupId>org.atmosphere</groupId>
			<artifactId>atmosphere-runtime</artifactId>
			<version>2.3.2</version>
		</dependency>
		<dependency>
         <groupId>org.atmosphere</groupId>
         <artifactId>atmosphere-jgroups</artifactId>
         <version>2.3.2</version>
      </dependency>


<build>
		<plugins>
			<plugin>
				<artifactId>maven-war-plugin</artifactId>
					<configuration>
						<archive>
							<manifestEntries>
							<Dependencies>org.apache.httpcomponents, org.jgroups</Dependencies>
							</manifestEntries>
						</archive>
					</configuration>
			</plugin>
		</plugins>
	</build>

I included jgroups because looking at the source file it had org.jgroups includes.  I there more depenencies?
I also tried JMSBroadcaster as well and the same issue.

**Comment by jfarcand** [comment]
Use [mailing list](https://groups.google.com/group/atmosphere-framework?pli=1) for question
