### ISSUE TITLE
Broadcasters not released from memory due to AtmosphereHandlerWrapper

### ISSUE THREAD

**Issue by vasekt** [Atmosphere/atmosphere#2186]
Hi,

I am using atmosphere (2.3.5) with PrimeFaces on payara web server in one of my projects and I am having memory issues. New broadcaster is created for each user ( lets say it is /foo/{idUsr} ), and after few days I can see thousands of broadcasters in memory ( jmap heapdump )
. 
I think this is not lifecycle policy problem - I've been playing with lifecycle policy for a while and it is set  to IDLE_DESTROY, however it didn't solve problem for me. In heapdump I can see broadcasters are still referenced from ApplicationFramework.atmosphereHandlers map. I ve been going through source codes for quite a long time however I am not sure how to handle this. I also checked newer versions of atmosphere, but I dont' think there is anything new about this.

Solution could be manually calling removeAtmosphereHandler ( but I cannot access atmosphere from my application because is are using PrimeFaces classes ). Am I supposed to do so? I would expect atmosphere to clean everything about broadcaster itself when destroying. But maybe I am missing something / using atmosphere in an incorrect way.

Any advice appreciated. Thanks

**Comment by saikiran939** [comment]
A similar issue I found out, I don't know whether the issue I found out is the same issue your have reported.

Recently, I have been developing monitoring APIs to report the no.of broadcasters connected to our servers, during that process I have written this simple test case - which destroys the broadcaster and assert on the number of active/alive broadcaster and I found that the broadcaster object is not removed broadcaster factory. Here is the simple test case:

`Broadcaster b1 = broadcasterFactory.lookup("/SOMEID/RECOGID", true);`
`Assert.assertEquals(1, mAtmosphere.getBroadcasterFactory().lookupAll().size());`
`b1.destroy();`
`Assert.assertEquals(0, mAtmosphere.getBroadcasterFactory().lookupAll().size());`

After few hours of debugging the code and I found the issue in in DefaultBroadcaster.destroy() and my analysis is put below:

1. Firstly the broadcaster is marked as destroyed - which looked neat in the first step.
2. there is this trace logger statement which prints the list of atmosphere resources associated with the current broadcaster, in the org.atmosphere.cpr.AtmosphereResourceImpl.toString() implementation is also prints broadcaster id using getBroadcaster().getID() but this getBroadcaster() method passes 'autoCreate' argument as 'true' to org.atmosphere.cpr.AtmosphereResourceImpl.getBroadcaster(boolean) and as the broadcaster has already been marked as destroyed it will re-create the broadcaster and associate the resource back again.

I don't know the implementors of atmosphere wanted this to happen. 

The fix would be to mark the broadcaster as destroyed after printing the trace line, i re-ordered two statements and test case passed. I would be happy if other developers chip-in and provide their analysis. I can also submit a pull request if they agree with my analysis.

**Comment by saikiran939** [comment]
Tagging @jfarcand for his thoughts

**Comment by saikiran939** [comment]
@jfarcand do you want me to open a pull request ? I can do it.

**Comment by jfarcand** [comment]
@saikiran939 go!

**Comment by saikiran939** [comment]
@jfarcand - I opened pull request for this. could you please approve.

**Comment by kylejmcintyre** [comment]
This issue seems pretty significant. Any chance of backporting the fix into 2.4.x and doing a release?

Thanks,
Kyle

**Comment by jfarcand** [comment]
@kylejmcintyre 2.4.14 released.
