### ISSUE TITLE
Atmosphere in Apache Felix container (OSGi)

### ISSUE THREAD

**Issue by harshild** [Atmosphere/atmosphere#2191]
I have an application, which uses Dropwizard + Jersey , configured for Atmosphere , and it works like a charm.

But, now I am porting it to work and OSGi , the Atmosphere framework is initialized but Resources are not mapped. When i send a GET request I get error :-

`org.atmosphere.cpr.AtmosphereMappingException: No AtmosphereHandler found. Make sure you define it inside WEB-INF/atmosphere.xml or annotate using @___Service`

When I set ReflectorServletProcessor as the handler , on sending GET request i get error :-

`java.lang.RuntimeException: javax.servlet.ServletException: No Servlet Found`

It looks like it has something to do with the ClassLoaders.

You may use sample [code] ( https://github.com/harshild/atmosphere-osgi ) to debug the same, no setup configuration will be required to run it, it is backed by Gradle and [Gradle Felix Plugin](https://github.com/harshild/gradle-felix-plugin) , It can be run by a single Gradle command `gradle runFelix`

**Comment by harshild** [comment]
I would also like to create a PR to demonstrate a sample when using Atmosphere with OSGi. I will do it once it is fixed.

Let me know if complete error stacktrace is required

**Comment by harshild** [comment]
Just noticed another error 
`INFO  o.a.cpr.DefaultAnnotationProcessor - AnnotationProcessor class org.atmosphere.cpr.DefaultAnnotationProcessor$BytecodeBasedAnnotationProcessor being used`
`WARN  o.a.cpr.DefaultAnnotationProcessor - Unable to detect annotations. Application may fail to deploy.`

**Comment by harshild** [comment]
Okay ! It is indeed a class loader issue, with a little hack i could make atmosphere work with OSGi. But there are two issues 

- Class Loader hack is not as per the OSGi guidline, the hack is therefore not appropiate
- I still could achieve WebSocket connection, Atmosphere is falling back to Long Polling

**Comment by harshild** [comment]
Websocket connection is failing with this exception 

`java.lang.LinkageError: loader constraint violation: when resolving interface method "org.eclipse.jetty.server.Connector.getByteBufferPool()Lorg/eclipse/jetty/io/ByteBufferPool;" the class loader (instance of org/apache/felix/framework/BundleWiringImpl$BundleClassLoaderJava5) of the current class, org/eclipse/jetty/websocket/server/WebSocketServerFactory, and the class loader (instance of org/apache/felix/framework/BundleWiringImpl$BundleClassLoaderJava5) for the method's defining class, org/eclipse/jetty/server/Connector, have different Class objects for the type org/eclipse/jetty/io/ByteBufferPool used in the signature
	at org.eclipse.jetty.websocket.server.WebSocketServerFactory.upgrade(WebSocketServerFactory.java:516) ~[na:na]
	at org.eclipse.jetty.websocket.server.WebSocketServerFactory.acceptWebSocket(WebSocketServerFactory.java:185) ~[na:na]
	at org.eclipse.jetty.websocket.server.WebSocketServerFactory.acceptWebSocket(WebSocketServerFactory.java:152) ~[na:na]
	at org.atmosphere.container.Jetty9AsyncSupportWithWebSocket$1.acceptWebSocket(Jetty9AsyncSupportWithWebSocket.java:146) ~[na:na]
	at org.atmosphere.container.Jetty9AsyncSupportWithWebSocket.service(Jetty9AsyncSupportWithWebSocket.java:175) ~[na:na]
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2287) ~[na:na]
	at org.atmosphere.cpr.AtmosphereServlet.doPost(AtmosphereServlet.java:191) ~[na:na]`

**Comment by elakito** [comment]
atmosphere itself has been used in OSGi and we also have a couple of samples using apache Karaf (running on felix). So I don't think there is a principal issue in atmosphere itself.

 Unfortunately there is no sample directly in atmosphere-samples. We will need to create an OSGi version of the simple echo sample there. 

Some of the samples using atmosphere in OSGi are here:
https://github.com/swagger-api/swagger-socket/tree/master/samples/swaggersocket-cxf-osgi-echo
https://github.com/elakito/swaggersocket-samples

**Comment by harshild** [comment]
Thanks for replying,

Definitely its not an issue with Atmosphere Framework. It is that OSGi framework has restricted Class Loading principle. So until and unless we explicitly define class loader which loads all class , `Class.forName` wont work for lot of situations. It happens for most of the third-party dependencies.

`Thread.currentThread().setContextClassLoader(this.getClass().getClassLoader());`

- But, it's not a issues with OSGi, its the baseline it follows, so is it possible to have a different way of Class Loading  other tjhan `Class.forName` and other equivalents ?

- I don't think SwaggerSocket examples will be of real help. Although, i have ready and working sample for Atmosphere Framwork and OSGi, with only issue which is WebSocket support.

- WebSocket issues appears class loader issue as well but mostly it cannot be fixed on Atmosphere's part.

_For sample purposes if you wish i can create a code like [this](https://github.com/harshild/atmosphere-osgi)_

**Comment by elakito** [comment]
As you also agree, this is not an issue in atmosphere, I don't think it makes sense to keep this ticket open for atmosphere's issue list. So, would you mind closing it?  By the way, I just added an osgi version of cxf-chat sample in atmosphere-samples' samples/cxf-chat-osgi. This is similar to the swagger socket's sample but uses plain chat service like other atmosphere samples.
