### ISSUE TITLE
AJAX push is not working in IPV6 mode

### ISSUE THREAD

**Issue by ajayjnv02** [Atmosphere/atmosphere#2195]
Hi

 

We are using richfaces-a4j-4.5.14.Final  with atmosphere-runtime-2.2.3.jar

 

And we have following entries in web.xml

 

<context-param>

        <param-name>org.richfaces.push.handlerMapping</param-name>

        <param-value>/__richfaces_push</param-value>

    </context-param>

 

<servlet>

        <servlet-name>Push Servlet</servlet-name>

        <servlet-class>org.richfaces.webapp.PushServlet</servlet-class>

        <load-on-startup>1</load-on-startup>

    </servlet>

 

 

But the ajax push is not working with ipv6 mode. We have tested the same with IPV4 mode.

 

Kindly help us in resolving this issue.

 

Best Regards!

**Comment by jfarcand** [comment]
Ask the question to the richfaces team or the app server you are using. This has nothing to do with Atmosphere.
