### ISSUE TITLE
UUIDBroadcasterCache: Reason why broadcaster cache listener is not called on invalidateExpiredEntries()

### ISSUE THREAD

**Issue by saikiran939** [Atmosphere/atmosphere#2199]
Hi,

Is there any specific reason why org.atmosphere.cache.UUIDBroadcasterCache.invalidateExpiredEntries() doesn't invoke org.atmosphere.cache.UUIDBroadcasterCache.notifyRemoveCache(String, CacheMessage) method - which will inturn invoke the cache listeners ?

Tagging @jfarcand - if it is not an intentional change, i can submit a pull request for the same.

Thanks

**Comment by jfarcand** [comment]
@saikiran939 +1 for the pull
