### ISSUE TITLE
Get the reference of AtmosphereResource which sent the message inside @Message

### ISSUE THREAD

**Issue by arunkjn** [Atmosphere/atmosphere#2200]
I am using an @Message handler inside my code. I want to know the resource which sent this message to the server. One of the ways is to have the client send its uuid as part of the message and retrieve it. Is there any other way to do it without explicitly encoding in in the message?

**Comment by saikiran939** [comment]
Usually @Message is invoked at server side, a hook that is invoked whenever a broadcast operation is performed. 

Whenever client sends a message, it is delivered to @Post annotated method and @Post method will get AtmosphereResource.
