### ISSUE TITLE
@PathParam value is null, because wildcardMapping is wrong

### ISSUE THREAD

**Issue by randm-ch** [Atmosphere/atmosphere#2201]
The screenshots below show that the value for `wilcardMapping` [sic] is `false` even though the `path` in the `ManagedService` has a wildcard parameter and the class has an attribute that is annotated with `@PathParam`. This causes said attribute to always be `null`.

I traced the problem to `ManagedServiceInterceptor.java` on line 68, this patch should fix the issue (but haven't tested it):

```
diff --git
a/modules/cpr/src/main/java/org/atmosphere/config/managed/ManagedServiceInterceptor.java
b/modules/cpr/src/main/java/org/atmosphere/config/managed/ManagedServiceInterceptor.java
index e53bf10..de99afa 100644
--- a/modules/cpr/src/main/java/org/atmosphere/config/managed/ManagedServiceInterceptor.java
+++ b/modules/cpr/src/main/java/org/atmosphere/config/managed/ManagedServiceInterceptor.java
@@ -65,7 +65,7 @@ public class ManagedServiceInterceptor extends ServiceInterceptor {

AtmosphereResourceImpl.class.cast(request.resource()).atmosphereHandler(ap);

-        config.framework().addAtmosphereHandler(path, ap,
+        config.framework().addAtmosphereHandler(targetPath, ap,
            config.getBroadcasterFactory().lookup(a.broadcaster(), path, true), w.interceptors);
        request.setAttribute(FrameworkConfig.NEW_MAPPING, "true");
    } catch (Throwable e) {
```

We use the Play! Framework 2.5.4 with `atmosphere-play` 2.3.0 and `atmosphere-guice` 2.4.2.

I would appreciate instructions on how to compile the library myself (can I use `mvn install`?) or a quick fix on your end. What do you suggest? Or is this not a Atmosphere bug, but a problem on my end?

Thanks!

![screenshot 2016-08-12 12 26 38](https://cloud.githubusercontent.com/assets/2759010/17620065/ebba475e-6089-11e6-8d84-3da4edfad0fa.png)
![screenshot 2016-08-12 12 27 18](https://cloud.githubusercontent.com/assets/2759010/17620066/ebbbd52e-6089-11e6-8222-75aa5584226f.png)

**Comment by randm-ch** [comment]
Hello again!

I found the time to implement the suggested change, compile and build the project, and load it into ours. Sadly, it didn't fix the issue. I do however still suspect that this is a bug with atmosphere, that should be addressed. Let me know if I can help you with anything.

Cheers!
Raphael

**Comment by mkefd** [comment]
Hi @randm-ch ,

Seems that including injection plugin (cdi, spring or guice) breaks default annotation processing.
Addition info #2167 and #2201
