### ISSUE TITLE
Atmosphere's websocket transport doesn't work on Liberty when deployed as spring boot app

### ISSUE THREAD

**Issue by stsymbal** [Atmosphere/atmosphere#2209]
Atmosphere's websocket transport doesn't work on Liberty when deployed as spring boot app. 
Handshake returns 200 instead of 101 status code and Atmosphere attempts to fall back to long-polling. The error on the server side is the following:

Liberty:
`[8/30/16 13:24:26:035 CDT] 00000078 id=0ca5a83f com.ibm.ws.wsoc.WsocConnLink                                 > close Entry                                                                                                               CloseReason[1011,Connection closed: Read failed.  Possible end of stream encountered. ]`

Atmosphere when attempts to suspend the resource:
`[8/30/16 13:24:26:124 CDT] 0000005d id=         SystemOut                                                    O 15:39:36.865 [Default Executor-thread-27] TRACE o.a.container.JSR356Endpoint - com.ibm.ws.wsoc.external.v11.SessionExtV11@74ee5177 closed CloseReason[1011,Connection closed: Read failed.  Possible end of stream encountered. ]`

The below link contains the repro:

https://github.com/stsymbal/atmosphere-samples/tree/spring-boot-deployable-war

Note that websocket transport works with the following none-spring war file, so it looks like the problem is Spring or Spring Boot specific.
[atmosphere-chat-2.4.5.war](http://search.maven.org/remotecontent?filepath=org/atmosphere/samples/atmosphere-chat/2.4.5/atmosphere-chat-2.4.5.war)

**Comment by jfarcand** [comment]
CC @philwebb .

**Comment by jfarcand** [comment]
At first, it seems the jsr356 container is not properly initialized by Spring Boot there.

**Comment by seamusmac** [comment]
What version of WAS LIberty are you using? Did you install the websockets module?

I am using regular Spring 4.2.7 and latest WAS Liberty 6.0.0.2 with the websockets 1.1 module and it all works fine for me.

**Comment by jfarcand** [comment]
@seamusmac Are you using Spring Boot? It works well with Atmosphere without it.

**Comment by seamusmac** [comment]
@jfarcand Sorry no I'm not using Spring Boot, I thought Spring would have been the same. I did check out the project to have a quick look, and as you said there is definitely some issue here. 

Here is the stacktrace I get with that project on Liberty. https://gist.github.com/seamusmac/0cd5bdf1ff620290ed4c628022d7bb1b

**Comment by philwebb** [comment]
@seamusmac If it's a Spring issue could you please raise a bug at http://jira.springsource.org/.

**Comment by jfarcand** [comment]
@philwebb, I agree with @elakito, there is some strange things happening in Spring Boot, not Spring
```
it looks like there is something wrong with the buffering in liberty+springboot.
it is not returning the expected http header.

I looked at the http headers returned by both atmosphere-chat.war and
spring-boot-sample-atmosphere.war.
atmosphere-chat, which is working fine, returned a valid http header
whereas spring-boot-sample-atmosphere returned an http header,
otherwise valid, but proceeded by some corrupted string (atmosphere's protocol * 045|65cf89c0-363a-451c-a4d8-536a2b70099b|10000|X|*), thus it is
invalid and hence not recognized by the client.
see the transcription attached. It looks like what is written by
atmosphere to the websocket is written to the stream before the http
header is written. It is really strange.
I don't think this is an atmosphere issue.
```

```
GET /atmosphere-chat/chat?X-Atmosphere-tracking-id=0&X-Atmosphere-Framework=2.3.2-javascript&X-Atmosphere-Transport=websocket&X-Atmosphere-TrackMessageSize=true&Content-Type=application/json&X-atmo-protocol=true HTTP/1.1
Upgrade: websocket
Connection: Upgrade
Host: 192.168.99.100:32769
Origin: http://192.168.99.100:32769
Cookie: __utma=111872281.199833355.1450788534.1450788534.1450788534.1
Pragma: no-cache
Cache-Control: no-cache
Sec-WebSocket-Key: QWD/mWYlRhHq2uJjAHqUCg==
Sec-WebSocket-Version: 13
Sec-WebSocket-Extensions: x-webkit-deflate-frame
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.8 (KHTML, like Gecko) Version/9.1.3 Safari/601.7.8

ÀñNYf.K>
==== Response ====
HTTP/1.1 101 Switching Protocols
X-Powered-By: Servlet/3.1
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: rPDSORG2hy1mDuusHcHpKCPWNVA=
Content-Language: en-US
Content-Length: 0
Set-Cookie: JSESSIONID=0000FxTO7IIVVLg_1Alt-RRxrP7:c9928cb8-38e9-4aa4-bea4-42867f47aedf; Path=/; HttpOnly
Date: Fri, 02 Sep 2016 23:27:56 GMT
Expires: Thu, 01 Dec 1994 16:00:00 GMT
Cache-Control: no-cache="set-cookie, set-cookie2"

045|b5f477d5-4f94-46bc-9cc4-4e7c26e91b93|10000|X|
==============
```

And 

```
==== Request ====
GET /spring-boot-sample-atmosphere/chat?X-Atmosphere-tracking-id=0&X-Atmosphere-Framework=2.3.0-javascript&X-Atmosphere-Transport=websocket&X-Atmosphere-TrackMessageSize=true&Content-Type=application/json&X-atmo-protocol=true HTTP/1.1
Upgrade: websocket
Connection: Upgrade
Host: 192.168.99.100:32769
Origin: http://192.168.99.100:32769
Cookie: __utma=111872281.199833355.1450788534.1450788534.1450788534.1
Pragma: no-cache
Cache-Control: no-cache
Sec-WebSocket-Key: 5hsBsIn16PX8NhbyCSmNFA==
Sec-WebSocket-Version: 13
Sec-WebSocket-Extensions: x-webkit-deflate-frame
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.8 (KHTML, like Gecko) Version/9.1.3 Safari/601.7.8


==== Response ====
045|65cf89c0-363a-451c-a4d8-536a2b70099b|10000|X|HTTP/1.1 101 Switching Protocols
X-Powered-By: Servlet/3.1
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: dnOfaTC9oLIsxY5HUwzN3WGEYCA=
Content-Language: en-US
Content-Length: 0
Set-Cookie: JSESSIONID=0000o7VkB-bnUvmm6flntSdipuT:c9928cb8-38e9-4aa4-bea4-42867f47aedf; Path=/; HttpOnly
Date: Fri, 02 Sep 2016 23:22:12 GMT
Expires: Thu, 01 Dec 1994 16:00:00 GMT
Cache-Control: no-cache="set-cookie, set-cookie2"

1|X
==============
```
@philwebb Is SpringBoot bufferring body/header?

**Comment by philwebb** [comment]
@jfarcand It's possible that the error handling code is getting in the way. I'll raise a Boot issue to investigate.

**Comment by elakito** [comment]
@philwebb what appears to be happening is that the response http header for the websocket upgrade request is not flushed by the container before the initial data written to the websocket. You can probably write a simple app without atmosphere that reproduces this issue and then give it to the Liberty guys to look at. I don't think the spring-boot guys without much Liberty knowledge can help.

**Comment by stsymbal** [comment]
@elakito, I was able to reproduce the problem with "spring-boot-sample-websocket” application, BUT only during the first "echo connect" after app server start up. All subsequent "echo connects" result is successful websocket connection. Please see my comment in the issue @philwebb opened earlier:
https://github.com/spring-projects/spring-boot/issues/6822#issuecomment-244969540

**Comment by jfarcand** [comment]
@stsymbal Great work!

**Comment by stsymbal** [comment]
IBM fixed the problem via ifix PI70184 for Liberty 8.5.5.9 released to my customer. It is not clear if/when it will be publicly available, so if interested then open a PMR with IBM Support to request the ifix ported to your version of Liberty.

**Comment by jfarcand** [comment]
Closing as fixed.
