### ISSUE TITLE
IdleResourceInterceptor logging invalid state at error level

### ISSUE THREAD

**Issue by Talon876** [Atmosphere/atmosphere#2214]
Hello,

The IdleResourceInterceptor considers resources as invalid if they do not have the `MAX_INACTIVE`property set. However, this interceptor is also responsible for setting that particular property. Since the `idleResources()` method is being called every 2 seconds using a `ScheduledFuture` I'm guessing this is a race condition where `idleResources()` is called before `insepect()`.

We are occasionally seeing this message show up in our logs but it does not appear to be causing any failures. **Since atmosphere appears to gracefully recover from this scenario would you consider changing the log level to info or warn?**

Also, do you have any recommendations on preventing resources from getting in to this state in the first place?

**Comment by saikiran939** [comment]
thanks for bringing it up, even I faced this issue, may be we can change to WARN ? I can do a pull request for this.

**Comment by jfarcand** [comment]
+1

**Comment by saikiran939** [comment]
@jfarcand - Made a pull request - Could you please approve it ?
