### ISSUE TITLE
Prevent AtmosphereRequest from writing attributes once resumed to prevent broken container from crashing

### ISSUE THREAD

**Issue by jfarcand** [Atmosphere/atmosphere#2215]
For example, with long-polling, WebSphere keep crashing under load as it seems to re-use `HttpServletRequest` event if they are in use by the application.

**Comment by seamusmac** [comment]
@jfarcand  Sorry to hijack the thread here. 
I seen this pop into my inbox today. We are currently rolling out Atmosphere in an application to production on Websphere 8.5.x at the moment. 

Is this an urgent fix that will be released soon, or I shouldn't be worried about it?

**Comment by jfarcand** [comment]
@seamusmac No, it is just an optimization as I do have an Async-IO customer that showed me some strange exception with `long-polling`.
