### ISSUE TITLE
CookieUtil memory leak on tomcat 8.0.28 shutdown

### ISSUE THREAD

**Issue by tejaghali** [Atmosphere/atmosphere#2221]
HI ,

Today i encountered the following issue on my local web application that uses atmosphere to server real time notifications.

28-Oct-2016 16:22:57.869 SEVERE [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [prweb] created a ThreadLocal with key of type [org.atmosphere.util.CookieUtil$1] (value [org.atmosphere.util.CookieUtil$1@d562d8e]) and a value of type [java.text.SimpleDateFormat] (value [java.text.SimpleDateFormat@a99420e6]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

I see that in cookieUtil class threadLocal is used to cache the simple date format object - instead of creating new one every time for the construction of response headers.

One simple way to fix this is not to cache the date format... but threadLocal has been used for some performance reasons if i am not wrong...

I just did a single threaded qucik test to verify the new SimpleDateFormat object creation vs fetching it from threadlocal and saw nothing to very minute performance impact in terms of nano seconds.

I also performed a multithreaded test with 5 threads and pumping 100 tasks that does toString(Cookie) ,toNewString(Cookie) and saw only 5 milli-seconds variant - i.e threadLocal is ahead of new object creation by 5 milli seconds.

Does anyone encountered this issue anytime ? If it has been already identified - how do we overcome this issue?

public class TestCookieUtil {

	/**
	 * @param args
	 * @throws InterruptedException 
	 */
	public static void main(String [] args) throws InterruptedException{
		ThreadPoolExecutor mExec = (ThreadPoolExecutor) java.util.concurrent.Executors.newFixedThreadPool(5);
	
		 long initialValue =  System.nanoTime() ;

		 int localCounter = 100;
		 
		 CountDownLatch latch = new CountDownLatch(localCounter);
		 
		 
		for(int i = 0 ; i < localCounter ; i ++)
		mExec.execute(new TestTask(latch));
		
		try {
			latch.await();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}finally {
System.out.println( System.nanoTime() - initialValue);
                  e.shutdown();
                }
		
	}

	

	
}

class TestTask implements Runnable {

	CountDownLatch aLatch ;
	Cookie a;

	public TestTask(CountDownLatch latch) {

		a = new Cookie("yo", "man");
		a.setComment("kdaskjdaskda");
		a.setDomain("dasdasdasd");
		a.setHttpOnly(true);
		a.setPath("/ya");
		aLatch = latch;
	}

	@Override
	public void run() {
		aLatch.countDown();

		CookieUtil.toNewString(a);

	}
}

**Comment by jfarcand** [comment]
@tejaghali Pull request welcomed

**Comment by tejaghali** [comment]
@jfarcand  I created a pull request , can you please review and approve ? Thank you.
