### ISSUE TITLE
ExecutorsFactory.reset() never terminates/shutdown the threadpool on atmosphereFrameWork.destroy()

### ISSUE THREAD

**Issue by tejaghali** [Atmosphere/atmosphere#2223]
org.atmosphere.cpr.AtmosphereFramework.destroy() - method does cleanup job - in this process 

` 
//Invoke ShutdownHook.
config.destroy();

// Code of AtmosphereConfig.destroy() method
  **properties.clear();**

//Code snippet in org.atmosphere.util.ExecutorsFactory.getScheduler(AtmosphereConfig)
if (shared) {
                config.properties().put(SCHEDULER_THREAD_POOL, scheduler);
            }
    `

The mentioned code snippet clears of properties map that holds shared thread pools when atmosphere is configured to use ApplicationConfig.BROADCASTER_SHARABLE_THREAD_POOLS as true.

So framework.destroy() which in-turn calls config.destroy() before the ExecutorsFactory.reset(config) results in clearing of the properties map - and the actual logic in ExecutorsFactory.reset() doesn't have any effect as the properties in config map has been cleared off...

So the fix could be to place  **// config.destroy();** after the ExecutorsFactory.reset() call has been made.

Do please let me know if my understanding is correct - And other reasons why the code has been written in such a way. Thank you.

` 
// code snippet of reset() method
        ExecutorService e = (ExecutorService) config.properties().get(ASYNC_WRITE_THREAD_POOL);
        if (e != null) {
            e.shutdown();
        }
        config.properties().remove(ASYNC_WRITE_THREAD_POOL);

        e = (ExecutorService) config.properties().get(SCHEDULER_THREAD_POOL);
        if (e != null) {
            e.shutdown();
        }
        config.properties().remove(SCHEDULER_THREAD_POOL);

        e = (ExecutorService) config.properties().get(BROADCASTER_THREAD_POOL);
        if (e != null) {
            e.shutdown();
        }
        config.properties().remove(BROADCASTER_THREAD_POOL);
    `

**Comment by jfarcand** [comment]
@tejaghali Pull request :-)

**Comment by tejaghali** [comment]
@jfarcand  Created pull request - can you please accept ? Thank you

**Comment by tejaghali** [comment]
@jfarcand  Fixed tab character thank you for reminding the clean code practices . can you please review and accept ?
