### ISSUE TITLE
onOpen no longer called after upgrading to 2.4.7

### ISSUE THREAD

**Issue by jonrimmer** [Atmosphere/atmosphere#2224]
After upgrading from 2.4.6 to 2.4.7, our onOpen handler is no longer being called. The JS code has not changed, so this must be a server issue.

It looks like, when running 2.4.6, a message is sent from server to client immediately upon connect, and this is what causes the onOpen handler to be called. But after upgrading to 2.4.7, this message is no longer sent.

It looks like the problem was caused by commit d23b8bc7821f26202fdadab2122449f93267895a.

In  [JavaScriptProtocol.inspect()](https://github.com/Atmosphere/atmosphere/blob/atmosphere-2.4.x/modules/cpr/src/main/java/org/atmosphere/interceptor/JavaScriptProtocol.java#L165) the onSuspend handler for non-resumable transports is only sending the protocol message if ```delayProtocolMilliseconds``` is non-zero:

```java
@Override
public void onSuspend(AtmosphereResourceEvent event) {
    if (delayProtocolInMilliseconds > 0) {
        executorService.schedule(new Runnable() {
            @Override
            public void run() {
                response.write(protocolMessage.get());
            }
        }, delayProtocolInMilliseconds, TimeUnit.MILLISECONDS);
    } else {
        try {
            response.flushBuffer();
        } catch (IOException e) {
            logger.trace("", e);
        }
    }
    r.removeEventListener(this);
}
``` 

I guess you need ```response.write(protocolMessage.get());``` in the else block as well.

**Comment by jfarcand** [comment]
https://github.com/Atmosphere/atmosphere/pull/2225
