### ISSUE TITLE
Possible that multiple AtmosphereResourceFactory instances are created

### ISSUE THREAD

**Issue by slovdahl** [Atmosphere/atmosphere#2226]
Noticed with 2.2.9.

If `AtmosphereFramework.init()` is invoked after eg. `AtmosphereFramework.getBroadcasterFactory()` or `AtmosphereFramework.atmosphereFactory()` a second instance of `AtmosphereResourceFactory` is created.

This is problematic if guice is used and an instance of `AtmosphereResourceFactory` has already been leaked to the outside world. In that case Atmosphere internally uses one instance of `AtmosphereResourceFactory` while the instance available for injection with guice is another instance that's never used by Atmosphere itself.

Probably caused by #1785

**Comment by slovdahl** [comment]
This actually seems to be fixed on the 2.3.x branch by d4a8785e70572b8912d622f9d16b676855b7b8f6.

**Comment by slovdahl** [comment]
@elakito do you have any input on this issue? If it looks good to you I'd be very happy about a 2.2.10 release :)

**Comment by elakito** [comment]
@slovdahl the fix itself is fine but I wonder if you really need a 2.2.x release now because it's been quite a while since 2.2.9 was released and other bug fixes that went into 2.3.x aren't there as well. If you indeed need one, please go ahead. 
regards, aki

**Comment by slovdahl** [comment]
Yep, I'm still using 2.2.x in production so I need a fixed version. Thank you, I'm publishing a 2.2.10 then. I'll check if there are any trivial fixes that are cherry-pickable from 2.3.x before that, though.
