### ISSUE TITLE
Servlet Filters applied in random order

### ISSUE THREAD

**Issue by jbim** [Atmosphere/atmosphere#2227]
Filters are handed to the MeteorServlet constructor in an array, are then stored in a HashSet in the ReflectorServletProcessor before handed through to the FilterChain, where they are an array again. Thus the application order of the filters depends from their hashCode, not from the intended order.

In some cases the order is essential, e.g. when a CharacterEncodingFilter has to be applied before extracting a request parameter in another filter.

Changing the type of "filters" in ReflectorServletProcessor from HashSet to ArrayList should be sufficient to achieve this.

**Comment by jbim** [comment]
We use atmosphere-runtime-native 2.4.6, but the mentioned code is the same on the 2.4.x branch top and master.

**Comment by jfarcand** [comment]
@jbim Pull request welcomed! I will do a release after that.

**Comment by jfarcand** [comment]
Fixed, 2.4.8 released. Thanks!
