### ISSUE TITLE
Messages are sometimes lost while broadcasting Deliver

### ISSUE THREAD

**Issue by paulauskas96** [Atmosphere/atmosphere#2234]
In DefaultBroadcaster.deliverPush, deliver.message is stringified (instead of being kept as an object type) for no reason, which causes loss of a message in case it is an instance of, e.g., GwtEvent. (As GwtEvent.toString() returns "An event type".)

```
protected void deliverPush(Deliver deliver, boolean rec) {
       <...>
       String prevMessage = deliver.message.toString();
       <...>
       deliver.message = prevMessage;
       <...>
}
```

**Comment by jfarcand** [comment]
@paulauskas96 Pull request welcomed! Good catch.

**Comment by saikiran939** [comment]
I can do this.
