### ISSUE TITLE
Why does Atmosphere export packages in provided jar from Maven Central Repository?

### ISSUE THREAD

**Issue by faustmann** [Atmosphere/atmosphere#2237]
Hi,

thanks for the good product. It helped us a lot. :-)

Now we want to use it in an OSGI context.
We recognized that atmosphere jar file from maven central defines some packages in the section "Export-Package:" which it does not offer. 
e.g.: org.apache.shiro.web.env, org.glassfish.grizzly.websockets, javax.servlet.http, com.sun.grizzly.websockets, com.sun.grizzly.util.buf, com.sun.grizzly.tcp, com.sun.enterprise.web.connector.grizzly.comet, org.glassfish.grizzly.comet, org.glassfish.grizzly.http.server, com.sun.grizzly.comet

The Export-Package section should only contain Java packages from the jar which are available.

Thanks for your help!

**Comment by jfarcand** [comment]
@faustmann Contribution welcomed

**Comment by faustmann** [comment]
I am sorry. From my current point of view, the export section in the generated manifest file is okay.
It was a false alarm because I used an editor which does not highlight this file and I lost track which packages are exported and which packages are used by the exported packages.

If you also do not see a problem here I would close this issue.
