### ISSUE TITLE
Does Atmosphere work with the current socket.io version? Examples are outdated by 5 years

### ISSUE THREAD

**Issue by sqshq** [Atmosphere/atmosphere#2246]
[This examples](https://github.com/Atmosphere/atmosphere-samples/tree/master/extensions-samples/socketio) seems to be abandoned and outdated. socket.io v.0.9.6 is used there, which was released ~ 5 years ago.

I'm wondering does Atmosphere work with current socket.io?

**Comment by jfarcand** [comment]
Some work will need to be done...contribution welcomed :-)
