### ISSUE TITLE
WebSocket closed with 1002 Error in tomcat 7.0.35 version

### ISSUE THREAD

**Issue by maddaliravi** [Atmosphere/atmosphere#2251]
what is the 10002 error code mean while closing a websocket connection abruptly without providing the proper details of the reason for close.

Tomcat version used is 7.0.35 version and browser is Google Chrome.

**Comment by saikiran939** [comment]
any stacktrace ?

**Comment by maddaliravi** [comment]
There is no exception as such. 

I see this  .....TomcatWebSocketHandler: onClose 1002 ... in the TRACE logs.

**Comment by maddaliravi** [comment]
'maxIdleTime' value is causing the tomcat to close the websocket after the time has reached. currently we set it to 30 minutes... but we plan to increase it to 8 to 9 hours to avoid closing the connections frequently as our application use the websocket very rarely.
