### ISSUE TITLE
BroadcasterFactory not broadcasting message to client

### ISSUE THREAD

**Issue by Nadia1989** [Atmosphere/atmosphere#2254]
Doubt : broadcasterFactory.get(userId).broadcast(15); is not invoking getMessage() on client side.
Any response will be appreciated.

Java code for atmosphere handler 
---------------------------------------

import java.io.IOException;
import javax.inject.Inject;
import org.atmosphere.config.service.AtmosphereHandlerService;
import org.atmosphere.cpr.AtmosphereHandler;
import org.atmosphere.cpr.AtmosphereResource;
import org.atmosphere.cpr.AtmosphereResourceEvent;
import org.atmosphere.cpr.Broadcaster;
import org.atmosphere.cpr.BroadcasterFactory;

@AtmosphereHandlerService(path = "/chat",interceptors = org.atmosphere.interceptor.AtmosphereResourceLifecycleInterceptor.class)
public class WebSocketForPostsUsingAtmosphere implements AtmosphereHandler {
	@Inject 
	private BroadcasterFactory broadcasterFactory;
	
	
   @Override
    public void onRequest(AtmosphereResource r) throws IOException {  	
    	String userId = (String) r.getRequest().getParameter("userId");
    	Broadcaster broadcaster = broadcasterFactory.lookup(userId, true);
    	r.addBroadcaster(broadcaster);
        broadcasterFactory.get(userId).broadcast(15);
   }
	@Override
    public void onStateChange(AtmosphereResourceEvent event) throws IOException {
        if (event.isSuspended()) {
            event.broadcaster().broadcast("jsjaha jsajsakjs");
        }
    }
    @Override
    public void destroy() {

    }
}

Javascript code for calling above service
-----------------------------------------

var socket = atmosphere;								
var request = { url: 'http://192.168.1.45:8081/MarketProject/' + 'chat?userId='+userId,
			contentType : "application/json",
			logLevel : 'debug',
			transport : 'websocket' ,
			trackMessageLength : true,
			fallbackTransport: 'long-polling'
		    };
 request.onOpen = function(response) {
	alert("text: "+'Atmosphere connected using ' + response.transport);
};  
request.onMessage = function (response) {
	alert("response =>"+JSON.stringify(response));
};
request.onError = function(response) {
	alert('Sorry, but there is some problem with your ' + 'socket or the server is down' );
};  
var subSocket = socket.subscribe(request); 
subSocket.push(JSON.stringify({abc:"abc","abc1":"abc1"}));

**Comment by Nadia1989** [comment]
Please help if anyone has faced this issue.

**Comment by paulauskas96** [comment]
Hello,
seems familiar to me :).

The problem seems to be identified at #2236 . Found no proper fix, however, as what I had tried to commit (#2243) seems not to be a good practice and the Serializer needs to be set on the Broadcaster.

**Comment by redpacifier** [comment]
Seems similar issue reported at #2282 - I just saw this question on stackoverflow that will likely address your problem. Looks like it is caused by your use of "trackMessageLength" without using the TrackMessageLengthInterceptor. https://stackoverflow.com/a/19526230/3586783
