### ISSUE TITLE
Would I be able to use python flask socket io in the backend

### ISSUE THREAD

**Issue by blaisezzz** [Atmosphere/atmosphere#2256]
Hi,

I am exploring the possibility of integrating **Flask Socket IO** (https://github.com/miguelgrinberg/Flask-SocketIO) in the back-end with **atmosphere js** in the front-end. I am a new developer when it comes to Atmosphere JS, so I am uncertain if it is technically possible to integrate the two together. Looking it online haven't return any relevant results to help me move forward. Can I someone with more knowledge in determining the viability of this approach ? 

Thank you.

**Comment by jfarcand** [comment]
Use https://groups.google.com/group/atmosphere-framework?pli=1 for question
