### ISSUE TITLE
Make shiro an optional dependency

### ISSUE THREAD

**Issue by hendrikebbers** [Atmosphere/atmosphere#2261]
As far as I can see Apache shiro is only used in one class to provide security / shiro support. Without this dependency the core runtime would only depend on really common frameworks & JSRs. I think it would be a great benefit to provide the shiro support as an optional feature. This could be done by adding a shire-module to the project that contains the ShiroInterceptor.java. This can be loaded automatically by the runtime if it is on the class path.

I could do a PR if this feature is wanted. @jfarcand what do you think?

**Comment by saikiran939** [comment]
It would be really nice. Could you please share the changes without doing a PR - I mean by forking it and share the commit here ? Till @jfarcand gives green signal others can learn from it.

**Comment by jfarcand** [comment]
@hendrikebbers @saikiran939 +1 this is a great idea that could be added to next `2.4.x` release

**Comment by hendrikebbers** [comment]
Perfect :) I will work on this next week

**Comment by hendrikebbers** [comment]
But why should I add the change here? Everyone can see the PR and this can simple be changed if something is wrong.

**Comment by jfarcand** [comment]
+1

**Comment by jfarcand** [comment]
Fixed on master
