### ISSUE TITLE
Concurrency issue of UUIDBroadcasterCache 

### ISSUE THREAD

**Issue by ikeforward** [Atmosphere/atmosphere#2262]
Hello,

I am using atmosphere-runtime 2.4.9.

I am simulating to broadcast a massive amount of messages within a short time to test the stability. When long-polling protocol is used, even with UUIDBroadcasterCache, some messages are incorrectly cached.

I debug the source code, I've found something interesting (tell me if I am wrong):
- When a broadcaster broadcasts a message, a new thread is created. Therefore, when a broadcaster broadcasts a massive amount of messages within a short time, during this period, a massive amount of threads are created.
- in UUIDBroadcasterCache, for the same broadcaster, the methods: addToCache, retrieveFromCache, clearCache are not synchronized, which means the ConcurrentHashMap "messages" variable can be accessed by different threads at the same moment.
- in UUIDBroadcasterCache, the ConcurrentHashMap "messages" variable is not volatile, which means there is a possibility that the later thread may not have the "real" value of the "messages" variable that could be modified in a previous thread, because the modified value could be still in the previous thread cache, not moved into the memory yet.

To verify my guess above, I copy the UUIDBroadcasterCache, put addToCache, retrieveFromCache, clearCache methods to synchronized, change the variables "messages" and "activeClients" to volatile type, and use this customized cache, it solves the issue. But of course, it is slower.

Is there a solution in Atmosphere for this issue?

Many thanks.

**Comment by jfarcand** [comment]
@ikeforward Can you do a pull request with your change? I will cut 2.4.10 just for you :-)

**Comment by ssullivan** [comment]
@ikeforward Out of curiosity... Did you test just making the fields volatile and not using synchronized on those methods?

**Comment by ikeforward** [comment]
@ssullivan Hi, just tested, with this configuration, it is much better and faster than synchronized, but there are still some messages incorrectly cached.
I am broadcasting ids, one id per message. In this test, I see some messages contain multiple ids, for example, "642, 643, 644, 645, 646, 647".

**Comment by thabach** [comment]
@ikeforward Could u please share your test code with us ?

**Comment by ikeforward** [comment]
@jfarcand Hi, thanks for doing it, really appreciated.
@thabach I didn't do anything special, just followed the documentations: subscribe in js, implement AtmosphereHandler and broadcast message through broadcaster. But if you want, I can create a test code for u.

**I just noticed another point**: I am broadcasting ids, one id per message. Sometimes, I broadcast an id (for example "1"), but the message I received is enclosed with square brackets ("[1]"). If is it normal? Do I miss some configurations?

**Comment by thabach** [comment]
@ikeforward please do so.

**Comment by thabach** [comment]
@ikeforward both version, with locks and without (i.e.the volatiles version) - thx.

**Comment by saikiran939** [comment]
adding volatile to message concurrent map will help us ? messages map is already constructed in object creation itself therefore all the threads see the same object but whether the content in the object is visible to other threads or not is a different question. how do you come up that messages are incorrectly cached ? cached here means the messages are not yet delivered and are residing in cache till the expiry ? can you clarify more on the problem ?

**Comment by jfarcand** [comment]
@ikeforward receiving `[]` is expected, it's from the cache and Atmosphere sent them in array instead of one per write

**Comment by ikeforward** [comment]
@saikiran939 Hi, indeed all the threads access the same ConcurrentHashMap object, however, if it is not volatiled, which means the modification is first cached(or saved) thread-locally, then the modification goes to the "main memory", at this moment, other threads can read the modified value, but we have no control on the second step. On the contrary, if it is volatiled, the value of the variable will never be cached thread-locally: all reads and writes will go straight to "main memory".

That means the later thread may read "old" value from "main memory" that has not yet been updated by the previous thread, if it is not volatiled.

**Comment by thabach** [comment]
@ikeforward actually, the [Concurrent Collections](https://docs.oracle.com/javase/tutorial/essential/concurrency/collections.html) do inherently guarantee the happens-before relationship and from that perspective the collection (i.e. the reference to the collection) does not need to be marked `volatile`. In this case volatile only guarantees visibility of the actual reference (between threads), which might well already be guaranteed on a more holistic level (as part of object graph initialization in Atmosphere).

Could you provide us the test code and the modifications you introduced to have your test pass, so we can do further analysis ?

thx, and cheers, Christian.

**Comment by ikeforward** [comment]
@thabach Indeed, I was wrong, here volatile only acts on the reference to the collection, which doesn't make too much sense.

I will create a test code as soon as I can. Is there a place I can upload the code?

**Comment by jfarcand** [comment]
@ikeforward Create a github repo or just gist your code. Thanks!

**Comment by ikeforward** [comment]
@jfarcand @thabach Hi , here is the test code:

**web.xml:**
    <servlet>
        <description>AtmosphereServlet</description>
        <servlet-name>AtmosphereServlet</servlet-name>
        <servlet-class>org.atmosphere.cpr.AtmosphereServlet</servlet-class>
        <init-param>
            <param-name>org.atmosphere.cpr.packages</param-name>
            <param-value>path.to.the.atmosphere.handler.package</param-value>
        </init-param>
        <init-param>
              <param-name>org.atmosphere.interceptor.HeartbeatInterceptor.paddingChar</param-name>
	      <param-value>test</param-value>
        </init-param>
	<init-param>
		<param-name>org.atmosphere.cpr.sessionSupport</param-name>
		<param-value>false</param-value>
	</init-param>
        <async-supported>true</async-supported>
        <load-on-startup>4</load-on-startup>
    </servlet>
    <servlet-mapping>
        <servlet-name>AtmosphereServlet</servlet-name>
        <url-pattern>/atmosphereBroadcast/*</url-pattern>
    </servlet-mapping>

**client side for atmosphere subscription:**
function subscribe(){		
    var request = { url: 'http://127.0.0.1/test-web/atmosphereBroadcast/testChannel',
                    transport : 'long-polling',
                    fallbackTransport: 'long-polling'};
    
    request.onMessage = function(response){
    	if (response.status == 200){
    		console.log(response.responseBody);
    	}
    };

    atmosphere.subscribe(request); 
}

**Atmosphere handler:**
@AtmosphereHandlerService(interceptors = { AtmosphereResourceLifecycleInterceptor.class }, broadcasterCache = TestUUIDBroadcasterCache.class)
public class TestAtmosphereHandler
    implements AtmosphereHandler
{
    @Override
    public void onRequest(AtmosphereResource r)
        throws IOException
    {
        AtmosphereRequest req = r.getRequest();
        if (req.getMethod().equalsIgnoreCase("GET"))
        {
            Broadcaster b = BroadcasterUtility.getBroadcasterFactory().lookup(req.getPathInfo(), true);
            b.addAtmosphereResource(r);
        }
    }

    @Override
    public void onStateChange(AtmosphereResourceEvent event)
        throws IOException
    {
        AtmosphereResource r = event.getResource();
        AtmosphereResponse res = r.getResponse();

        if (event.isSuspended() && event.getMessage() != null)
        {
            String message = event.getMessage().toString();
            res.getWriter().write(message);
            switch (r.transport())
            {
                case JSONP:
                case LONG_POLLING:
                    event.getResource().resume();
                    break;
                case STREAMING:
                    res.getWriter().flush();
                    break;
                case WEBSOCKET:
                default:
                    break;
            }
        }
    }

    @Override
    public void destroy()
    {
    }
}

**The massive broadcasts:**
ServletContext servletContext = ServletContextFactory.getDefault().getServletContext();
AtmosphereFramework framework = (AtmosphereFramework) servletContext.getAttribute("AtmosphereServlet");
Broadcaster b = framework.getBroadcasterFactory().lookup("/testChannel");
for (int index = 0; index < 200; index++)
{
    b.broadcast(Integer.toString(index));
}

**TestUUIDBroadcasterCache.java:**
This class is exactly same as UUIDBroadcasterCache.java, except I put **volatile** to messages and activeClients variables, put methods addToCache, retrieveFromCache and clearCache to **synchronized**.

**Comment by ikeforward** [comment]
@jfarcand @thabach Hi, a stupid question, how to do a pull request? It seems I have to choose a base branch and a head branch, and do a comparison?

**Comment by seamusmac** [comment]
@ikeforward  Easiest is probably to click the "Fork" button on the top right of the project page: https://github.com/Atmosphere/atmosphere
and then make changes in your fork, and commit.
You can make a pull request from that fork.

eg see the "New pull request" button in image in my fork.
![image](https://cloud.githubusercontent.com/assets/43647/24793708/f8ee4144-1b7a-11e7-96fb-745b3b8b13a8.png)

**Comment by ikeforward** [comment]
@jfarcand @seamusmac Done. The pull request is https://github.com/ikeforward/atmosphere/pull/1

**Comment by jfarcand** [comment]
@ikeforward The pull request needs to be on this project, not your :-)

Also can you put your test in Github with a proper pom.xml so we just need  to run it in order to reproduce? That will help getting a fix for the issue. Thanks

**Comment by ikeforward** [comment]
@jfarcand Hi, I investigated a little more, and found something new, maybe it is not a bug from Atmosphere, but my mistake.....
Before, I said when broadcasting a massive number of messages within a short time, we broadcast one id per message, sometimes the received message is the single id, sometimes the received message is enclosed with [], not only enclosed with one id, sometimes with multiple ids(for example, [2] or [16] or [642, 643, 644, 645, 646, 647])
For me, I expect the received message is a single id, not the array.
You said it is expected when Atmosphere sent them in array instead of one per write.  But why? Why when broadcasting one id per message, the received message is an array? I know it is because of multiple threads  are acting on the same object to broadcast messages, but is it a correct behavior in atmosphere? How do we know when the received message is an array or when a string?
Thanks and sorry for the wrong analysis before.

**Comment by saikiran939** [comment]
@ikeforward why not transfer data in JSON ?

**Comment by ikeforward** [comment]
@saikiran939 

Is there a way in Atmosphere to broadcast data in json format? Or I have to manually convert the data to json format?

I am using broadcaster to broadcast message.

**Comment by saikiran939** [comment]
broadcast method takes object as parameter, so you will have to form JSON data you can create JSON data. For example you can use [http://docs.oracle.com/javaee/7/api/javax/json/JsonObject.html](url) to create JSON data.

`org.atmosphere.cpr.DefaultBroadcaster.broadcast(Object)`
