### ISSUE TITLE
How to get Reference to Broadcastor Object

### ISSUE THREAD

**Issue by maddaliravi** [Atmosphere/atmosphere#2263]
How can i get access to Broadcaster object in a specific object.

Point is that , i get a message in a JMS listener.. once i receive the message in JMS listener class, i should be able to broadcast it to all clients/web sockets of a broadcastor. how can i get a reference to that broadcastor ?

**Comment by saikiran939** [comment]
You should be able to get from BroadcasterFactory.lookup() method.
