### ISSUE TITLE
Losing Messages Under Load Using WebSockets...

### ISSUE THREAD

**Issue by jwcarman** [Atmosphere/atmosphere#2264]
We are using Atmosphere 2.4.9 inside a Jetty 8.1.19.v20160209 server (the default one that comes with Karaf).  We also witnessed the behavior using Nettosphere 2.4.10, however.  We have an interesting scenario where we're posting messages to a JAX-RS-based service elsewhere that publishes the messages to an ActiveMQ topic, which is listened to by all of our Atmosphere nodes using a Camel route which does this:

```java
Universe.broadcasterFactory().lookup(channel, true).broadcast(message);
```

Where "channel" is just some arbitrary identifier that we assign elsewhere.  When a new AtmosphereResource is connected, we associate it with its corresponding "channel" like this:

```java
public class MyService extends OnMessage<String> {
    
    @Override
    public void onOpen(AtmosphereResource resource) throws IOException {
        final String channel = ...;
        final BroadcasterFactory factory = resource.getAtmosphereConfig().getBroadcasterFactory();
        final Broadcaster broadcaster = factory.lookup(channel, true);
        resource.setBroadcaster(broadcaster);;
    }

    @Override
    public void onMessage(AtmosphereResponse response, String message) throws IOException {
        response.write(message);
    }
}
```

The Camel route is reporting that it has processed all of the messages.  However, we are witnessing an interesting pattern.  Typically, if we are going to lose messages during our load test (which happens very often), the messages start disappearing during the 15 second "window" of the Gatling test.  Every time, if message are going to disappear, we will see it during that window.  Typically, the messages that disappear during this time frame are the only ones that will go missing, but sometimes we see a couple of stragglers show up later, but for the most part, the missing messages just stop and the test continues as expected with everything delivering perfectly fine.  Another interesting point is that if we run the load test right after the server has started up (no other traffic yet), we typically do not see lost messages during that run.  We are using a SimpleBroadcaster (DefaultBroadcaster was terribly slow, which I'll open another ticket about).  We have tried using the "stock" UUIDBroadcasterCache, a "patched" UUIDBroadcasterCache with the ClientQueue stuff removed, and a custom cache implementation based on Guava's cache support.  We lose messages in all cases.  The number of missing messages is typically pretty low, from a handful to maybe 60 or 70.

**Comment by jfarcand** [comment]
@jwcarman We will need a way to reproduce your issue...best way would be to create a Github project we can close an run to reproduce it. If you can't, you may need to buy some support from http://async-io.org/

Also it seems your messages are getting lost because they expires...have you properly configured the timeout for the `UUIDBroadcasterCache`

**Comment by jwcarman** [comment]
@jfarcand I am actually working on a small sample project right now.  I have not changed UUIDBROADCASTERCACHE_CLIENT_IDLETIME nor UUIDBROADCASTERCACHE_IDLE_CACHE_INTERVAL.  I left them as the defaults.   The behavior that we're seeing is that messages are lost during the first 15 seconds of our test run.  Neither of those timeouts are less than 15 seconds.  Our Gatling test does the following:

- Establish a websocket connection to a "channel".
- Send a message to that channel
- Wait (up to 10 seconds) for the message to arrive on the websocket.  

All of our lost messages manifest as timeouts under this test.  Do you think changing either of the UUIDBroadcasterCache timeout values would help this scenario?  Thanks for looking into this and I hope to have an example project whipped up here very shortly.

**Comment by saikiran939** [comment]
@jwcarman the role of UUIDBroadcasterCache would be less in case of websockets because the connection is always available and the message is sent almost instantly to client. 

Is this happening only in performance test or did you try it manually and firing bulk messages from some other client and see if it is the same behavior ?

**Comment by jwcarman** [comment]
At this point, I am thinking it might be something to do with my test, honestly.  If I send 10,000 message through to one client in a browser and have the JS count up how many it receives, it always gets the messages, no matter what transport I use.  I am going to close this for now.  Thank you for your help and I apologize for the noise :)  Great framework, by the way.  Thanks for your hard work!

**Comment by jwcarman** [comment]
@jfarcand we are still having troubles.  We don't know if it's Gatling or the way we've set things up.  I've created this "gist" of the output from our server:

https://gist.github.com/jwcarman/8137d4d4f648ed706b2b8b44acd7a335

Is there anything glaring in this setup?

**Comment by thabach** [comment]
@jwcarman could you please wrap up a sample that reproduces the issue, so we can have an "educated" look ?
