### ISSUE TITLE
Licensing restrictions?

### ISSUE THREAD

**Issue by BHunter2889** [Atmosphere/atmosphere#2266]
Sorry if this has been answered but I'm new to this framework and I'm just wondering if I use atmosphere for a commercial project, does it require that I publish any of my code that implements it? I've not had a thorough legal education on open source licenses...

**Comment by thomasreiser** [comment]
Check the license included to the repository. You can use it for commercial applications but afaik you need to deliver the sources of the CDDL licensed within your project Installation.

Please check the license text for credible details as I am not a lawyer.
