### ISSUE TITLE
How to send data with first hand shake request with long polling transport.

### ISSUE THREAD

**Issue by xdenser** [Atmosphere/atmosphere#2268]
I need to send some first message as soon as Atmosphere.JS client is connected to the server.
 transport is 'long-polling', all settings are default.

Initially I was using onOpen event to push first message.
Everything was ok until I stumbled on the setup where the server was under strange load balancer (IIS).
The problem there is that loadbalancer sends response as a whole. I.e. first long polling GET request receives ReadyState=2 (Headers Received) at the end of long-polling period (in my case 60 seconds). So  onOpen is called in 60 seconds after the call to atmosphere.subscribe( ...). 
It can be even longer (or forever) depending on server parameters.
So the question is : can i send first push message with first hand shake request?
I have tried to set request.method to 'POST' and  request.data to data, but then I do not get the data on server side (because of protocol interceptor i think).
If I switch off protocol (enableProtocol = false. readResponseHeaders = true)
Then I get different uuid on each request as long-polling with xhr can not read uuid from headers by some reason.

Of course I can patch Astmosphere.JS but I want to keep things compatible for future updates.

I also can return all GET requests w/o call to suspend until first POST message is received, but I need this first  data to be on server ASAP so it will be really better to make it work with first request.

**Comment by jitendra19** [comment]
+

**Comment by jitendra19** [comment]
plus 1

**Comment by saikiran939** [comment]
@xdenser so you mean JS onOpen() is not getting invoked instantly after the connection establishment ?
