### ISSUE TITLE
Error 501 on tomcat 8

### ISSUE THREAD

**Issue by afxgroup** [Atmosphere/atmosphere#2272]
Hello,
i've configured a new server with tomcat 8. On production there is tomcat 7 that has working web sockets.
In this new machine i'm having an error 501 when the client trying to open the web socket.

On the server side when the tomcat starts i have no error at all (on tomcat 7 i have one error..) and it is the web socket related log
`org.atmosphere.cpr.AtmosphereFramework   : Using EndpointMapper class org.atmosphere.util.DefaultEndpointMapper
org.atmosphere.cpr.AtmosphereFramework   : Using BroadcastFilter: org.atmosphere.client.TrackMessageSizeFilter
org.atmosphere.cpr.AtmosphereFramework   : Using BroadcasterCache: org.atmosphere.cache.UUIDBroadcasterCache
org.atmosphere.cpr.AtmosphereFramework   : Default Broadcaster Class: org.atmosphere.cpr.DefaultBroadcaster
org.atmosphere.cpr.AtmosphereFramework   : Broadcaster Shared List Resources: false
org.atmosphere.cpr.AtmosphereFramework   : Broadcaster Polling Wait Time 100
org.atmosphere.cpr.AtmosphereFramework   : Shared ExecutorService supported: true
org.atmosphere.cpr.AtmosphereFramework   : Messaging ExecutorService Pool Size unavailable - Not instance of ThreadPoolExecutor
org.atmosphere.cpr.AtmosphereFramework   : Async I/O Thread Pool Size: 200
org.atmosphere.cpr.AtmosphereFramework   : Using BroadcasterFactory: org.atmosphere.cpr.DefaultBroadcasterFactory
org.atmosphere.cpr.AtmosphereFramework   : Using AtmosphereResurceFactory: org.atmosphere.cpr.DefaultAtmosphereResourceFactory
org.atmosphere.cpr.AtmosphereFramework   : Using WebSocketProcessor: org.atmosphere.websocket.DefaultWebSocketProcessor
org.atmosphere.cpr.AtmosphereFramework   : Invoke AtmosphereInterceptor on WebSocket message true
org.atmosphere.cpr.AtmosphereFramework   : HttpSession supported: false
org.atmosphere.cpr.AtmosphereFramework   : Atmosphere is using org.atmosphere.inject.InjectableObjectFactory for dependency injection and object creation
org.atmosphere.cpr.AtmosphereFramework   : Atmosphere is using async support: org.atmosphere.container.Tomcat7CometSupport running under container: Apache Tomcat/8.0.43
org.atmosphere.cpr.AtmosphereFramework   : Atmosphere Framework 2.4.9 started.`

But on tomcat log i receive the "Websocket protocol not supported" error and the client receive an error 501.

I've tried to remove the atmosphere-compat-tomcat-2.0.1.jar from lib but i receive a class not found exception. I'm using APR with NIO.

What i can check?

**Comment by kylejmcintyre** [comment]
Did you ever get to the bottom of this?

**Comment by afxgroup** [comment]
Nope.. i need to use Tomcat 7 to have no errors. With tomcat 8 i never succeded to use websockets

**Comment by jfarcand** [comment]
Invalid.

**Comment by afxgroup** [comment]
This is not invalid.. This is an issue on tomcat 8 that is not a problem with tomcat 7...

**Comment by jfarcand** [comment]
@afxgroup I have more than 100+ customers on Tomcat 8 using WebSockets :-) I don't think there are issues with Tomcat 8 :-)
