### ISSUE TITLE
After disconnect, heartbeat has a null websocket leading to "No suspended connection available" error

### ISSUE THREAD

**Issue by jpinpin** [Atmosphere/atmosphere#2273]
I've implemented a JavaScript application-layer reconnect mechanism, however, after my reconnect is completed, I'm getting the "No suspended connection available" error message when heartbeats are being sent. Upon inspection, the heartbeat websocket is null due to the disconnect. Is there a way to reset the heartbeat websocket? This occurs in Firefox 53.0.3 but not in Chrome 58.0.3.

**Comment by jpinpin** [comment]
In _push(message), could we add an attempt to re-establish _websocket (if it is null) using _executeWebSocket(webSocketOpened) before failing?

**Comment by jfarcand** [comment]
@jpinpin Contribution welcomed!

**Comment by jfarcand** [comment]
Should be fixed by now
