### ISSUE TITLE
Problem with @ManagedService

### ISSUE THREAD

**Issue by arastoob** [Atmosphere/atmosphere#2279]
Hi all,
I'm new in Atmosphere and I want to integrate Atmosphere with Spring. I followed the famous example of Atmosphere, chat, and I did all the steps. I implemented a ManagedService in my project. The only difference with my project and the samples is in its configuration. I configure my project with a Java class instead of xml. My configuration class is as follows:

`public class SpringWebAppInitializer implements WebApplicationInitializer {

	@Override
	public void onStartup(ServletContext servletContext) throws ServletException {
        AnnotationConfigWebApplicationContext appContext = new AnnotationConfigWebApplicationContext();
        appContext.register(ApplicationContextConfig.class);

        /**
         * registering Kafka's KafkaSender and KafkaReceiver configuration files
         */
        appContext.register(KafkaSenderConfig.class);
        appContext.register(KafkaReceiverConfig.class);

        /**
         * registering spring session configurations
         */
        appContext.register(RedisConfig.class);

        // Manage the lifecycle of the root application context
        servletContext.addListener(new ContextLoaderListener(appContext));

        ServletRegistration.Dynamic dispatcher = servletContext.addServlet(
                "SpringDispatcher", new DispatcherServlet(appContext));
        dispatcher.setLoadOnStartup(1);
        dispatcher.addMapping("/");

            ServletRegistration.Dynamic atmosphereServletRegistration = servletContext.addServlet("AtmosphereServlet", new AtmosphereServlet());
            atmosphereServletRegistration.setLoadOnStartup(0);
            atmosphereServletRegistration.addMapping("/wpsdSocket/*");
            atmosphereServletRegistration.setAsyncSupported(true);
            atmosphereServletRegistration.setInitParameter("org.atmosphere.interceptor.HeartbeatInterceptor.clientHeartbeatFrequencyInSeconds", "10");

    }
}`

and my ManagedService class is as follows:

`@ManagedService(path = "/wpsdSocket", atmosphereConfig = MAX_INACTIVE + "=120000")
public class Socket1 {

    final static Logger logger = LogManager.getLogger(Socket1.class.getName());

    // For demonstrating injection.
    @Inject
    private BroadcasterFactory factory;

    // For demonstrating javax.inject.Named
    @Inject
    @Named("/wpsdSocket")
    private Broadcaster broadcaster;

    @Inject
    private AtmosphereResource r;

    @Inject
    private AtmosphereResourceEvent event;

    @Heartbeat
    public void onHeartbeat(final AtmosphereResourceEvent event) {
        logger.info("Heartbeat send by: " + event.getResource());
    }

    @Ready
    public void onReady() {
        logger.info("onReady");
        logger.info("Browser connected: " + r.uuid());
        logger.info("BroadcasterFactory used: " + factory.getClass().getName());
        logger.info("Broadcaster injected: " + broadcaster.getID());
      }

    @Disconnect
    public void onDisconnect() {
        if (event.isCancelled()) {
            logger.info("Browser unexpectedly disconnected: " + event.getResource().uuid());
        } else if (event.isClosedByClient()) {
            logger.info("Browser closed the connection: " + event.getResource().uuid());
        }
    }

    /**
     * Simple annotated class that demonstrate how {@link org.atmosphere.config.managed.Encoder} and {@link org.atmosphere.config.managed.Decoder
     * can be used.
     *
     * @param message an instance of {@link Message}
     * @return
     * @throws IOException
     */
    @org.atmosphere.config.service.Message(encoders = {JacksonEncoder.class}, decoders = {JacksonDecoder.class})
    public Message onMessage(Message message) throws IOException {
        logger.info("onMessage");
        logger.info("message: " + message.toString());
        logger.info(message.getAuthor() + " just sent " + message.getMessage());
        return message;
    }

}`

My problem is that the websocket request reaches the "onReady" method and the logs are done correctly, but the request never reaches the "onMessage" method, i.e., when I try to connect and send a message, non of the logs in onMessage class are done. 
I don't know what is wrong with my codes, but it's making me crazy. Please help me what to do.

**Comment by shashankn91** [comment]
Did you find the solution ? I am facing the same issue .
