### ISSUE TITLE
Jetty Websocket support broken in 2.4.x for Jetty < 9.4

### ISSUE THREAD

**Issue by kylejmcintyre** [Atmosphere/atmosphere#2286]
https://github.com/Atmosphere/atmosphere/commit/9fd3d45c01b0c52d57ddfb6664eb6bb67c072410

The above changes made it so that both Jetty9AsyncSupportWithWebSocket and Jetty93AsyncSupportWithWebSocket rely on a constructor on WebSocketServerFactory that doesn't appear to be available until Jetty 9.4. @shanielh - any chance you can fix?

**Comment by shanielh** [comment]
Hey, I'm sorry, I guess the only change that needs to be done is in [`modules/cpr/src/main/java/org/atmosphere/container/Jetty9AsyncSupportWithWebSocket.java:45`](https://github.com/Atmosphere/atmosphere/commit/9fd3d45c01b0c52d57ddfb6664eb6bb67c072410#diff-2901051e3e16a93a323ee0aa9cd4e9f4R45) - to remove the first argument to the c'tor. Can you create a pull request?

**Comment by kylejmcintyre** [comment]
I'm still confused actually because your commit says you added support for Jetty 9.3, but actually it seems like you added support for Jetty 9.4? Do we need to rename Jetty93AsyncSupport...?

**Comment by shanielh** [comment]
@kylejmcintyre I'm pretty sure this C'tor was supported in Jetty 9.3, I guess that it was in some minor fix in Jetty 9.3

**Comment by jfarcand** [comment]
@shanielh If you have the cycle, do me a favor and resend a pull request with the fix. Thanks!
