### ISSUE TITLE
Memory leak in DefaultBroadcaster due to usage of ConcurrentLinkedQueue

### ISSUE THREAD

**Issue by SoftMadHatter** [Atmosphere/atmosphere#2290]
It seems there is an issue in ConcurrentLinkedQueue in jdk <1.8u102 that can cause an OutOfMemoryError (.remove(object) keeps the node with null item).

The resources field of DefaultBroadcaster uses a ConcurrentLinkedQueue, so when a lot of resources are  on the same broadcaster it causes an OutOfMemoryError.
(in my case ~46 000 000 empty nodes corresponding to the "removed" resources)

Is it possible to use a different kind of queue/list ?

Bugs in JDKs : https://bugs.openjdk.java.net/browse/JDK-8054446, http://bugs.java.com/bugdatabase/view_bug.do?bug_id=8054446

**Comment by jfarcand** [comment]
@SoftMadHatter Contribution welcomed
