### ISSUE TITLE
Camel Spring Boot Atmosphere Websocket problem with AsyncSupport

### ISSUE THREAD

**Issue by pkletsko** [Atmosphere/atmosphere#2291]
Hi,

I am trying to create a simple example for our small community with combination of Camel+Spring Boot+Atmosphere Websocket and it doesn't work. 

Link to the example:
https://github.com/pkletsko/spring-boot-camel-atmosphere-websocket

Link to the Issue:
https://github.com/pkletsko/spring-boot-camel-atmosphere-websocket/issues/1

WBR,
Pavlo

**Comment by pkletsko** [comment]
I have fixed this issue .
Camel component has been updated.

https://issues.apache.org/jira/browse/CAMEL-11725

Thus after release of camel 2.19.3 should work.

**Comment by jfarcand** [comment]
@pkletsko Just for your information, there where no change in initialization. What makes you thinks that?
