### ISSUE TITLE
Memory leak after shutdown of Atmosphere

### ISSUE THREAD

**Issue by jacobilsoe** [Atmosphere/atmosphere#2293]
I am currently using Atmosphere 2.3.8 in an application deployed in WildFly 10.1.0.Final. When I undeploy my application, it seems Atmosphere is leaking memory. I have investigated a bit and I can make the leaks go away if I extend `org.atmosphere.cpr.AtmosphereFramework.destroy` to also call `Runtime.getRuntime().removeShutdownHook(shutdownHook);`, null the fields in `org.atmosphere.cpr.Universe` and set `ServletContextFactory.servletContextFactory` to null. I can see that the shutdown hook issue seems to have been fixed in the most recent Atmosphere code whereas the other two issues are not.

**Comment by jfarcand** [comment]
@jacobilsoe Pull request welcome! Once done I can cut a new release for your team.

**Comment by jfarcand** [comment]
@jacobilsoe Pull request welcomed...please try with the latest 2.4.20
