### ISSUE TITLE
Use http connection on IBM WebShpere 9

### ISSUE THREAD

**Issue by hustleone** [Atmosphere/atmosphere#2297]
Hello!

We have vaadin 7.6.3 web application which is building by jdk6 and deploying to IBM WAS 8 jdk 6, javax webSocket v.3.
Our goal is to use http connection with client, so we have 'org.atmosphere.usewebsocketandservlet3 = false' at our web.xml

.war file contains: atmosphere-runtime-2.2.7.vaadin1.jar

We'd like to move to jdk 8.121 and IBM WAS 9 jdk 8 (javax webSocket v.3.1), but while testing found an issue.

Changing paramater 'org.atmosphere.usewebsocketandservlet3' to 'org.atmosphere.usewebsocketandservlet3.1 = false' does not gives us solution - our web application still connects via WebSocket connection.

Also i tried this addition serlvet listener https://github.com/Atmosphere/atmosphere/wiki/Enabling-HttpSession-Support - no result.

Could you please tell me about compatibility between 3.1 serlvet framework and atmosphere framework?
Thank you.

**Comment by jfarcand** [comment]
Vaadin uses a fork of Atmosphere...use their forum for such question
