### ISSUE TITLE
org.atmosphere.cpr.AtmosphereFramework#destroy() leaking threads

### ISSUE THREAD

**Issue by brunojcm** [Atmosphere/atmosphere#2311]
I'm currently investigating the cause of https://github.com/vaadin/framework/issues/10532 and I think it's an Atmosphere issue.

Consider this destroy method on the 2.4.x branch:

    public AtmosphereFramework destroy() {
        ...
        // Invoke ShutdownHook.
        config.destroy();

        ...
        ExecutorsFactory.reset(config);

        ...
        return this;
    }

and the `org.atmosphere.util.ExecutorsFactory#reset(AtmosphereConfig)` as being:

    public final static void reset(AtmosphereConfig config) {
        ExecutorService e = (ExecutorService) config.properties().get(ASYNC_WRITE_THREAD_POOL);
        if (e != null) {
            e.shutdown();
        }
        config.properties().remove(ASYNC_WRITE_THREAD_POOL);

        e = (ExecutorService) config.properties().get(SCHEDULER_THREAD_POOL);
        if (e != null) {
            e.shutdown();
        }
        config.properties().remove(SCHEDULER_THREAD_POOL);

        e = (ExecutorService) config.properties().get(BROADCASTER_THREAD_POOL);
        if (e != null) {
            e.shutdown();
        }
        config.properties().remove(BROADCASTER_THREAD_POOL);
    }

And finally `org.atmosphere.cpr.AtmosphereConfig#destroy()` as:

    protected void destroy() {
        for (ShutdownHook h : shutdownHooks) {
            try {
                h.shutdown();
            } catch (Exception ex) {
                logger.warn("", ex);
            }
        }
        properties.clear();
        shutdownHooks.clear();
        startUpHook.clear();
        atmosphereHandlerConfig.clear();
    }

As we can see, `org.atmosphere.cpr.AtmosphereConfig#destroy()` empties the `properties`  map **before** `org.atmosphere.util.ExecutorsFactory#reset(AtmosphereConfig)` can use it to locate and shutdown the `ExecutorService`s, causing a thread leak that can lead to huge memory leaks (as detailed it the Vaadin mentioned thread).

Can you please look into that?

**Comment by brunojcm** [comment]
Nice, thanks! :)

Just one question: where `properties.clear();` is being executed now? It seems to be completely removed.

**Comment by jfarcand** [comment]
@brunojcm Good catch. Just re-added it.
