### ISSUE TITLE
Path parameters broken with @AtmosphereService annotation

### ISSUE THREAD

**Issue by baconmania** [Atmosphere/atmosphere#2315]
Path parameters don't seem to work with the `@AtmosphereService` annotation. Looking at the `jersey2-chat` example in atmosphere-samples, changing the path [here](https://github.com/Atmosphere/atmosphere-samples/blob/master/samples/jersey2-chat/src/main/java/org/atmosphere/samples/chat/jersey/Jersey2Resource.java#L43) to `/chat/{arg}` results in the following behavior from the server:

```
➜  ~ wscat -c 'ws://localhost:8080/chat/test'
connected (press CTRL+C to quit)
< ERROR: 404:Not Found
< ERROR: 404:Not Found
```

**Comment by pedrohdz** [comment]
I am experiencing the same issue here.  Has anyone resolved this, found a work around?

**Comment by jfarcand** [comment]
@baconmania @pedrohdz The `{arg}` needs to be set via the `Path` annotation, not that value.

**Comment by pedrohdz** [comment]
Worked!  Thanks!
