### ISSUE TITLE
404 after upgrade of atmosphere-runtime from 2.4.20 to 2.4.21

### ISSUE THREAD

**Issue by cthiebaud** [Atmosphere/atmosphere#2317]
the url defined as: 

@ManagedService(path = "/patata/{dagName}/patati/{scope}") 

(line 26 of https://github.com/aequologica/dagr/blob/develop/dagr-vebchar/src/main/java/net/aequologica/neo/dagr/websocket/DagSocket.java)

returns 404 after the upgrade of atmosphere-runtime from 2.4.20 to 2.4.21 (and not changing anything else)

no clue why, I stay on 2.4.20, just FYI

thanks
Christophe

**Comment by jfarcand** [comment]
Oups...let me investigate ASAP

**Comment by cthiebaud** [comment]
Yeah, I had a rapid look at the commit diff between the two releases, and this one sounds related. Sorry, it is beyond my skills to investigate. Thanks for the quick reply. Tell me if I can contribute in any way.

**Comment by jfarcand** [comment]
@cthiebaud Thanks! Will look as soon as I have the cycle.

**Comment by jfarcand** [comment]
@cthiebaud Can you try 2.4.23-SNAPSHOT once you have a chance?

**Comment by cthiebaud** [comment]
from here I guess ?
https://oss.sonatype.org/content/repositories/snapshots/org/atmosphere/atmosphere-runtime/2.4.23-SNAPSHOT/

ok, I'll give it a try

**Comment by jfarcand** [comment]
Fixed in `.22` and up
