### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by chukcha123** [Atmosphere/atmosphere#2318]
Sometimes (very rare) our web application starts to have a high CPU usage.
We use push functionality with Atmosphere.
After tracing the problem I found the following.
User connects with long-polling and receives a push message (usually a big cached sequence of messages).
The following error is displayed in the log:
   

```
AtmosphereResource 560084e2-2965-4e09-8c3a-e1077f17118b is not suspended. If cached messages exists, this may cause unexpected situation
Sending cached message "xxxxx"
```

folowed by:

```
Duplicate resource 560084e2-2965-4e09-8c3a-e1077f17118b
Cached message found, not suspending 560084e2-2965-4e09-8c3a-e1077f17118b
Unable to add AtmosphereResource 560084e2-2965-4e09-8c3a-e1077f17118b
Cached message found, not suspending 560084e2-2965-4e09-8c3a-e1077f17118b

```

and the CPU usage goes high.
The resource is always suspended in my application.

In the tomcat console is visible that the following request to my atmosphere endpoint appears and disapears non-stop even when the user is logoffed: 

`GET /xxxxxxsrv/643EB3437B93C51898EEBA8DD2C9C82EBE346?X-Atmosphere-tracking-id=560084e2-2965-4e09-8c3a-e1077f17118b&X-Atmosphere-Framework=2.2.12-javascript&X-Atmosphere-Transport=long-polling&X-Atmosphere-TrackMessageSize=true&Content-Type=application%2Fjson&X-atmo-protocol=true&_=1517910619585 HTTP/1.1
`
Also checking with visualVM I see that this request regulary appears/disappears and occupies the threads:

![problem_issue](https://user-images.githubusercontent.com/37155191/37293577-f72c43ac-2613-11e8-85e1-520896b88e58.png)
 
Do you know already this issue and how can I fix it (or workarround it) ?

**Comment by jfarcand** [comment]
I am heavily using Atmosphere in production and never see something like that. I suspect it's related to Tomcat and not Atmopshere as the underlying I/O is done by Tomcat. Which version of Tomcat are you using? 

The only way I will be able to help is if you share a test case on github that reproduce the issue. If you can't, consider looking at the professional service options on http://Async-Io.org (yes I know if commercial support :-))

**Comment by chukcha123** [comment]
The tomcat version is 7.0.70 running with java 1.7.0_80 and Atmosphere Framework 2.2.8
In internet I found also another users having troubels with similar problems: https://github.com/vaadin/framework/issues/10532

Is there a way to workaround it, for example to identify this case and may be to close the hanging request ?
