### ISSUE TITLE
HeartbeatInterceptor does not work with GET method

### ISSUE THREAD

**Issue by fenik17** [Atmosphere/atmosphere#2325]
`HeartbeatInterceptor` skips the content of the GET method:
https://github.com/Atmosphere/atmosphere/blob/c2e67ed7a8c69ac164af4da58ff7f05b35a6943a/modules/runtime/src/main/java/org/atmosphere/interceptor/HeartbeatInterceptor.java#L197

Because of this, the client's heartbeat message (with 'X' in content) reaches the handler.
At the moment I use workaround with an additional interceptor:
```java
public class HeartbeatWorkaroundInterceptor extends AtmosphereInterceptorAdapter {
    @Override
    public Action inspect(AtmosphereResource r) {
        r.getRequest().method("POST");
        return Action.CONTINUE;
    }

    @Override
    public PRIORITY priority() {
        return InvokationOrder.BEFORE_DEFAULT;
    }
}
```

But I think this is an issue, and `HeartbeatInterceptor` should not take into account the method type. Either I do not understand something...

**Comment by jfarcand** [comment]
@fenik17 The client is sending a `POST` to the client with the body set to `X`. `atmosphere.js` does a `GET` for suspending its connection (receive push), and then use `POST` for the heart.

**Comment by fenik17** [comment]
To prevent the connection breaking we added an init parameter:
`org.atmosphere.interceptor.HeartbeatInterceptor.clientHeartbeatFrequencyInSeconds = 30`

But after that our handler began to receive messages with 'X' in the body (with the direct connection, or proxied by nginx).

For the tests I use this client script: https://github.com/Atmosphere/atmosphere-samples/blob/master/samples/websocket-chat/src/main/webapp/javascript/application.js
I tried with different browsers.

Some details:
Atmosphere Framework 2.4.24
atmosphere.js 2.3.5
Jetty 9.4.8.v20171121 (as part of the Dropwizard 1.2.4)

```
org.atmosphere.cpr.broadcaster.maxProcessingThreads = -1
org.atmosphere.cpr.broadcaster.shareableThreadPool = true
org.atmosphere.cpr.defaultContentType = application/json
org.atmosphere.interceptor.HeartbeatInterceptor.heartbeatFrequencyInSeconds = 90
org.atmosphere.interceptor.HeartbeatInterceptor.clientHeartbeatFrequencyInSeconds = 30
org.atmosphere.util.IOUtils.readGetBody = true
org.atmosphere.websocket.messageContentType = application/json
org.atmosphere.websocket.WebSocketProtocol = org.atmosphere.websocket.protocol.StreamingHttpProtocol
...
Atmosphere is using async support: org.atmosphere.container.JSR356AsyncSupport running under container: jetty/9.4.8.v20171121 using javax.servlet/3.0 and jsr356/WebSocket API
...
 interceptors
	0: org.atmosphere.interceptor.CorsInterceptor
	1: com.navixy.apiserver.ws.handle.HeartbeatWorkaroundInterceptor
	2: org.atmosphere.interceptor.IdleResourceInterceptor
	3: org.atmosphere.interceptor.NginxInterceptor
	4: org.atmosphere.interceptor.CacheHeadersInterceptor
	5: org.atmosphere.interceptor.PaddingAtmosphereInterceptor
	6: org.atmosphere.interceptor.AndroidAtmosphereInterceptor
	7: org.atmosphere.interceptor.HeartbeatInterceptor
	8: org.atmosphere.interceptor.SSEAtmosphereInterceptor
	9: org.atmosphere.interceptor.JSONPAtmosphereInterceptor
	10: org.atmosphere.interceptor.JavaScriptProtocol
	11: org.atmosphere.interceptor.WebSocketMessageSuspendInterceptor
	12: org.atmosphere.interceptor.OnDisconnectInterceptor
```

**Comment by jfarcand** [comment]
@fenik17 OK you are right. Can you do a pull request? Thanks!

**Comment by fenik17** [comment]
@jfarcand sure. I'll do later.

**Comment by jfarcand** [comment]
@fenik17 Do you need an official release? Also can you drop me an email @ `jfarcand@apache.org` ? I would like to chat with you on Atmosphere.
