### ISSUE TITLE
Can not start nettosphere 2.4.10 + atmosphere 2.4.24 + jetty 9.4

### ISSUE THREAD

**Issue by max-grigoriev** [Atmosphere/atmosphere#2328]
Hi,
I'm migrating the project to jetty 9.4.
I can not start web socket server because When `Jetty9AsyncSupportWithWebSocket` tries to start `WebSocketServerFactory`, it wants to get executor from context on start:
```
@Override
    protected void doStart() throws Exception
    {
        ...
        if(this.executor == null && context != null)
        {
            ContextHandler contextHandler = ContextHandler.getContextHandler(context);
            this.executor = contextHandler.getServer().getThreadPool();
        }
      ...
      super.doStart();
    }
```

But `ContextHandler.getContextHandler(context);` returns `null` because nettosphere passes own ServerContext nettosphere-2.4.10-sources.jar!/org/atmosphere/nettosphere/BridgeRuntime.java:207  :
```
 ServletContext ctx = (ServletContext) Proxy.newProxyInstance(BridgeRuntime.class.getClassLoader(), new Class[]{ServletContext.class},
                new InvocationHandler() {
                    @Override
                    public Object invoke(Object proxy, Method method, Object[] args) throws Throwable {
                        try {
                            Method stub = Context.class.getMethod(method.getName(), method.getParameterTypes());
                            if (stub != null) {
                                return stub.invoke(context, args);
                            } else {
                                logger.trace("Method {} not supported", method.getName());
                                return null;
                            }
                        } catch (NoSuchMethodException ex) {
                            logger.trace("Method {} not supported", method.getName());
                            return null;
                        }
                    }
                });
```

Is there a workaround to use nettosphere 2.4.10 + atmosphere 2.4.24 + jetty 9.4

**Comment by jfarcand** [comment]
@max-grigoriev You can't use both runtime at the same time...either you run Atmosphere on Netty or run on Jetty. Why would you use Netty on top of Jetty?

**Comment by max-grigoriev** [comment]
> Why would you use Netty on top of Jetty?

here's stacktrace when I start `nettosphere:
` 
at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolveWebSocket(DefaultAsyncSupportResolver.java:308)
! at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolve(DefaultAsyncSupportResolver.java:294)
! at org.atmosphere.cpr.AtmosphereFramework.autoDetectContainer(AtmosphereFramework.java:2088)
! at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:914)
! at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:838)
! at org.atmosphere.nettosphere.BridgeRuntime.<init>(BridgeRuntime.java:227)
! at org.atmosphere.nettosphere.Nettosphere.<init>(Nettosphere.java:74)
! at org.atmosphere.nettosphere.Nettosphere.<init>(Nettosphere.java:59)
! at org.atmosphere.nettosphere.Nettosphere$Builder.build(Nettosphere.java:188)
`

And Atmosohere automatically detects Jetty. How can I start under netty?

**Comment by fenik17** [comment]
@max-grigoriev as @jfarcand said, don't use Nettosphere with Jetty.

**Comment by max-grigoriev** [comment]
@fenik17 so is it impossible to have some services running under jetty as plain old REST endpoint and have Nettosphere which is running in the same service? 

P.S. container class should be printed when nettosphere configuration is OK:
`Atmosphere is using async support: org.atmosphere.container.NettyCometSupport running under container: Nettosphere/2.0` ?

**Comment by fenik17** [comment]
Theoretically, this is possible. But IIUC, Atmosphere is not designed for multiple containers in classpath. It use the first found container.
