### ISSUE TITLE
Support for tomcat 9.x

### ISSUE THREAD

**Issue by yadavamit** [Atmosphere/atmosphere#2332]
Please add the support for tomcat 9.x. As of now tomcat 9.x is not in the supported  webservers list.

https://github.com/Atmosphere/atmosphere/wiki/Supported-WebServers-and-Browsers

**Comment by yadavamit** [comment]
Atmosphere version i am using is 2.4.

**Comment by jfarcand** [comment]
Tomcat 8.5 and up is listed on that page.
