### ISSUE TITLE
AtmosphereHandler not detected - even with package configured in web.xml

### ISSUE THREAD

**Issue by ak80** [Atmosphere/atmosphere#2346]
I have a Java Web-App running fine in tomcat when deployed as a war file. When I run it through the tomcat maven plugin, with the "exploded" war file I get a

```No AtmosphereHandler or WebSocketHandler installed. Adding a default one.```

I have the dependency 
```
        <dependency>
            <groupId>eu.infomas</groupId>
            <artifactId>annotation-detector</artifactId>
            <version>3.0.1</version>
        </dependency>
```
and see ```Atmosphere is using org.atmosphere.cpr.DefaultAnnotationProcessor for processing annotation``` but my handler, annotated with the *ManagedService* annotation is not picked up. 

I even configured the package in web.xml
```
        <init-param>
            <param-name>org.atmosphere.cpr.packages</param-name>
            <param-value>de.newlift.elevision.server.service.atmosphere</param-value>
        </init-param>
```

This doesn't help. I am using Version 2.4.14

Any ideas?

**Comment by ak80** [comment]
It seems my issue is related to #1159 but I can't figure out how that helps me. I am using Servlet 3.0 and have defined my package in web xml. Still, it is not picked up.

Any help would be greatly appreciated

**Comment by yfraquelle** [comment]
It works when the project is deployed as a jar file.

**Comment by jarry284** [comment]
hi, i get the same situation when use idea via maven plugin(tomcat7:run) run the project,but use eclipse run fine. finally i found it's a idea config problem. here is the o
ption,you can hava a try.
![1568254217(1)](https://user-images.githubusercontent.com/23185962/64748747-cb31a980-d545-11e9-8e89-63eff498bb31.jpg)
