### ISSUE TITLE
Atmosphere resource is not closed if client abort connection

### ISSUE THREAD

**Issue by DarrMirr** [Atmosphere/atmosphere#2348]
Hello!

I have spring boot 1.5.14 application and use atmosphere framework to notify clients about events. Sometimes connection is aborted unexpectedly by client or proxy server. Tomcat close socket and log this action. But atmosphere resource is still open on server side. When server try to write something to such resource I have `java.io.IOException: Broken pipe`

My project configuration is the same as [Spring Boot Atmosphere Sample](https://github.com/Atmosphere/atmosphere-samples/tree/master/samples/spring-boot-sample-atmosphere)

**Steps to reproduce error:**
1. Download [Spring Boot Atmosphere Sample](https://github.com/Atmosphere/atmosphere-samples/tree/master/samples/spring-boot-sample-atmosphere)
2. Open project in IDE
3. Add lines to application.properties:
`logging.level.org.atmosphere.config:trace
logging.level.org.atmosphere.cpr:trace
logging.level.org.atmosphere.container:trace
logging.level.org.apache:debug`
4. Run Application
5. Open linux terminal
6. Send curl request:
`curl "http://localhost:8080/chat?X-Atmosphere-tracking-id=0&X-Atmosphere-Framework=2.2.8-javascript&X-Atmosphere-Transport=streaming&X-Atmosphere-TrackMessageSize=false&Content-Type=application/json&X-atmo-protocol=true"`
7. Press Ctrl+C in terminal after a few seconds
8. Wait for HeartbeatInterseptor trying to write to closed resource.

**Expected result:**
- Atmosphere resource is closed immediately when client abort connection

**Actual result:**
- Atmosphere resource is not closed. Exception `java.io.IOException: Broken pipe` is appeared

My project recently migrate from Java EE + Glassfish 3 to Spring Boot + Tomcat. This error no reproduce on Glassfish 3. Atmosphere used async support: org.atmosphere.container.GrizzlyCometSupport under container: GlassFish Server Open Source Edition 3.1.2.2. Now Atmosphere use async support: org.atmosphere.container.JSR356AsyncSupport under container: Apache Tomcat/8.0.32 using javax.servlet/3.0 and jsr356/WebSocket API

**Comment by DarrMirr** [comment]
Hi there!

Using websocket is the best way to resolve this issue. Unfortunately, there are a lot of clients which have old versions of software. And I have to support backward compatibility. I found out solely workaroud for this issue. Workaround have different implementation for Jetty and Tomcat.

Let's begin with Jetty.

Firstly, I create class which extend `org.eclipse.jetty.server.handler.AbstractHandler` and override handle() method. Here is code:

    @Override
    public void handle(String s, Request request, HttpServletRequest httpServletRequest, HttpServletResponse httpServletResponse) throws IOException, ServletException {
        Object transport = request.getHttpChannel().getEndPoint().getTransport();
        if (transport instanceof SocketChannel) {
            SocketChannel socketChannel = (SocketChannel) transport;
            httpServletRequest.setAttribute("BrokenPipeChecker", new BrokenPipeChecker(socketChannel));
        }
    }

I retrieve transport object from request and check for instance of SocketChannel class. And set `BrokenPipeChecker` attribute to request. BrokenPipeChecker class keep SocketChannel object as field and have only one method as follow:

    @Override
    public boolean evaluate(Object o) {
        try {
            if (socketChannel.isOpen()) {
                int i = socketChannel.read(ByteBuffer.allocate(1));
                if (i == -1) {
                    throw new IOException("client abort connection");
                }
                return true;
            }
        } catch (IOException e) {
            logger.error("", e);
        }
        return false;
    } 

Finally, I create class which extend `PerRequestBroadcastFilter`. I check for half-closed connection before send notification about event in application. Here is code:

    @Override
    public BroadcastAction filter(String s, AtmosphereResource atmosphereResource, Object originalMessage, Object message) {
        AtmosphereRequest request = atmosphereResource.getRequest();
        Predicate brokenPipeChecker = (Predicate) request.getAttribute("BrokenPipeChecker");
        if (brokenPipeChecker == null || brokenPipeChecker.evaluate(request)) {
            return new BroadcastAction(BroadcastAction.ACTION.CONTINUE, message);
        }
        return new BroadcastAction(BroadcastAction.ACTION.ABORT, message);
    }

Workaround for Tomcat is more complicated than Jetty one. I have to create class which extend `org.apache.coyote.http11.Http11Processor` and override service() method as follow:

    @Override
    public AbstractEndpoint.Handler.SocketState service(SocketWrapperBase<?> socketWrapper) throws IOException {
        getRequest().setAttribute("BrokenPipeChecker", brokenPipeChecker);
        return super.service(socketWrapper);
    }

Variable `brokenPipeChecker` is instance of inner class. Here is code:

    private class BrokenPipeChecker implements Predicate {

        @Override
        public boolean evaluate(Object o) {
            try {
                if (getSocketWrapper().getSocket() instanceof NioChannel) {
                    NioChannel channel = (NioChannel) getSocketWrapper().getSocket();
                    if (channel.isOpen()) {
                        int i = channel.getIOChannel().read(ByteBuffer.allocate(1));
                        if (i == -1) {
                            throw new IOException("client abort connection");
                        }
                        return true;
                    }
                }
            } catch (IOException e) {
                setErrorState(ErrorState.CLOSE_NOW, e);
            }
            return false;
        }
    }

Next, I have to create another class which extend `org.apache.coyote.http11.Http11NioProtocol` and override createProcessor() method as follow:

    @Override
    protected Processor createProcessor() {
        Http11Processor processor = new AntiHalfConnectionHttp11Processor(this.getMaxHttpHeaderSize(), this.getAllowHostHeaderMismatch(), this.getRejectIllegalHeaderName(), this.getEndpoint(), this.getMaxTrailerSize(), new HashSet<>(Arrays.asList(getAllowedTrailerHeaders().split(","))), this.getMaxExtensionSize(), this.getMaxSwallowSize(), null, this.getSendReasonPhrase(), getRelaxedPathChars(), getRelaxedQueryChars());
        processor.setAdapter(this.getAdapter());
        processor.setMaxKeepAliveRequests(this.getMaxKeepAliveRequests());
        processor.setConnectionUploadTimeout(this.getConnectionUploadTimeout());
        processor.setDisableUploadTimeout(this.getDisableUploadTimeout());
        processor.setCompressionMinSize(this.getCompressionMinSize());
        processor.setCompression(this.getCompression());
        processor.setNoCompressionUserAgents(this.getNoCompressionUserAgents());
        processor.setCompressibleMimeTypes(this.getCompressibleMimeTypes());
        processor.setRestrictedUserAgents(this.getRestrictedUserAgents());
        processor.setMaxSavePostSize(this.getMaxSavePostSize());
        processor.setServer(this.getServer());
        processor.setServerRemoveAppProvidedValues(this.getServerRemoveAppProvidedValues());
        return processor;
    }

Unfortunately, I have to lost support of http/2 protocol because of field have private access modifier in `org.apache.coyote.AbstractProtocol` class. But it suit to me due to using http/1.1 one. Finally, I set custom protocol in tomcat options. Code of `PerRequestBroadcastFilter` became the same.

**Comment by jfarcand** [comment]
@DarrMirr Any reason to close the issue?

**Comment by DarrMirr** [comment]
@jfarcand, I think it is not issue atmosphere framework. Glassfish have Comet programming technique and I used it to deploy my application. And there was no problem with half open connection. When I started migrate to Spring Boot I faced with problem which I described above. Recently, I found out workaround and closed issue.
