### ISSUE TITLE
Socket connection using Spring boot and socket.io

### ISSUE THREAD

**Issue by DominikSammerLocoso** [Atmosphere/atmosphere#2351]
Hey there,

Right now I am trying to implement an application, that creates a socket connection between an Angular application and a spring boot server. 
The actual problem is that my client is not able to establish a connection to the backend application. 
What the client is trying to is connecting to the server using localhost:4200/socket.io which is the port on which it running but what it should do is connecting to localhost:8080/chat.

What I did was the following:
Creating the spring boot application via:
`@Configuration
@EnableAutoConfiguration
public class AtmosphereApplication {
    private static Logger logger = LoggerFactory.getLogger(AtmosphereApplication.class);

    @Bean
    public EmbeddedAtmosphereInitializer atmosphereInitializer() {
        return new EmbeddedAtmosphereInitializer();
    }

    @Bean
    public ServletRegistrationBean atmosphereServlet() {
        // Dispatcher servlet is mapped to '/home' to allow the AtmosphereServlet
        // to be mapped to '/chat'
        ServletRegistrationBean registration = new ServletRegistrationBean(
                new AtmosphereServlet(), "/chat/*");
        registration.addInitParameter("org.atmosphere.cpr.packages", "sample");
        registration.addInitParameter("org.atmosphere.interceptor.HeartbeatInterceptor"
                + ".clientHeartbeatFrequencyInSeconds", "10");
        registration.setLoadOnStartup(0);
        // Need to occur before the EmbeddedAtmosphereInitializer
        registration.setOrder(Ordered.HIGHEST_PRECEDENCE);
        logger.info("Finished");
        return registration;
    }

    private static class EmbeddedAtmosphereInitializer extends ContainerInitializer
            implements ServletContextInitializer {

        public void onStartup(ServletContext servletContext) throws ServletException {
            onStartup(Collections.<Class<?>> emptySet(), servletContext);
        }

    }

    public static void main(String[] args) throws Exception {
        SpringApplication.run(AtmosphereApplication.class, args);
    }
}`

Implementing a service with:
`@ManagedService(path = "/chat")
public class ChatService {
    private final Logger logger = LoggerFactory.getLogger(ChatService.class);

    @Ready
    public void onReady(final AtmosphereResource resource) {
        this.logger.info("Connected", resource.uuid());
    }

    @Disconnect
    public void onDisconnect(AtmosphereResourceEvent event) {
        this.logger.info("Client {} disconnected [{}]", event.getResource().uuid(),
                (event.isCancelled() ? "cancelled" : "closed"));
    }

    @org.atmosphere.config.service.Message()
    public void onMessage(AtmosphereResource resource, String message) throws IOException {
        this.logger.info("Author {} sent message {}", message);
        resource.getResponse().write(message + " from server");
    }

}
`

And now the client side I connect using the following method:
`
@Injectable()
export class WebSocketService {

  private socket;

  constructor() {

  }

  connect(): Rx.Subject<MessageEvent> {
    console.log("try to connect")
    this.socket = io("http://127.0.0.1:8080/chat");

    // We define our observable which will observe any incoming messages
    // from our socket.io server.
    let observable = new Observable(observer => {
      this.socket.on('message', (data) => {
        console.log("Received message from Websocket Server")
        observer.next(data);
      })
      return () => {
        this.socket.disconnect();
      }
    });

    // We define our Observer which will listen to messages
    // from our other components and send messages back to our
    // socket server whenever the `next()` method is called.
    let observer = {
      next: (data: Object) => {
        this.socket.emit('message', JSON.stringify(data));
      },
    };

    // we return our Rx.Subject which is a combination
    // of both an observer and observable.
    return Rx.Subject.create(observer, observable);
  }
}`

The WebSocketService is called when loading the page.

Since I wrote "this.socket = io("http://127.0.0.1:8080/chat");" I am expecting to access my server chat service that I declared with "@ManagedService(path = "/chat")". I do not understand why it tries to connect to localhost:4200/socket.io when I am loading the page.

**Comment by jfarcand** [comment]
Socket IO is no longer supported.
