### ISSUE TITLE
Broadcast to single client over long-polling fails

### ISSUE THREAD

**Issue by meszarv** [Atmosphere/atmosphere#2361]
Hi, 
 I found an issue in long polling transport when broadcasting to single client using the 
`broadcaster.broadcast(msg,ar);`

I have managed to reproduce this issue by modifying the atmosphere-chat sample: 
https://gist.github.com/meszarv/adbec9e0ce3e8b788380e9cda150502d#file-chat-java-L150

**Expected behavior (as observed with websocket transport):** 
User sends a message and chat responds with 10 messages counting 1 to 10 every 100ms

**Current behavior  using long-polling:**
User sends a message and 10 messages appear all at once in chat after exactly 1 minute.
if user sends another message within this one minute interval, the messages are delivered with the second user's message

Sounds like a problem with the BroadcasterCache to me, but I was not able to figure out the root cause. 

This issue is similar to #2045 

Hope you will be able to help me find a resolution. 
Thanks
Viktor

**Comment by jfarcand** [comment]
This is the expected behaviour , e.g just configure the BroadcasterCache properly.
