### ISSUE TITLE
WebSocket protocol not supported on Payara 5

### ISSUE THREAD

**Issue by blono** [Atmosphere/atmosphere#2367]
I'm trying to test https://github.com/Atmosphere/atmosphere-samples/tree/master/samples/websocket-chat on Payara 5.

It seems that WebSocket protocol is not supported on Payara.

## Steps to reproduce

1. git clone https://github.com/Atmosphere/atmosphere-samples/tree/master/samples/websocket-chat
2. mvn package
3. download Payara 5.191 from https://www.payara.fish/software/downloads/
4. unzip payara-5.191.zip
5. run payara\glassfish\bin\startserv.bat
6. goto http://localhost:4848/
7. deploy atmosphere-websocket-chat.war
8. goto http://localhost:8080/atmosphere-websocket-chat/

Expected outcome is "Atmosphere connected using websocket."
Current outcome is "Atmosphere connected using streaming."

In case of using GlassFish 5 instead of Payara 5, websocket is working properly.

For testing purpose, I modified　atmosphere/modules/cpr/src/main/java/org/atmosphere/cpr/ContainerInitializer.java as follows

boolean force = c.getServerInfo().toLowerCase().contains("glassfish");
↓
boolean force = c.getServerInfo().toLowerCase().contains("glassfish") || c.getServerInfo().toLowerCase().contains("payara");

if (c.getServerInfo().toLowerCase().contains("glassfish")) {
↓
if (c.getServerInfo().toLowerCase().contains("glassfish") || c.getServerInfo().toLowerCase().contains("payara")) {

then I confirmed WebSocket is running propely on Payara 5.

Payara is compatible with GlassFish and Atmosphere already support GlassFish.
So, please support Payara too!

**Comment by jfarcand** [comment]
@blono Great investigation! Can you do a pull request? I will merge it and integrate it ASAP. Thanks!

**Comment by blono** [comment]
@jfarcand Thank you, too!
I'm really glad if WebSocket works fine on Payara!
https://github.com/Atmosphere/atmosphere/pull/2369
