### ISSUE TITLE
Two licenses in the same file

### ISSUE THREAD

**Issue by rahulmohang** [Atmosphere/atmosphere#2377]
Hi,

I have seen two licenses listed in the following files in atmosphere package:

atmosphere-atmosphere-project-2.4.30.zip/atmosphere-atmosphere-project-2.4.30/modules/cpr/src/main/java/org/atmosphere/util/uri/*. They are Apache-2.0, and dual license of GPL-2.0 and CDDL-1.1. As Apache is incompatible with both GPL and CDDL, this does not look right as far as I am aware of the incompatibility topic. 

As per the readme file, atmosphere-atmosphere-project-2.4.30/license/README, the files in uri folder should be under CDDL. 

So, can we please make the license information consistent and have a conclusion on the license of the files?

@jfarcand @neotyk @ceefour @wolfie

**Comment by wolfie** [comment]
Unless I'm mistaken, I'm included here because of commit d64542a19.

Be how it may, feel free to use, license, share, distribute, copy, modify and whatever you need to do with any and all code I have contributed to Atmosphere. In other words, I don't really care what you do with my code :)

Enjoy, have fun!

**Comment by rahulmohang** [comment]
Thank you wolfie, Yes, my intention was to get you attention as I thought you were connected to this.

**Comment by rahulmohang** [comment]
Hi, 

In the file, 'https://github.com/Atmosphere/atmosphere/blob/atmosphere-project-2.7.3/modules/cpr/src/main/java/org/atmosphere/util/ThreadLocalInvoker.java', there are two licenses. I understand that the file is supposed to be licensed under Apache v2.0 as per https://github.com/Atmosphere/atmosphere/blob/atmosphere-project-2.7.3/license/README.

**Comment by jfarcand** [comment]
@rahulmohang You can have both license per file say. That's always how it worked with forked code used in Atmosphere

**Comment by rahulmohang** [comment]
@jfarcand, ok. I wanted to raise the issue that the license of the forked code used in Atmosphere and the license of Atmosphere that you applied to the forked code are incompatible to each other. Source code in a single file licensed under CDDL v1.1 or GPL v2.0 with Classpath exception cannot be licensed under Apache v2.0 as well, when it is copied to an Apache v2.0 project, unless the copyright holders of the code, that you copied to the project, agree to do a re-licensing of the code.  If it is a re-licensing, your approach may be right. 

I am not a lawyer though. So, I may be wrong. My reasoning is that, if the files are considered licensed under CDDL v1.1 or GPL v2.0 only with Classpath exception,  then, due to the copyleft effect of the licenses (in the file scope), only one of the licenses may be applied to the file. For the same reason, Apache v2.0 license may not be applied to the file. 

So, if you keep the files under either CDDL v1.1 or GPL v2.0 with Classpath exception, without applying the header of the Apache v2.0 license, I think that it is fine.
