### ISSUE TITLE
OpenJDK 8

### ISSUE THREAD

**Issue by seamusmac** [Atmosphere/atmosphere#2380]
I tried to upgrade to Atmosphere 2.5.5 today, but I got this error when an atmosphere connection is made.

W 10:16:11.957 [o.a.c.AtmosphereResourceImpl] [700-exec-6] [] Exception during suspend() operation java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
D 10:16:11.957 [o.a.c.AtmosphereResourceImpl] [700-exec-6] [] 
java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
	at org.atmosphere.client.TrackMessageSizeInterceptor$Interceptor.transformPayload(TrackMessageSizeInterceptor.java:168)

This worked before on Atmosphere 2.5.4.

I wonder is it related to the move to OpenJDK on Travis? Don't have time to investigate further.

**Comment by jfarcand** [comment]
Strange...Are you using Oracle JDK or OpenJDK?

**Comment by seamusmac** [comment]
I tried with 
AdoptOpenJDK jdk-8.0.222.10
& 
Oracle jdk1.8.0_191

Both gave the same  error

**Comment by seamusmac** [comment]
V. similar issue if you google, eg https://github.com/hazelcast/hazelcast/issues/14214

**Comment by seamusmac** [comment]
Hmm, if you look at the Travis log it says javac 9.0.1

0.01s$ java -Xmx32m -version
openjdk version "1.8.0_141"
OpenJDK Runtime Environment (build 1.8.0_141-8u141-b15-3~14.04-b15)
OpenJDK 64-Bit Server VM (build 25.141-b15, mixed mode)
$ javac -J-Xmx32m -version
javac 9.0.1

**Comment by jfarcand** [comment]
Just tested with 
```
jfarcand@/workspace/atmosphere-samples/samples/chat $ java -version
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
jfarcand@/workspace/atmosphere-samples/samples/chat $
```

and everything works as expected.

**Comment by jfarcand** [comment]
@seamusmac I'm still puzzled about this issue. I was able to reproduce it (with 2.5.8) but still unclear how to fix it. For sure it happens when I cut release, but I do use jdk8/javac8. Digging
