### ISSUE TITLE
org.atmosphere::atmosphere-project::2.5.6 not published on maven central

### ISSUE THREAD

**Issue by cthiebaud** [Atmosphere/atmosphere#2382]
maven error : "Failed to collect dependencies at org.atmosphere:atmosphere-runtime:jar:2.5.6: Failed to read artifact descriptor for org.atmosphere:atmosphere-runtime:jar:2.5.6: Could not find artifact org.atmosphere:atmosphere-project:pom:2.5.6"

Seems that org.atmosphere:atmosphere-project:pom:2.5.6 is not on maven central :

https://search.maven.org/search?q=g:org.atmosphere%20AND%20a:atmosphere-project&core=gav

**Comment by jfarcand** [comment]
Fixed the issue in `2.5.8`
