### ISSUE TITLE
DefaultBroadcaster calls toString() unnecessarily on every notification

### ISSUE THREAD

**Issue by alexkau** [Atmosphere/atmosphere#2383]
At the start of DefaultBroadcaster.deliverPush(), Atmosphere calls `String prevMessage = deliver.message.toString();`, and at the end of the function, calls `deliver.message = prevMessage;`.

This was originally added in [this commit from 2010](https://github.com/Atmosphere/atmosphere/commit/abaa9eebdd01ed4f26180477f8c96f61f124657f), and as far as I can tell the logic hasn't changed since. Unfortunately, the linked issue no longer exists, and web.archive.org doesn't appear to have archived it.

In my application, we frequently send out fairly large objects that Atmosphere converts to JSON for us. Calling toString() on these objects takes a fairly large amount of CPU time, and in some cases creates unnecessary humongous allocations that place extra load on the garbage collector.

In addition to the performance issue, there's another potential issue in that `deliver.message.toString()` may not be equivalent to `deliver.message`. I can't find any documentation that indicates that they must be equivalent, but as far as I can tell it looks like this is an undocumented requirement for whatever case was being affected by the aforementioned bug.

I discussed with a coworker, and the only situations we could come up with that would make the toString() in this call make sense would be if Atmosphere was modifying the inner object (which I highly doubt, given that it could only really operate on Java builtins, and I can't think of any reason why it'd do this) or if the application was modifying the notification object using a BroadcastFilter (and if things broke because of this, then that's the fault of the developer implementing the filter, not something Atmosphere should account for).

I just wanted to double-check that I'm not overlooking any edge cases before I went ahead and submitted a pull request to change `String prevMessage = deliver.message.toString();` to `Object prevMessage = deliver.message;`.

Thanks!

**Comment by jfarcand** [comment]
@alexkau Make sense. Bring the pull request :-)

**Comment by alexkau** [comment]
Done! https://github.com/Atmosphere/atmosphere/pull/2384
