### ISSUE TITLE
Long polling POST produces "received an empty body"

### ISSUE THREAD

**Issue by StacyMader** [Atmosphere/atmosphere#2387]
Deployment: Atmosphere 2.5.4 on Tomcat 8.0.49 server. After a server disconnect, Atmosphere degrades to long-polling (from websocket), but unable to POST messages, but GET (i.e., receives new messages) works fine.

```1312272 [http-nio-8080-exec-1] WARN org.atmosphere.config.managed.ManagedAtmosphereHandler - AtmosphereRequest{ method=POST contextPath=/HOME servletPath=/async pathInfo=/message requestURI=/HOME/async/message requestURL=http://xxx.xxx.xxx.xxx:8080/HOME/async/message AtmosphereResource UUID=9b398ce3-ab59-48b0-998f-30fa9d26d866 destroyable=true} received an empty body```

The browser log shows Content-Length: 0 , but the payload is definitely not zero-length: { type: "chat", message: "hello" } . Interestingly, the Request URL is:

```https://xxx.xxx.xxx.xxx/HOME/fallback/message?X-Atmosphere-tracking-id=9b398ce3-ab59-48b0-998f-30fa9d26d866&X-Atmosphere-Framework=2.3.8-javascript&X-Atmosphere-Transport=polling&X-Atmosphere-TrackMessageSize=true&Content-Type=application%2Fjson&_=1574870316069```

We have Tomcat and Apache linked in a reverse proxy setup. The web.xml is attached. Any help appreciated!

```<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://java.sun.com/xml/ns/javaee"
         xmlns:web="http://java.sun.com/xml/ns/javaee"
         xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd"
         id="HOME" version="3.0">
   
        <session-config>
        <session-timeout>5</session-timeout>
    </session-config>    
  
  <display-name>HOME</display-name>
  
  <welcome-file-list>
    <welcome-file>index.jsp</welcome-file>
  </welcome-file-list>
  
  <listener>
    <listener-class>org.springframework.web.context.ContextLoaderListener</listener-class>
  </listener>
  
  <listener>
    <listener-class>org.springframework.security.web.session.HttpSessionEventPublisher</listener-class>
  </listener>
  
  <context-param>
    <param-name>contextConfigLocation</param-name>
    <param-value>/WEB-INF/applicationContext-security.xml</param-value>
  </context-param>
  
  <listener>
    <listener-class>org.atmosphere.cpr.SessionSupport</listener-class>
  </listener>
  
  <servlet>
    <description>AtmosphereServlet</description>
    <servlet-name>AtmosphereServlet</servlet-name>
    <servlet-class>org.atmosphere.cpr.AtmosphereServlet</servlet-class>
    
    <init-param>
      <param-name>org.atmosphere.cpr.packages</param-name>
      <param-value>xxx.xxx.websocket</param-value>
    </init-param>
    
    <init-param>
      <param-name>org.atmosphere.cpr.AtmosphereInterceptor</param-name>
      <param-value>org.atmosphere.client.TrackMessageSizeInterceptor</param-value>
    </init-param>
    
    <init-param>
      <param-name>org.atmosphere.interceptor.HeartbeatInterceptor.heartbeatFrequencyInSeconds</param-name>
      <param-value>10</param-value>
    </init-param>
    
    <init-param>
      <param-name>org.atmosphere.interceptor.HeartbeatInterceptor.clientHeartbeatFrequencyInSeconds</param-name>
      <param-value>15</param-value>
    </init-param>
    
    <init-param>
      <param-name>org.atmosphere.cpr.removeSessionTimeout</param-name>
      <param-value>true</param-value>
    </init-param>
 
    <async-supported>true</async-supported>
  </servlet>
  
  <servlet-mapping>
    <servlet-name>AtmosphereServlet</servlet-name>
    <url-pattern>/async/*</url-pattern> 
  </servlet-mapping>
  
  <filter>
    <filter-name>springSecurityFilterChain</filter-name>
    <filter-class>org.springframework.web.filter.DelegatingFilterProxy</filter-class>
    <async-supported>true</async-supported>
  </filter>
  
  <filter-mapping>
    <filter-name>springSecurityFilterChain</filter-name>
    <url-pattern>/*</url-pattern>
    <dispatcher>REQUEST</dispatcher>
    <dispatcher>ASYNC</dispatcher>
  </filter-mapping>
    
  <servlet>
    <servlet-name>RestletServlet</servlet-name>
    <servlet-class>org.restlet.ext.servlet.ServerServlet</servlet-class>
  </servlet>
  
  <servlet-mapping>
    <servlet-name>RestletServlet</servlet-name>
    <url-pattern>/api/*</url-pattern>
  </servlet-mapping>
  
  <context-param>
    <param-name>org.restlet.application</param-name>
    <param-value>xxx.xxx.DataServiceApplication</param-value>
  </context-param>
  
</web-app>```

**Comment by jfarcand** [comment]
@StacyMader Have you found the issue?

**Comment by StacyMader** [comment]
Hi @jfarcand 

No, not yet, though it may be related to this: https://github.com/Atmosphere/atmosphere/issues/1459

When connection to the server is lost, fallback/long-polling is activated, but we are unable to send a message using long-polling, with the message below.

We will try a few things and get back to you.

BTW, we are using runtime-2.5.9 / Tomcat 8.0.49 / Apache 2.4.10.

109368 [http-nio-8080-exec-10] WARN org.atmosphere.config.managed.ManagedAtmosphereHandler - AtmosphereRequest{ method=POST contextPath=/xx servletPath=/async pathInfo=/message requestURI=/xx/async/message requestURL=http://hostname:8080/xx/async/message AtmosphereResource UUID=7ac3ed7d-2b8b-4465-8d30-1da881693009 destroyable=true} received an empty body
D

**Comment by StacyMader** [comment]
This was due to a misconfiguration of the servlet, which did not capture /fallback for long-polling.
