### ISSUE TITLE
in DefaultBroadcaster.lookup() the call to store.getId() is made twice but once should be enough

### ISSUE THREAD

**Issue by ggaborg** [Atmosphere/atmosphere#2389]
if (unique && store.get(id) != null) {
                throw new IllegalStateException("Broadcaster already exists " + id + ". Use BroadcasterFactory.lookup instead");
            }
T b = (T) store.get(id);

could be written:

T b = (T) store.get(id);
if (unique && b != null) {
                throw new IllegalStateException("Broadcaster already exists " + id + ". Use BroadcasterFactory.lookup instead");
            }

**Comment by jfarcand** [comment]
@ggaborg Good catch. Just do a pull request and I will integrate (and cut) a new release
