### ISSUE TITLE
in DefaultBroadcaster.lookup() the synchronized(c) block should be avoided

### ISSUE THREAD

**Issue by ggaborg** [Atmosphere/atmosphere#2390]
In DefaultBroadcaster.lookup() the synchronized(c) block can be avoided for specific combinations of 
'createIfNull' and 'unique' parameters. 

For example if 'createIfNull' is false and 'unique' is false the implementation can be reduced to something simple without any syncronized(c) block, e.g:

            T b = (T) store.get(id);
            logger.trace("Looking in the store using {} returned {}", id, b);
            if (b != null && !c.isAssignableFrom(b.getClass())) {
                String msg = "Invalid lookup class " + c.getName() + ". Cached class is: " + b.getClass().getName();
                logger.debug(msg);
                throw new IllegalStateException(msg);
            }

The benefit of avoiding the synchronized block is much higher than having a single generic implementation of the lookup() method.

**Comment by jfarcand** [comment]
@ggaborg Please file pull request
