### ISSUE TITLE
Adding heartbeat listener fails due to different instance of AtmosphereResource with same uuid

### ISSUE THREAD

**Issue by pas-dag** [Atmosphere/atmosphere#2392]
I am attempting to add a heartbeat listener to every new `AtmosphereResource` created in my application, and running into trouble. I have a class that implements `AtmosphereHandler` annotated with `AtmosphereHandlerService`, and in the `onRequest` method, I've added several event listeners to the resource. However, when the heartbeat triggers, it logs the message,
`TRACE o.a.cpr.AtmosphereResourceImpl - No listener with <<uuid>>`. This uuid matches the one logged in `onRequest`. I inspected this with the debugger, and despite having the same uuid, the instance of `AtmosphereResourceImpl` that my `onRequest` method is called with is different from the one that is getting the heartbeat event, and has none of the listeners I added in `onRequest`. However, my `onRequest` method also adds a disconnect listener, and that listener *does* work correctly.

I would like very much to be told that I'm just using the library wrong. I'm using atmosphere-runtime 2.5.12 from maven. The app is a dropwizard web application.

**Comment by jfarcand** [comment]
Which transport are you using? Any unit test that I could play with?

**Comment by pas-dag** [comment]
It's using websocket transport. I'll try to create a minimal demonstration of the problem to share.

**Comment by pas-dag** [comment]
Here's a repo with a tiny app that demonstrates the problem. Not exactly a unit test, but hopefully this will let you see the issue.

https://github.com/pas-dag/websocket-demo

**Comment by jfarcand** [comment]
Fixed in 2.6.2+
