### ISSUE TITLE
Atmosphere uses "polling" to issue a close when not configured via transport/fallbackTransport

### ISSUE THREAD

**Issue by StacyMader** [Atmosphere/atmosphere#2402]
When there is a network outage, we've noticed Atmosphere issues a close statement using the "polling" method. In our configuration, we have set transport = websocket and fallbackTransport = long-polling, so it is not clear why "polling" is used:

```
 let request = new atmosphere.AtmosphereRequest();
                        request.contentType = 'application/json';
                        request.enableProtocol = true;
                        request.fallbackTransport = "long-polling";
                        request.logLevel = "debug";
                        request.maxReconnectOnClose = 12;
                        request.reconnectInterval = 5000;
                        request.trackMessageLength = true;
                        request.transport = 'websocket';
```

The issue is our reverse proxy setup (Apache frontend, Tomcat backend) detects the header string "polling" and cannot be redirected, resulting in a 500 error. Whilst we could configure this in the Apache configuration, I am wondering if this is a bug, given we have not selected polling as any method.

Request Header:
```
Request URL: https://xxx?X-Atmosphere-tracking-id=b2a29b78-8dc7-46c5-bf8d-80951e8e7ec4&X-Atmosphere-Framework=2.3.8-javascript&X-Atmosphere-Transport=polling&X-Atmosphere-TrackMessageSize=true&Content-Type=application%2Fjson&_=1581582829589

Request Method: POST
```

Response Header:
```
Connection: close
```

This is using Atmosphere runtime 2.5.13, on Tomcat 8.0.49.

**Comment by jfarcand** [comment]
@StacyMader That's the default behavior. Have you found a solution ?

**Comment by StacyMader** [comment]
@jfarcand , yes we have, thank you. 

With our Apache frontend, we now use a RewriteRule to direct websocket traffic to ws:// , and all other traffic such as long-polling or polling to http://
