### ISSUE TITLE
“NoSuchMethodErrors” due to multiple versions of org.eclipse.jetty:jetty-http:jar

### ISSUE THREAD

**Issue by Bing-ok** [Atmosphere/atmosphere#2415]
Hi, there are multiple versions of <b><i>org.eclipse.jetty:jetty-http</i></b> in <b><i>atmosphere-atmosphere-project-2.6.1\modules\cpr</i></b>. As shown in the following dependency tree, according to Maven's “nearest wins” strategy, only <b><i>org.eclipse.jetty:jetty-http:9.3.19.v20170502</i></b> can be loaded, <b><i>org.eclipse.jetty:jetty-http:7.6.9.v20130131</i></b> will be shadowed.

As <b><i>org.eclipse.jetty:jetty-http:7.6.9.v20130131</i></b> has not been loaded during the building process, several methods are missing. However, the missing methods:
<b><i>1. org.eclipse.jetty.http.HttpParser: org.eclipse.jetty.io.Buffer getBodyBuffer()</i></b>
<details>
<summary>Check for details of invocation</summary>
</br>paths------
</br>&lt;org.atmosphere.container.JettyWebSocketUtil: org.atmosphere.cpr.Action doService(org.atmosphere.cpr.AsynchronousProcessor,org.atmosphere.cpr.AtmosphereRequest,org.atmosphere.cpr.AtmosphereResponse,org.eclipse.jetty.websocket.WebSocketFactory)&gt; atmosphere-atmosphere-project-2.6.1\modules\cpr\target\classes
</br>&lt;org.eclipse.jetty.websocket.WebSocketFactory: boolean acceptWebSocket(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)&gt; Repositories\org\eclipse\jetty\jetty-websocket\7.6.9.v20130131\jetty-websocket-7.6.9.v20130131.jar
</br>&lt;org.eclipse.jetty.websocket.WebSocketFactory: void upgrade(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse,org.eclipse.jetty.websocket.WebSocket,java.lang.String)&gt; Repositories\org\eclipse\jetty\jetty-websocket\7.6.9.v20130131\jetty-websocket-7.6.9.v20130131.jar
</br>&lt;org.eclipse.jetty.http.HttpParser: org.eclipse.jetty.io.Buffer getBodyBuffer()&gt;
</details>

<b><i>2. org.eclipse.jetty.http.HttpException: void <init>(int,java.lang.String)</i></b>
<details>
<summary>Check for details of invocation</summary>
</br>paths------
</br>&lt;org.atmosphere.container.JettyWebSocketUtil: org.atmosphere.cpr.Action doService(org.atmosphere.cpr.AsynchronousProcessor,org.atmosphere.cpr.AtmosphereRequest,org.atmosphere.cpr.AtmosphereResponse,org.eclipse.jetty.websocket.WebSocketFactory)>&gt; atmosphere-atmosphere-project-2.6.1\modules\cpr\target\classes
</br>&lt;org.eclipse.jetty.websocket.WebSocketFactory: boolean acceptWebSocket(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)&gt; Repositories\org\eclipse\jetty\jetty-websocket\7.6.9.v20130131\jetty-websocket-7.6.9.v20130131.jar
</br>&lt;org.eclipse.jetty.websocket.WebSocketFactory: void upgrade(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse,org.eclipse.jetty.websocket.WebSocket,java.lang.String)&gt; Repositories\org\eclipse\jetty\jetty-websocket\7.6.9.v20130131\jetty-websocket-7.6.9.v20130131.jar
</br>&lt;org.eclipse.jetty.http.HttpException: void init (int,java.lang.String)&gt;
</details>

<b><i>3. org.eclipse.jetty.http.HttpParser: org.eclipse.jetty.io.Buffer getHeaderBuffer()</i></b>
<details>
<summary>Check for details of invocation</summary>
</br>paths------
</br>&lt;org.atmosphere.container.JettyWebSocketUtil: org.atmosphere.cpr.Action doService(org.atmosphere.cpr.AsynchronousProcessor,org.atmosphere.cpr.AtmosphereRequest,org.atmosphere.cpr.AtmosphereResponse,org.eclipse.jetty.websocket.WebSocketFactory)&gt; atmosphere-atmosphere-project-2.6.1\modules\cpr\target\classes
</br>&lt;org.eclipse.jetty.websocket.WebSocketFactory: boolean acceptWebSocket(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)&gt; Repositories\org\eclipse\jetty\jetty-websocket\7.6.9.v20130131\jetty-websocket-7.6.9.v20130131.jar
</br>&lt;org.eclipse.jetty.websocket.WebSocketFactory: void upgrade(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse,org.eclipse.jetty.websocket.WebSocket,java.lang.String)&gt; Repositories\org\eclipse\jetty\jetty-websocket\7.6.9.v20130131\jetty-websocket-7.6.9.v20130131.jar
</br>&lt;org.eclipse.jetty.http.HttpParser: org.eclipse.jetty.io.Buffer getHeaderBuffer()&gt;
</details>

The above missing methods are actually referenced by <b><i>atmosphere-atmosphere-project-2.6.1\modules\cpr</i></b>, which will cause “NoSuchMethodErrors” at runtime.

Suggested fixing solutions:
1. Upgrade dependency <b><i>org.eclipse.jetty:jetty-websocket</i></b> from <b><i>7.6.9.v20130131</i></b> to <b><i>7.6.10.v20130312</i></b>. Because one conflicting library version <b><i>org.eclipse.jetty:jetty-http:7.6.9.v20130131</i></b> is transitively introduced by <b><i>org.eclipse.jetty:jetty-websocket:7.6.9.v20130131</i></b>. Upgrading dependency <b><i>org.eclipse.jetty:jetty-websocket</i></b> from <b><i>7.6.9.v20130131</i></b> to <b><i>7.6.10.v20130312</i></b> can solve this dependency conflict.

Thank you very much for your attention.
Best regards,

Dependency tree----
<details>
<summary>click for details</summary>
</br>[INFO] org.atmosphere:atmosphere-runtime:bundle:2.6.1
</br>[INFO] +- org.eclipse.jetty.websocket:websocket-server:jar:9.3.19.v20170502:provided
</br>[INFO] |  +- org.eclipse.jetty:jetty-servlet:jar:9.3.19.v20170502:provided
</br>[INFO] |  |  \- org.eclipse.jetty:jetty-security:jar:9.3.19.v20170502:provided
</br>[INFO] |  |     \- org.eclipse.jetty:jetty-server:jar:9.3.19.v20170502:provided
</br>[INFO] |  |        \- <b>(org.eclipse.jetty:jetty-http:jar:9.3.19.v20170502:provided - omitted for duplicate)</b>
</br>[INFO] |  \- <b>org.eclipse.jetty:jetty-http:jar:9.3.19.v20170502:provided</b>
</br>[INFO] \- org.eclipse.jetty:jetty-websocket:jar:7.6.9.v20130131:provided
</br>[INFO]    \- <b>(org.eclipse.jetty:jetty-http:jar:7.6.9.v20130131:provided - omitted for conflict with 9.3.19.v20170502)</b>
</details>

**Comment by Bing-ok** [comment]
Could you help me review this issue? 👍 Thanks! @jfarcand

**Comment by jfarcand** [comment]
@Bing-ok Could you please do a pull request? That way I will be able to merge faster.

**Comment by Bing-ok** [comment]
Thanks for your support!
