### ISSUE TITLE
Content-Type header + Spring mvc 5

### ISSUE THREAD

**Issue by itgabrut** [Atmosphere/atmosphere#2417]
Hi all,

I was trying to run Atmosphere (2.5.12) + Spring MVC (5.2.8) but encountered a certain problem.

Since some Spring release an AbstractMessageConverterMethodProcessor class, writeWithMessageConverters method has started to check response header 'Content-Type' rather then 'Accept' header of a request in order to find appropriate message converter.

Problem is that Atmosphere Framework set Content-Type header as well. And it is always 'text/plain', it is set in AtmosphereFramework configureRequestResponse method.

see: https://github.com/Atmosphere/atmosphere/issues/2312

Even if the header is not set there, it is default contentType within AtmosphereResponseImpl, which is text/html...

In this case, Spring can never find a correct converter and exception is thrown:

DefaultHandlerExceptionResolver]: Resolved [org.springframework.http.converter.HttpMessageNotWritableException: No converter for [class com.Connection] with preset Content-Type 'text/plain;charset=utf-8']

**Atmosphere Info**
  - version 2.5.12
  - atmosphere.js version 2.3.9

**Expected behavior**
Maybe it is worth to take Content-Type header from Accept header of a request ?
Or at least to have possibility to override default content-type, as was done for atmosphere 2.2.x
see: https://github.com/Atmosphere/atmosphere/pull/2410

**Systems (please complete the following information):**
 - OS: any
 - Java version 8
 - Serveur name and version [Tomcat]

**Comment by jfarcand** [comment]
@itgabrut Can you try with 2.6.1? The default is now configurable.

**Comment by itgabrut** [comment]
Unfortunately I've found that it maybe was not merged to 2.6.1
You can check here
[github.com/Atmosphere/atmosphere/blob/atmosphere-2.2.x/modules/cpr/src/main/java/org/atmosphere/cpr/AtmosphereFramework.java](https://github.com/Atmosphere/atmosphere/blob/atmosphere-2.2.x/modules/cpr/src/main/java/org/atmosphere/cpr/AtmosphereFramework.java)
It contains following code:
` String contentType = config.getInitParameter(CONTENT_TYPE_FIRST_RESPONSE);
            if (contentType != null) {
                res.setHeader("Content-Type", contentType);
            }`

But if I am looking to a 2.6.1:
[github.com/Atmosphere/atmosphere/blob/atmosphere-project-2.6.1/modules/cpr/src/main/java/org/atmosphere/cpr/AtmosphereFramework.java](https://github.com/Atmosphere/atmosphere/blob/atmosphere-project-2.6.1/modules/cpr/src/main/java/org/atmosphere/cpr/AtmosphereFramework.java)
I see the old hardcoded value:

`if (s == null || s.equals("0")) {
            s = config.uuidProvider().generateUuid();
            res.setHeader(HeaderConfig.X_FIRST_REQUEST, "true");
            res.setHeader(X_ATMOSPHERE_TRACKING_ID, s);
            res.setHeader("Content-Type", "text/plain; charset=utf-8");
        }`

**Comment by jfarcand** [comment]
@itgabrut Thanks for the analysis. Can you do a pull request? I will cut a release ASAP after to accommodate you.
