### ISSUE TITLE
Atmosphere JSR356 + Spring mvc 5 NPE while debug log level is enabled for Spring MVC

### ISSUE THREAD

**Issue by itgabrut** [Atmosphere/atmosphere#2418]
While using Atmosphere JSR 356 endpoint there is possibility to use   ReflectorServletProcessor as atmosphereHandler, which forwards request to a DispatcherServlet. JSR endpoint path in this case the same as servlet path.
(It uses URL pattern from web.xml)
`    <servlet-mapping>`
      `  <servlet-name>spring-mvc</servlet-name>`
      `  <url-pattern>/</url-pattern>`
  `  </servlet-mapping>`

Spring MVC 5 has improved logging, so it logs additional parameters of a request such as 'dispatchertype'.
DispatcherServlet, logRequest method:
`String dispatchType = (!request.getDispatcherType().equals(DispatcherType.REQUEST)`

Now it fails with NPE, because reguest.getDispatcherType() returns null.
HttpRequest implementation is AtmosphereRequestImpl, while calling dispatcherType it refers to a nested Request which is finally 'AtmosphereRequestImpl$NoOpsRequest' instance, and getDispatcherType is implemented to return null.

**Atmosphere Info**
  - version 2.6.1
  - atmosphere.js 2.3.9

**Systems (please complete the following information):**
 - OS: Windows 10
 - Java version 8
 - Tomcat 9.037

**Comment by jfarcand** [comment]
@itgabrut Pull request more than welcomed :-)
