### ISSUE TITLE
Missing Licensing information

### ISSUE THREAD

**Issue by JRSofty** [Atmosphere/atmosphere#2423]
There is no listed license for this project. According to maven earlier versions of this were licensed under CDDL 1.0 but the link connecting the project to the license is dead as java.net is now closed. 

Could you please provide an appropriate licensing link to this project?

**Comment by jfarcand** [comment]
For an unknown reason, the license has been deleted from the working branch, but was still present master:

https://github.com/Atmosphere/atmosphere/tree/master/license

Fixed
