### ISSUE TITLE
NullPointerException in JSR356Endpoint.onOpen(JSR356Endpoint.java:129)

### ISSUE THREAD

**Issue by mvysny** [Atmosphere/atmosphere#2427]
**Describe the bug**
Atmosphere fails with NullPointerException in JSR356Endpoint.onOpen():

```
2021-02-05 14:26:49,395 DEBUG [org.atm.con.JSR356Endpoint] (vert.x-eventloop-thread-8) Problem in web socket session: java.lang.NullPointerException
	at org.atmosphere.container.JSR356Endpoint.onOpen(JSR356Endpoint.java:129)
	at io.undertow.websockets.jsr.EndpointSessionHandler.connected(EndpointSessionHandler.java:130)
	at io.undertow.websockets.jsr.JsrWebSocketFilter$1.accept(JsrWebSocketFilter.java:128)
	at io.undertow.websockets.jsr.JsrWebSocketFilter$1.accept(JsrWebSocketFilter.java:125)
	at io.undertow.websockets.jsr.handshake.Handshake$1.accept(Handshake.java:141)
	at io.undertow.vertx.VertxHttpExchange$10$1.run(VertxHttpExchange.java:869)
	at io.undertow.vertx.VertxHttpExchange$10.handle(VertxHttpExchange.java:873)
	at io.undertow.vertx.VertxHttpExchange$10.handle(VertxHttpExchange.java:858)
	at io.vertx.core.net.impl.ConnectionBase.lambda$wrap$1(ConnectionBase.java:184)
```

Upon debugging it can be seen that `handshakeHeaders` is null, which suggests the reason why NPE is thrown.

The `handshakeHeaders` is populated in `JSR356Endpoint.handshakeRequest()` which is in turn called by `AtmosphereConfigurator.modifyHandshake()` or `AtmosphereConfigurator.getEndpointInstance()`. I can see that there is a workaround for Glassfish, in a sense that certain values are stored in ThreadLocals. However, upon debugging, it looks like that on Quarkus/VertX/Undertow, the methods are called by various threads, and so the ThreadLocals are empty, causing the  `JSR356Endpoint.handshakeRequest()` not to be called, which in turn causes the NPE.

This is just a preliminary analysis - please let me know if you'd like to learn more details.

**Atmosphere Info**
  - version: 2.4.30.slf4jvaadin1 (yeah unfortunately it's a Vaadin-patched Atmosphere library)
  - atmosphere.js version: 2.3.2.vaadin1-javascript
  - extensions used: not sure about this one...

**Expected behavior**
Atmosphere would initialize correctly in `JSR356Endpoint.onOpen()`

**Screenshots**
Atmosphere fails to initialize in `JSR356Endpoint.onOpen()`, which leads to Undertow to close the websocket, which in turn leads to Vaadin client-side to fall back to long polling.

**Systems (please complete the following information):**
 - OS: Ubuntu 20.10 x86-64
 - Browser name and version: Firefox 85.0
 - Java version and distribution: openjdk version "11.0.9.1" 2020-11-04
 - Serveur name and version: Undertow unknown version (comes from Quarkus 1.10.5), vertx unknown version (comes from Quarkus 1.10.5).

**Steps to reproduce**

1. git clone https://github.com/mvysny/vaadin-quarkus (the `main` branch; currently at commit `afe71f83ecca57a984cb3a407f0750624b6b0673`
2. Compile the project: `mvn -C clean package -DskipTests`
3. Run the project from Intellij in debug mode
4. Place a breakpoint into `JSR356Endpoint.handshakeRequest()` and observe that `this.handshakeHeaders` is null.
5. Place breakpoints into `JSR356AsyncSupport:133` (the `AtmosphereConfigurator.getEndpointInstance()`) and 149 (`AtmosphereConfigurator.modifyHandshake()`) and observe that they're being called from multiple threads.

**Comment by mvysny** [comment]
Placing breakpoints into `getEndpointInstance()` and `modifyHandshake()` and logging the current thread will yield the following order and log output for Undertow+VertX+Quarkus:

```
!!! modifyHandshake():Thread[executor-thread-3,5,executor]
!!! getEndpointInstance():Thread[vert.x-eventloop-thread-11,5,main]
!!! modifyHandshake():Thread[executor-thread-1,5,executor]
!!! getEndpointInstance():Thread[vert.x-eventloop-thread-10,5,main]
```

This means two things:
1. The "Glassfish" workaround needs to apply to Undertow as well, since the calls are reversed as well
2. The threads are completely different every time the function is invoked, hence the ThreadLocal solution won't work.

**Comment by mvysny** [comment]
I've patched the `JSR356AsyncSupportPatch.AtmosphereConfigurator` to store the current request in a `BlockingDeque` rather than in a ThreadLocal. Please find the class below:


```java
    public final static class AtmosphereConfigurator extends ServerEndpointConfig.Configurator {

        private final AtmosphereFramework framework;
        /**
         * TODO: UGLY!
         * Quarkus call modifyHandshake BEFORE getEndpointInstance() where other jsr356 do the reverse.
         * However, because of VertX the thread pool of Undertow handling regular http requests
         * differ to the thread pool handling websocket requests, so we can't use ThreadLocals to remember
         * the HandshakeRequest. Use BlockingDeque with the capacity of 1 since we don't want
         * the requests to get mixed up in case of high concurrency.
         *
         * The reasoning for BlockingDeque is that we expect that a call to getEndpointInstance() will
         * immediately follow call to modifyHandshake(). We will therefore store the request into this deque,
         * and we will pick it up in getEndpointInstance().
         *
         * The deque has a capacity of 1: if there are any concurrent attempts to initialize the endpoint,
         * any follow-up modifyHandshake() will be delayed until the getEndpointInstance() is called.
         *
         * For the ThreadLocal-based solution see the original JSR356AsyncSupport class from Atmosphere.
         */
        private final BlockingDeque<HandshakeRequest> requests = new LinkedBlockingDeque<>(1);

        public AtmosphereConfigurator(AtmosphereFramework framework) {
            this.framework = framework;
        }

        public <T> T getEndpointInstance(Class<T> endpointClass) throws InstantiationException {
            if (JSR356Endpoint.class.isAssignableFrom(endpointClass)) {
                JSR356Endpoint e = new JSR356Endpoint(framework, WebSocketProcessorFactory.getDefault().getWebSocketProcessor(framework));
                final HandshakeRequest request = requests.removeFirst();
                e.handshakeRequest(request);
                return (T) e;
            } else {
                return super.getEndpointInstance(endpointClass);
            }
        }

        public void modifyHandshake(ServerEndpointConfig sec, HandshakeRequest request, HandshakeResponse response) {
            try {
                // if there's an ongoing endpoint initialization, delay this call
                // until the getEndpointInstance() has been called.
                if (!requests.offer(request, 1, TimeUnit.SECONDS)) {
                    throw new RuntimeException("Timed out waiting for getEndpointInstance() to be called");
                }
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }
        }
    }
```

**Comment by jfarcand** [comment]
@mvysny Sorry for the delay. Can you do a pull request?

**Comment by mvysny** [comment]
No problem :) However, I think it's best to only use this workaround when running on Quarkus, to not to hinder existing servers (for which the workaround works well) :thinking: @jfarcand what do you think?

**Comment by jfarcand** [comment]
@mvysny I think we can detect if we are running on Quarkus and do the appropriate work

**Comment by jfarcand** [comment]
@mvysny I think we can detect if we are running on Quarkus and do the appropriate work

**Comment by jfarcand** [comment]
@mvysny Any update for the patch? Let me know if you have the cycle to produce it, and I will complete the implementation

**Comment by mvysny** [comment]
Sorry for the delay; I'll try to work on a PR today evening :+1:

**Comment by mvysny** [comment]
PR: https://github.com/Atmosphere/atmosphere/pull/2429
