### ISSUE TITLE
Release Build fails with Invalid “self-closing element not allowed”

### ISSUE THREAD

**Issue by castortech** [Atmosphere/atmosphere#2439]
building Atmosphere with:
 mvn -Prelease-profile clean install

Fails with:

Invalid “self-closing element not allowed”

Googling shows that is a restriction on Java 8+ being more stringent on using correct tags

Was able to get it working by adding:
<doclint>none</doclint> 

to configuration section of maven-javadoc-plugin as described [here](https://stackoverflow.com/questions/15886209/maven-is-not-working-in-java-8-when-javadoc-tags-are-incomplete)

Am I missing something or should I submit a patch?

**Atmosphere Info**
  - 2.7.3

**Comment by jfarcand** [comment]
@castortech Pull request welcomed :)
