### ISSUE TITLE
Allow to use the servlet-version-range 4

### ISSUE THREAD

**Issue by vogella** [Atmosphere/atmosphere#2466]
Currently the atmosphere runtime does not allow to use  servlet-version-range of 4.0.0. AFAIK (based on my very limited knowledge, sorry for this), the 4.0.0 uses still the same package name as the 3.x version. So maybe the version change can be adjusted to include 4 and only exclude 5 (which change the package name)?

So instead of 

<servlet-version-range>[2.5,4)</servlet-version-range>

in the pom we could use

<servlet-version-range>[2.5,5)</servlet-version-range>

@jfarcand WDYT?

**Comment by jfarcand** [comment]
@vogella Make sense! Can you do a pull request? Thanks!
