### ISSUE TITLE
Servlet 5 API support

### ISSUE THREAD

**Issue by Artur-** [Atmosphere/atmosphere#2467]
**Describe the bug**
Spring 6 is moving to [Java 17 + Servlet 5](https://spring.io/blog/2021/09/02/a-java-17-and-jakarta-ee-9-baseline-for-spring-framework-6) with the [first milestone release done](https://spring.io/blog/2021/12/16/spring-framework-6-0-m1-released). Does Atmosphere have any plans on making a new major for servlet 5?

**Comment by jfarcand** [comment]
@Artur- Yes, I will make the appropriate change and release Atmosphere 3.0 based on it. Should be before end of January. Is that OK for you?

**Comment by Artur-** [comment]
Sounds good!

**Comment by jfarcand** [comment]
atmosphere-runtime-3.0.0 has been released with support for Jakarta.

**Comment by sanushchacko** [comment]
The atmosphere-spring module is still using "javax.servlet".
As the Spring framework 6.0.0-RC3 is already released to support Jakarta 3.0, when can we expect a new artifact for atmosphere-spring to support "jakarta.servlet"?.
