### ISSUE TITLE
Websocket connection closing and reconnecting after upgrade

### ISSUE THREAD

**Issue by amy-b-cheng** [Atmosphere/atmosphere#2468]
**Describe the bug**
After I upgraded my Atmosphere version, my websocket connection continually closes and reopens every ~60s.

When I refresh the page, I see that a 101 Switching Protocols request is sent with `X-Atmosphere-Transport: websocket`. I see messages send successfully over this connection, and then I see a handful of heartbeat messages every 10s.

Then another 101 Switching Protocols request is sent with `X-Atmosphere-Transport: websocket`. There is no data, just 1 blank row under "messages". This message's request call stack looks like this:
![image](https://user-images.githubusercontent.com/84814809/146819774-4953151d-ac4b-43b7-ab38-2e0e11cc544f.png)

Then a HTTP GET with status 200 is sent with the X-Atmosphere-tracking-id from the 2nd message and `X-Atmosphere-Transport: close`. This message's request call stack looks like this:
![image](https://user-images.githubusercontent.com/84814809/146819689-bda54bc6-615c-4bca-b11b-56ba673f2339.png)

Then this cycle repeats continuously, with these 3 messages popping up about every minute.

**Atmosphere Info**
  - Version: Found this by upgrading from 2.5.13 to 2.7.3, but a binary search revealed that the change was introduced between 2.5.13 and 2.6.0
  - atmosphere.js version: currently using 2.3.2, did try upgrading to 3.1.3 but did not resolve this bug
  - configuration details:
  ```
  - heartbeat: 10s
  - maxIdleTime: 120000s
  - maxInactiveActivity: -1
  - broadcasterLifeCyclePolicy: IDLE_DESTROY
  - maxBroadcasterLifeCyclePolicyTime: 60000s
  - recoverFromDestroyedBroadcaster: true
  ```

**Expected behavior**
Using Atmosphere 2.5.13, the websocket connection would be established and stay open, with heartbeat messages every 10s.

**Systems (please complete the following information):**
 - OS: Mac Big Sur 11.6
 - Browser: Chrome 96
 - Java: AdoptOpenJDK-11.0.11+9
 - Server: Jetty 9.4

**Additional context**

**Comment by jfarcand** [comment]
@amy-b-cheng Can you share a test case by any chance?

**Comment by amy-b-cheng** [comment]
@jfarcand Hi, unfortunately I can't share too many specifics about my application but I did some investigating and I found [this change](https://github.com/Atmosphere/atmosphere/compare/atmosphere-project-2.5.15...atmosphere-project-2.6.0#diff-bdbb29403dc693807ab47591ccfa632a3790cc0751cf72b0ece5082b3eb22e19L81) in LifecycleHandler.java that seems to be a change in behavior between 2.5 and 2.6.

Since I use IDLE_DESTROY, it seems that now idle broadcasters are getting destroyed **even if there are non empty resources**. This seems to be consistent with the symptoms I'm seeing, where broadcasters are continually getting destroyed and recreated ~every minute when the user isn't interacting with the page.

I modified the latest version of Atmosphere to test my theory and the below diff fixes the issue I'm experiencing:

I'd like to know if there was a reason that this change was made, and whether I should submit a PR for it.

```diff --git a/modules/cpr/src/main/java/org/atmosphere/lifecycle/LifecycleHandler.java b/modules/cpr/src/main/java/org/atmosphere/lifecycle/LifecycleHandler.java
index 7cb373afa..8dfa29c9f 100644
--- a/modules/cpr/src/main/java/org/atmosphere/lifecycle/LifecycleHandler.java
+++ b/modules/cpr/src/main/java/org/atmosphere/lifecycle/LifecycleHandler.java
@@ -41,6 +41,7 @@ public class LifecycleHandler {
 
     public LifecycleHandler on(final DefaultBroadcaster broadcaster) {
         final BroadcasterLifeCyclePolicy lifeCyclePolicy = broadcaster.getBroadcasterLifeCyclePolicy();
+        final Collection<AtmosphereResource>  resources = broadcaster.getAtmosphereResources();
         if (broadcaster.getID().contains("{") && broadcaster.getID().contains("}")) {
             logger.trace("Ignoring wildcard {} with lifecycle policy: {}", broadcaster.getID(), lifeCyclePolicy.getLifeCyclePolicy().name());
             return this;
@@ -84,19 +85,21 @@ public class LifecycleHandler {
                         // Check for activity since the last execution.
                         if (recentActivity.getAndSet(false)) {
                             return;
-                        } else if (lifeCyclePolicy.getLifeCyclePolicy() == IDLE) {
-                            notifyIdleListener(broadcaster);
-
-                            broadcaster.releaseExternalResources();
-                            logger.debug("Applying BroadcasterLifeCyclePolicy IDLE policy to Broadcaster {}", broadcaster.getID());
-                            if (broadcaster.currentLifecycleTask() != null) {
-                                broadcaster.currentLifecycleTask().cancel(true);
+                        } else if (resources.isEmpty()) {
+                            if (lifeCyclePolicy.getLifeCyclePolicy() == IDLE) {
+                                notifyIdleListener(broadcaster);
+
+                                broadcaster.releaseExternalResources();
+                                logger.debug("Applying BroadcasterLifeCyclePolicy IDLE policy to Broadcaster {}", broadcaster.getID());
+                                if (broadcaster.currentLifecycleTask() != null) {
+                                    broadcaster.currentLifecycleTask().cancel(true);
+                                }
+                            } else if (lifeCyclePolicy.getLifeCyclePolicy() == IDLE_DESTROY) {
+                                notifyIdleListener(broadcaster);
+
+                                destroy(false);
+                                logger.debug("Applying BroadcasterLifeCyclePolicy IDLE_DESTROY policy to Broadcaster {}", broadcaster.getID());
                             }
-                        } else if (lifeCyclePolicy.getLifeCyclePolicy() == IDLE_DESTROY) {
-                            notifyIdleListener(broadcaster);
-
-                            destroy(false);
-                            logger.debug("Applying BroadcasterLifeCyclePolicy IDLE_DESTROY policy to Broadcaster {}", broadcaster.getID());
                         } else if (lifeCyclePolicy.getLifeCyclePolicy() == IDLE_RESUME) {
                             notifyIdleListener(broadcaster);```

**Comment by jfarcand** [comment]
@amy-b-cheng I did that https://github.com/Atmosphere/atmosphere/issues/2407 but I suspect I'm missed some case. Go for a PR and I will cut a new 2.7.x official release.

**Comment by jfarcand** [comment]
@amy-b-cheng The more I read about it the more I think the current implementation is right: https://github.com/Atmosphere/atmosphere/blob/75f568553bfb38f2c1f411eb0e636b85e117277f/modules/cpr/src/main/java/org/atmosphere/cpr/BroadcasterLifeCyclePolicy.java#L38
```
        /**
         * Release all resources associated with the Broadcaster when the idle time expires and destroy the Broadcaster.
         * This operation removes the Broadcaster from it's associated {@link org.atmosphere.cpr.BroadcasterFactory}
         * {@link org.atmosphere.cpr.Broadcaster#destroy()} will be invoked. Suspended {@link AtmosphereResource}
         * will NOT get resumed.
         */
        IDLE_DESTROY,
```

What you probably need is EMPTY_DESTROY I think. Can you confirm?

**Comment by amy-b-cheng** [comment]
@jfarcand I believe you are right about the correct usage of IDLE_DESTROY. I tried out using EMPTY_DESTROY, which fixes the disconnecting problem, but does not work when my application is in long polling mode and the resources become empty.

So there are 2 behaviors I want here:
1) if there are subscribers to a broadcaster (i.e. non empty resources), I don't want it to be destroyed, even if it is idle
2) how we have our long polling mode set up, it appears that resources are empty even when there are users needing information. I still want the broadcaster up in this scenario

I think support for EMPTY_IDLE_DESTROY would actually be ideal, if I am interpreting that correctly as "destroy broadcasters when they are empty _and_ have been idle for x seconds"

**Comment by jfarcand** [comment]
Exactly! @amy-b-cheng Do you have time to implement it? I could review and release it after!

**Comment by amy-b-cheng** [comment]
@jfarcand see the PR I just opened / let me know what I need to add to it!

**Comment by jfarcand** [comment]
Support added in 2.7.4! Thanks for the contribution!!!!!

**Comment by jfarcand** [comment]
@amy-b-cheng It should be available right now

**Comment by sherryyur** [comment]
Hi, @amy-b-cheng

I know this is all sorted, but I am just curious how you were able to see the heartbeat from your end. I am assuming it's on browser Network tab. I configured my setting as 10s heartbeat and I saw the sever log said its 10s as well, but I never saw it from the browser. On client js request option, did you set the heartbeat option? 

I am currently expericing a disconnecting issue after couple of hours. I thought the heartbeat option should keep the connection on but not 100 percent sure... 

Thanks for this thread anyways. It gives more understanding of the websocket connection.

**Comment by amy-b-cheng** [comment]
Hi,

Yes, I am able to see my heartbeat in Google Chrome by going to Network ->
hit the "WS" button, for websockets -> there should be something under the
"Name" column that is a websocket connection, click on that -> hit the
"Messages" column and you should see a bunch of rows that are the websocket
messages -> for me, every 10s a message appears that looks like "1|X" and
that's the heartbeat

Let me know if you have any other questions!

Amy
