### ISSUE TITLE
WebSocket Handshake Fails with embedded Jetty 10 in equinox OSGi environment

### ISSUE THREAD

**Issue by tarzdorf** [Atmosphere/atmosphere#2473]
Dear Atmosphere Team,

i am currently trying to get atmosphere working in combination with Jetty 10 inside an OSGi application.
The current issue i am facing is this error message:

'ERROR WebSocketTransport WebSocket Handshake Failed'

The initial request sent to the Server is successful and processed by my implementation of the AtmosphereHandler, but it seems that  status code 200 is sent as response. Instead 101 (switching protocol) seems to be expected.

The message occurs in this method on the client side:
org.atmosphere.wasync.transport.WebSocketTransport.onStatusReceived

I am using org.atmosphere runtime 2.7.5 and org.atmosphere.wasync 2.1.7.
The Jetty version is 10.0.7.

The request on client side is created like this:
AtmosphereRequestBuilder request = client.newRequestBuilder();
request.method(Request.METHOD.GET);
request.uri(mServerUrl);
request.trackMessageLength(true);
request.encoder(new CustomEncoder());
request.decoder(new CustomDecoder());
request.transport(Request.TRANSPORT.WEBSOCKET);

I tried to debug on server side where the AtmosphereHandler is called, but i could not find the location where something could go wrong. It seems that just the default response status code 200 is sent as response.

Thanks for your support in advance. Every hint is appreciated.

Best regards
Thomas

**Comment by jfarcand** [comment]
@tarzdorf Can you try with wasync 3.0.0, which contains an updated version of the websocket client implementation?

**Comment by tarzdorf** [comment]
@jfarcand I upgraded to wasync 3.0.0 and all the necessary dependecies. Still i get the same Handshake error.

Now i tried to look very deep into this topic.
From what i can see the issue might be that on init phase the DefaultAsyncSupportResolver resolves to "org.jboss.netty", i.e. the class NettyCometSupport is used, which does not seem to have any Websocket related handling for Jetty.

JETTY_10 was added as constant here and the class is also found during the resolve phase, but does not help, because there is no implementation class for Jetty 10. To which class should this logic resolve then if JETTY_10 is "true"? The resolve logic only checks for "!isJetty10"...

if (!isJetty10 && testClassExists(JETTY_9))
                    add(Jetty7CometSupport.class);

                if (!isJetty10 && testClassExists(JETTY_8))
                    add(Jetty7CometSupport.class);

                if (!isJetty10 && testClassExists(JETTY_7))
                    add(Jetty7CometSupport.class);

                if (!isJetty10 && testClassExists(JETTY))
                    add(JettyCometSupport.class);
...
if (!isJetty10) {
                            if (testClassExists(JETTY_9)) {
                                add(Jetty9AsyncSupportWithWebSocket.class);
                                add(Jetty93AsyncSupportWithWebSocket.class);
                            } else if (testClassExists(JETTY_8))
                                add(JettyServlet30AsyncSupportWithWebSocket.class);
                        }

In would expect some class for Jetty 10 as there is for Jetty 9 or 8, e.g. Jetty10AsyncSupportWithWebSocket.

What do you think @jfarcand ?

**Comment by jfarcand** [comment]
@tarzdorf Interesting. It seems you have a netty dependencies in your classpath. If you remove it it will work as expected. Atmosphere doesn't support Jetty 10 native implementation and instead use the Servlet 3.x and Websocket 1.x default implementation... that's why there is no Jetty10... classes.

**Comment by tarzdorf** [comment]
@jfarcand thanks for your advice. So i followed it and switched to the JSR365 implementation by putting javax.websocket-api 1.1 on the classpath. The resolver picked it up and used the **JSR365AsyncSupport** from that point on. So far so good.

Still i got the Handshake error. I started to debug the whole init procedure of that and i actually found the source of my problem.

The issue is now that we are running Jetty as embedded Server inside the Eclipse Equinox OSGi container and the javax.websocket implementation uses java.util.ServiceLoader to load a Default implementation of **javax.websocket.server.ServerEndpointConfig.Configurator**.

This fails and the library throws a RuntimeException and thus the whole init and handshake procedure fails.
I found that 3 methods are affected by this:

1. boolean checkOrigin(String originHeaderValue)
2. String getNegotiatedSubprotocol(List<String> supported, List<String> requested)
3. List<Extension> getNegotiatedExtensions(List<Extension> installed, List<Extension> requested)

What i did now is to overwrite those 3 methods in **org.atmosphere.container.JSR356AsyncSupport.AtmosphereConfigurator**.
To check if that works i just used a very simple default implementation like returning true, empty string and empty list.
And this was successful in my scenario, thus it seems now that everything works as expected.

So now i am wondering how we can integreate this and i tried to prepare a proposal **JSR356AsyncSupport.AtmosphereConfigurator**.
I suggest to check if a default implementation of **ServerEndpointConfig.Configurator** can be found via the ServiceLoader and if so, then call the methods of the base class. If it cannot be found then use a default implementation for these 3 methods.

@jfarcand what do you think?
