### ISSUE TITLE
Move class JavaScriptProtocol into package cpr

### ISSUE THREAD

**Issue by yanyiyi-yi** [Atmosphere/atmosphere#2475]
Hi, @jfarcand 

**Issue Description**

Package _org.atmosphere.interceptor_ is a promiscuous package, and groups together miscellaneous functionalities that might be useful to different subsystems. This means the cohesion between classes in the package is low. However, since the project has grown larger, this package structure is becoming increasingly hard to navigate. We found that Class _JavaScriptProtocol_ is not used by classes in their package _org.atmosphere.interceptor_. Moreover, there is a lot of dependencies between class _JavaScriptProtocol_ and classes in the package org.atmosphere.cpr.

Location: The source file can be found at path File  /modules/cpr/src/main/java/org/atmosphere/interceptor/JavaScriptProtocol.java

**Refactoring suggestions**

To avoid making _org.atmosphere.interceptor_ too big and unmanageable, we suggest to move class _JavaScriptProtocol_ into package _org.atmosphere.cpr_.

<img width="400" alt="Atmosphere-JavaScriptProtocol-java" src="https://user-images.githubusercontent.com/29889989/162695097-0a6bef89-5099-40ca-a92d-8a84133fe88f.png">

**Comment by jfarcand** [comment]
Hi @FanyiMeng-NEU , I need more context about this compatibility breaking change. Originally  `JavaScriptProtocol` is located under the `interceptor` package because it extends the adapter. Why is it hard to navigate right now with the current structure? If you can share a scenario where it cause "problem"? Thanks!

**Comment by fymys** [comment]
> Hi @FanyiMeng-NEU , I need more context about this compatibility breaking change. Originally `JavaScriptProtocol` is located under the `interceptor` package because it extends the adapter. Why is it hard to navigate right now with the current structure? If you can share a scenario where it cause "problem"? Thanks!

The package structure violates the “high cohesion and low coupling” design rules. The project has grown larger, leading to becoming increasingly hard to maintain. For example, if one modifies package **_org.atmosphere.cpr_** (i.e., package rename), and forget to change class **_JavaScriptProtocol_** during the maintenance process, there are indirect consequences for the class **_JavaScriptProtocol_**.

**Comment by jfarcand** [comment]
@fymys Why would you rename the package? Sorry for asking so many questions but I don't understand your goal here? What are you doing exactly with Atmosphere (give me some context). Since the `JavaScriptProtocol` is exposed publicly, renaming it will break existing implementation of Atmosphere no?

**Comment by fymys** [comment]
Sorry for getting back to you late.
During the development process, one groups together classes (that often co-change) with similar functionalities in one package to facilitate maintenance, which prevents a change that causes other packages to be modified, such as modifying package **_org.atmosphere.cpr_**, resulting in class **_JavaScriptProtocol_** to be changed.
I just provide the suggestions from the perspective of subsequent maintenance.
