### ISSUE TITLE
Support atmosphere-spring for Jakarta 3.0  jakarta.servlet

### ISSUE THREAD

**Issue by sanushchacko** [Atmosphere/atmosphere#2484]
The atmosphere-spring module is still using "javax.servlet".
As the Spring framework 6.0.0-RC3 is already released to support Jakarta 3.0, when can we expect a new artifact for atmosphere-spring to support "jakarta.servlet"?.

Please note that atmosphere-runtime is already supporting Jakarta 3.0 https://github.com/Atmosphere/atmosphere/issues/2467

**Comment by jfarcand** [comment]
@sanushchacko If you have the cycle, feel free to produce a pull request. I will merge and do the release.

**Comment by chrisormad** [comment]
@jfarcand 

The spring GA release for the version 6 is done. The jars are available in maven central repository.
```
<dependency>
    <groupId>org.springframework</groupId>
    <artifactId>spring-core</artifactId>
    <version>6.0.0</version>
</dependency>
```
The latest atmosphere-spring (2.6.5) is still using import "javax.servlet.*". So the projects using atmosphere are blocked from updating to spring 6 release.

Can you please inform, is there any plan to provide a release for atmosphere-spring which uses import "jakarta.servlet.*".

**Comment by enermax626** [comment]
Hey, guys, I came across the same issue, no jakarta for atm-spring. Did you get an update since 2022? thanks!

**Comment by vinitkumar-lv** [comment]
Do we have any solution for this. still i see latest release is 2.6.5 supports javax not jakarta

**Comment by jfarcand** [comment]
@vinitkumar-lv contribution welcome :-)

**Comment by slovdahl** [comment]
I started looking into this, but one problem is that it needs to be built with JDK 17 because Spring 6 has a JDK 17 baseline. And it seems like not all components in `atmosphere-extensions` can be built on JDK 17.

**Comment by slovdahl** [comment]
Fixing the JDK 17 compatibility with https://github.com/Atmosphere/atmosphere-extensions/pull/264.
