### ISSUE TITLE
Websocket Closing Connection Again and Again

### ISSUE THREAD

**Issue by slimaye12** [Atmosphere/atmosphere#2492]
We have implemented Websocket in client and server architecture. But client is continuously dropping the connection. We have added all the configuration in config file as well as annotations.But still the connection keeps closing.The timeout is set to 9999 in config file for connection as well.

**Comment by jfarcand** [comment]
@slimaye12 Please share a test/app that demonstrate the issue. Usually it could be your infra causing the connection to be dropped. Re-open once I can see the issue
