### ISSUE TITLE
JDK17 breaks working Atmosphere

### ISSUE THREAD

**Issue by Justvuur** [Atmosphere/atmosphere#2494]
Recently updated from Java 11 to Java 17 and my Atmosphere setup is no longer working. 

Atmosphere Info
- version 2.7.6
- atmosphere.js version 2.3.6
- wasync 2.1.7

Jetty
-10.0.11

I was hoping it would be a smooth transition.
Is there perhaps a version compatibility issue?

**Screenshots**
![image](https://github.com/Atmosphere/atmosphere/assets/34640344/3386bd15-f731-4f64-ac24-dbd80f36feb2)

![image](https://github.com/Atmosphere/atmosphere/assets/34640344/3843b1b7-ba15-4ba4-8367-8a331edd0d8f)

![image](https://github.com/Atmosphere/atmosphere/assets/34640344/bfa2de53-f743-4985-9cc3-72b3fd1951dc)

**Comment by minemeraj** [comment]
Is there any update?
