### ISSUE TITLE
Long-polling requests show XML parsing syntax error in Firefox console

### ISSUE THREAD

**Issue by SuperPat45** [Atmosphere/atmosphere#2495]
**Describe the bug**
Although this has no impact on the web application, the Firefox console show this error:
> XML parsing error: syntax error
> Location : http://xxxxxxxxx?X-Atmosphere-tracking-id=0&X-Atmosphere-Framework=3.1.4-javascript&X-Atmosphere-Transport=long-polling&X-atmo-protocol=true&_=1691055538276
> Line number 2, Column 1 :

For each request where the response look like this:
>
> ff04cfe8-9ad3-47c8-b453-ed5dd768c461|60000|X|

This error appear because Firefox assumes that all response without Content-Type header is text/html or text/xml

**Atmosphere Info**
  - version 2.7.3
  - atmosphere.js version 3.1.4
  - extensions used

**Expected behavior**
To avoid these errors, long-pooling connections returning these flags "ff04cfe8-9ad3-47c8-b453-ed5dd768c461|60000|X|" should define the response header:
`Content-Type: text/plain`

**Systems (please complete the following information):**
 - OS: Windows 10
 - Browser name and version: Firefox 116
 - Java version and distribution: Java 17.0.3
 - Serveur name and version: WildFly 26

**Comment by jfarcand** [comment]
Thanks! Will take a look ASAP
