### ISSUE TITLE
"org.atmosphere.container.Jetty9AsyncSupportWithWebSocket" does not exist 

### ISSUE THREAD

**Issue by Sbennett99** [Atmosphere/atmosphere#2497]
**Describe the bug**
"org.atmosphere.container.Jetty9AsyncSupportWithWebSocket" does not exist 

**Atmosphere Info**
  - version 3.0.3
  - atmosphere.js NA
  - extensions used NA

**Expected behavior**
I was using that class for Comet Support

**Screenshots**
NA

**Systems (please complete the following information):**
 - OS: ROCKY 8
 - Browser name and version [e.g. chrome 22]
 - Java version and distribution :  redhat openjdk 17.0.2
 - Serveur name and version [Jetty 11]
 - 
**Additional context**

**Comment by jfarcand** [comment]
@Sbennett99 With Jakarta support only the WebSocket JSR runtime will be supported (Servlet30CometSupportWithWebsocket)
