### ISSUE TITLE
JSR356Endpoint dropping custom attributes on the HTTP request

### ISSUE THREAD

**Issue by amy-b-cheng** [Atmosphere/atmosphere#2502]
**Describe the bug**
I currently use Atmosphere 2.7.4 and Jetty 9.4.52 and am upgrading to Atmosphere 2.7.10 and Jetty 10.0.19. I'm running into a problem where I set attributes on the websocket upgrade request via GuiceFilter, but these attributes are not getting propagated as localAttributes to the AtmosphereRequest built in JSREndpoint. Before the upgrade, this was working as expected.

**Atmosphere Info**
  - 2.7.10
  - atmosphere.js 2.3.2
  - Used with: org.atmosphere:atmosphere-annotations:2.7.10, org.atmosphere:atmosphere-guice:2.6.5

**Expected behavior**
My websocket upgrade request goes through GuiceFilter (which sets some attributes on the HTTP request), then WebSocketUpgradeFilter, then when it gets to JSREndpoint, these attributes should be included in the created AtmosphereRequest's localAttributes.

**Screenshots**
N/A

**Systems (please complete the following information):**
 - Running on macOS Ventura (server is Linux)
 - Google Chrome 121
 - Java OpenJDK_11_AdoptOpenJDK_with_Hotspot
 - Jetty 10.0.19
 
**Additional context**
In JSREndpoint, under session -> coreSession -> handler -> upgradeRequest -> servletRequest -> request -> attributes, my custom attributes are present.
The created AtmosphereRequest.b.localAttributes is missing these.

**Comment by jfarcand** [comment]
@amy-b-cheng Can you share an app or a test case on github?

**Comment by amy-b-cheng** [comment]
@jfarcand Hi Jeanfrancois, it's going to take me some time to assemble a testcase since I'm unable to share my application with you. But in the meantime here are some code examples of what I'm talking about, for your clarity.

Here's JSR356Endpoint.java not setting the local attribute: https://github.com/Atmosphere/atmosphere/blob/24a1456c137e36dfe7c7a6b180ebe299713fb457/modules/cpr/src/main/java/org/atmosphere/container/JSR356Endpoint.java#L227

Here's an example where ProtocolUtil uses the same AtmosphereRequestImpl.Builder but copies the attributes over: https://github.com/Atmosphere/atmosphere/blob/24a1456c137e36dfe7c7a6b180ebe299713fb457/modules/cpr/src/main/java/org/atmosphere/websocket/protocol/ProtocolUtil.java#L38

If you were to use AtmosphereRequestImpl#wrap, it would take into account the local attributes:
https://github.com/Atmosphere/atmosphere/blob/atmosphere-2.7.x/modules/cpr/src/main/java/org/atmosphere/cpr/AtmosphereRequestImpl.java#L1409C1-L1423C6

Let me know if that helps you or if you still need a test case to understand this issue.

**Comment by vaslabs** [comment]
wow, thanks @amy-b-cheng , I have the same issue with Tomcat, indeed the attributes are not copied over. I'll test locally and send a PR if it works out

**Comment by jfarcand** [comment]
@vaslabs That would be perfect if you can start a PR. I will look at it and integrate/release ASAP.

**Comment by vaslabs** [comment]
hello, thanks @jfarcand for your response. It looks to me that there's no way to get the request attributes in the JSR356 implementation, as the HandshakeRequest doesn't require them . For my case tomcat's WsHandshakeRequest doesn't use them as they are of course not required by HandshakeRequest.

So, it seems not possible for servlet filters to add attributes to the HttpServletRequest right now and the only solution I can see is setting Session attributes instead.

This doesn't seem to be a problem for atmosphere but the way `javax.websocket.server.HandshakeRequest` is defined, it doesn't consider itself with request attributes.

**Comment by amy-b-cheng** [comment]
@vaslabs are the attributes not in the HandshakeRequest#getHttpSession? I'm trying to see right now if copying over those will fix my problem

**Comment by amy-b-cheng** [comment]
Yes, the above code is copying the handshakeSession attributes to the AtmosphereRequestImpl. With this change + if inside my ServletFilter I set my custom attributes (which were previously going on the HTTP request) to now go on the session itself, I'm able to read the attributes off the AtmosphereResource downstream.

@jfarcand should I open a pull request?

**Comment by jfarcand** [comment]
@amy-b-cheng Yes, will take a look!
