### ISSUE TITLE
java.nio.ByteBuffer.flip()

### ISSUE THREAD

**Issue by fcorneli** [Atmosphere/atmosphere#2507]
Atmosphere version: 2.7.14
Java version: 8
We get the following exception:
```
15:21:08,709 ERROR [org.atmosphere.cpr.AsynchronousProcessor] (nioEventLoopGroup-3-5) : java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
	at org.atmosphere.client.TrackMessageSizeInterceptor$Interceptor.transformPayload(TrackMessageSizeInterceptor.java:173)
```
This did not happen on Atmosphere versions 2.7.10, 2.7.11.

**Comment by jfarcand** [comment]
Ah got it. The release has probably been made using jdk 21.

**Comment by fcorneli** [comment]
Yep. Was just also thinking about this... :)

**Comment by fcorneli** [comment]
@jfarcand Not urgent from our side.

**Comment by fcorneli** [comment]
@jfarcand Any news on a release?

**Comment by jfarcand** [comment]
@fcorneli Today and at worse, tomorrow!

**Comment by jfarcand** [comment]
Done. Apology for the delay.

**Comment by fcorneli** [comment]
Tested version 2.7.15 on a Java 8 based runtime. All OK, thanks.
