### ISSUE TITLE
Misleading Documentation

### ISSUE THREAD

**Issue by TobiasKiecker** [Atmosphere/atmosphere#2514]
The class `AtmosphereFramework.java` contains the function `initializationError`
https://github.com/Atmosphere/atmosphere/blob/d350bc5a8a46663fd54d82ba545dcfa5854f66b0/modules/cpr/src/main/java/org/atmosphere/cpr/AtmosphereFramework.java#L3441-L3448

The current docstring is very misleading because the function is not doing any logging.

A better documentation would probably be:

`* If a {@link ContainerInitializer} fails, set the field initializationError for later logging purposes.`

or 

`* If a {@link ContainerInitializer} fails, set the field initializationError here.`

**Comment by slovdahl** [comment]
Happy to improve it, would you like to submit a PR with your suggested change?

**Comment by TobiasKiecker** [comment]
Yes, I will do that.
