### ISSUE TITLE
resource.getRequest().getCookies() doesn't work

### ISSUE THREAD

**Issue by PavelR577** [Atmosphere/atmosphere#485]
tested with version 1.0.0.beta2a (0.9.4 also) .

resource.getRequest().getCookies() - returns empty.
resource.getRequest().getHeader("cookie") - return the cookies (works)

**Comment by jaltman7** [comment]
This seems to be happening again on Tomcat 8, as well as with Jetty 9.x on the latest version of atmosphere-runtime.  From what I have seen I feel like anyone who is going through the JSR356AsyncSupport -> JSR356Endpoint is not getting cookies, but is getting a header with the cookies as a string.

**Comment by gvillegas** [comment]
It is happening again, I have been trying to also read request's attributes I set in a Filter before reaching a Managed Service, and none of them are found inside the resource's AtmosphereRequest. Could this issue be related, or is a normal behavior that Websocket transport drops these attributes before reaching the Managed Service?

BTW I found that someone already reported the cookies issue again: https://groups.google.com/forum/embed/?place=forum/atmosphere-framework&showsearch=true&showpopout=true&showtabs=false&parenturl=http%3A%2F%2Fasync-io.org%2Fdownload.html#!topic/atmosphere-framework/qbicJoaKmpU

Regards

**Comment by jaltman7** [comment]
Should this be reopened or file a new issue?

**Comment by jfarcand** [comment]
@jaltman7 Reopen a new one ... with a fix :-)
