### ISSUE TITLE
[jQuery] streaming, IE , disconnect event not fired when server closed

### ISSUE THREAD

**Issue by PavelR577** [Atmosphere/atmosphere#559]
1. open streaming connection to the server
2. close the server.
3. disconnect event is not fired (works on FF and Chrome)

**Comment by c-venkatesh-mca** [comment]
Can you post the solution u tried. I am also facing the same issue.

**Comment by c-venkatesh-mca** [comment]
@poi212003 
Can you give the solution u tried. I am also facing same issue.
@flowersinthesand,
Can you give me any additional measure we can take to detect the disconnection when we use streaming transport.
