### ISSUE TITLE
Make Message UUID generator pluggable

### ISSUE THREAD

**Issue by werdex** [Atmosphere/atmosphere#626]
Message id is generated using UUID.randomUUID() which uses SecureRandom and it will be very slow on linux systems when creating many messages :) 
http://stackoverflow.com/questions/137212/how-to-solve-performance-problem-with-java-securerandom 
For most cases incremental integer generator will be enough: AtomicLong.incrementAndGet. However, it is possible that in some cases a global unique UUID will be required (in clustered environment?). So it's better to make such generator pluggable.
```java
public interface UidGenerator {
String generate();
}
```

**Comment by jfarcand** [comment]
Fixed https://github.com/Atmosphere/atmosphere/commit/725d526d717a316611c76094c79c026d689571fe

**Comment by slovdahl** [comment]
The fix isn't complete, [BroadcastMessage.java](https://github.com/Atmosphere/atmosphere/blob/2b479193a15e46d0751fb2b51daebc4c891447cb/modules/cpr/src/main/java/org/atmosphere/cache/BroadcastMessage.java) still has UUID.randomUUID() hard coded.

**Comment by jfarcand** [comment]
@slovdahl That one can't be changed. Instead the API should be deprecated.
