### ISSUE TITLE
Feature Request: Broadcaster groups

### ISSUE THREAD

**Issue by svenjacobs** [Atmosphere/atmosphere#671]
I would like to propose a new feature to easily organize and access groups of Broadcasters with same semantics. Currently it's only possible to access similar Broadcasters if the have a path-style id `/some/path/ID` with a common path through `MetaBroadcaster#broadcast("/some/path", ...)`

Let's assume we have an application with a WebSocket resource where every client receives unique messages and thus we need individual broadcasters for each client

``` java
@GET
@Suspend
public String subscribe(@QueryParam("clientUUID") Broadcaster broadcaster) {
    // ...
}
```

Here the client's unique id `clientUUID` is assigned to the broadcaster's id.

But what if I occasionally want to send a common message to all clients? The broadcaster ids are not path-like. Of course I could make them path-like but this wouldn't feel right, especially if I want to query a broadcaster for a specific client (cannot just use the client's uuid). Here I think Broadcaster groups would be handy. Something like

``` java
@GET
@Suspend
public String subscribe(@QueryParam("clientUUID") @BroadcasterGroup("clients") Broadcaster broadcaster) {
    // ...
}

MetaBroadcaster.getDefault().broadcastToGroup("clients", message, ...);

MetaBroadcaster.getDefault().scheduleToGroup("clients", message, ...);

Collection<Broadcaster> clientBroadcasters = BroadcasterFactory.getDefault().lookupGroup("clients");
```

**Comment by jfarcand** [comment]
Next official version https://github.com/Atmosphere/Atmosph4rX
