### ISSUE TITLE
Shiro & null ServletContext

### ISSUE THREAD

**Issue by skaddy** [Atmosphere/atmosphere#724]
Hello,
thank you for this amazing framework you have developed!

I'm building a webapp which relies on Atmosphere to provide Websocket support and Long-polling/Http Streaming fallback, it worked perfectly till I plugged Shiro authentication.

Shiro needs to get the ServletContext in order to bind the current user but every time the connection is made with Websocket I get a null ServletContext, using Http Streaming or Long Polling it works perfectly.

Regards,
Andrea

**Comment by Shabirmean** [comment]
How do you get this working with the fix? Is there any docs related to this?
